// TASKS & CARE — task rows are ACTION SURFACES (complete without opening). Quick Care = bulk care board.
import { esc, actions } from '../core/dom.js';
import { icon } from '../core/icons.js';
import { t } from '../core/i18n.js';
import * as store from '../core/store.js';
import { menu } from '../core/overlay.js';
import { SPECIES, latin, SUPPLEMENTS } from '../data/species.js';
import { TYPE, rotationState } from '../engine/ops.js';
import { buildTimeline, isOpen } from '../engine/timeline.js';
import * as A from '../engine/actions.js';
import { streamHTML, contextItems } from '../ui/timeline.js';
import { openQuickRecord } from '../ui/quickrecord.js';
import { avatar, chip, seg, empty } from '../ui/components.js';
import { done } from '../ui/feedback.js';
import { DAY, startOfDay, hm, rel } from '../core/time.js';

const QC = { type: 'feeding', sel: new Set(), scope: 'due', lastSel: [] };
try { QC.lastSel = JSON.parse(localStorage.getItem('irmB.qcsel') || '[]'); } catch {}
let showDone = false;

function counts() {
  const n = Date.now(), sod = startOfDay(n);
  const it = contextItems({ from: sod - 7 * DAY, to: sod + 15 * DAY, includeHistory: false }).filter((i) => i.kind !== 'phase');
  return { today: it.filter((i) => isOpen(i) && i.t < sod + DAY && i.t >= sod).length, upcoming: it.filter((i) => isOpen(i) && i.t >= sod + DAY).length, overdue: it.filter((i) => i.status === 'overdue').length };
}
export function context(r) {
  const c = counts();
  return { counts: { today: c.today, upcoming: c.upcoming, overdue: c.overdue }, sub: 'Record work — not create it',
    actions: [{ label: 'Quick Care', icon: 'zap', act: 'go', data: { href: '#/tasks/quick' }, hideM: true }, { label: '+ Task', icon: 'plus', act: 'quick-record', data: { type: 'task' }, primary: true, kbd: 'N' }] };
}
export function onNew() { openQuickRecord({ type: 'task' }); }

export function render(r) {
  const sub = r.sub || 'today', n = Date.now(), sod = startOfDay(n);
  if (sub === 'quick') return quickCare();
  let items, empt;
  if (sub === 'today') { items = contextItems({ from: sod - 7 * DAY, to: sod + DAY, includeHistory: showDone }).filter((i) => i.kind !== 'phase' && (i.t >= sod || isOpen(i))); empt = 'Nothing left for today — well done.'; }
  if (sub === 'upcoming') { items = contextItems({ from: sod + DAY, to: sod + 15 * DAY, includeHistory: false }).filter((i) => i.kind !== 'phase' && isOpen(i)); empt = 'Nothing scheduled in the next 14 days.'; }
  if (sub === 'overdue') { items = contextItems({ from: sod - 14 * DAY, to: n, includeHistory: false }).filter((i) => i.status === 'overdue'); empt = 'No overdue work.'; }
  if (sub === 'done') { items = contextItems({ from: sod - 7 * DAY, to: n + DAY, includeHistory: true }).filter((i) => ['done', 'skipped', 'cancelled'].includes(i.status) && i.kind !== 'phase' && i.kind !== 'milestone' && i.record?.source !== 'history').sort((a, b) => b.t - a.t); empt = 'Nothing completed in the last 7 days.'; }
  const c = counts();
  const head = `<div class="task-head">
    <div class="th-kpi"><b>${c.today}</b><span>open today</span></div><div class="th-kpi ${c.overdue ? 'bad' : ''}"><b>${c.overdue}</b><span>overdue</span></div><div class="th-kpi"><b>${c.upcoming}</b><span>next 14 days</span></div>
    <div class="spacer"></div>
    ${sub === 'today' ? `<label class="row sm-t"><input type="checkbox" class="switch" data-change="tk-done" ${showDone ? 'checked' : ''}><span>Show completed</span></label>` : ''}
    <a class="btn sm" href="#/planner/timeline">${icon('planner')}Open in Planner</a>
  </div>`;
  if (sub === 'done') return head + (items.length ? doneList(items) : empty(empt, '', 'tasks'));
  return head + (items.length ? streamHTML(items, { mode: 'full', showDone: true, empty: empt }) : empty(empt, 'Routine care is generated by care plans; use + Task for one-off work.', 'tasks', `<button class="btn primary" data-act="quick-record" data-type="task">${icon('plus')}New task</button>`));
}
function doneList(items) {
  const byDay = {}; for (const i of items) (byDay[startOfDay(i.t)] ||= []).push(i);
  return Object.entries(byDay).sort((a, b) => b[0] - a[0]).map(([d, arr]) => `<div class="tl-sec sec-past"><div class="tl-sech"><b>${new Date(+d).toDateString()}</b><em>${arr.length}</em><i></i></div>${arr.map((i) => streamHTML([i], { mode: 'full' }).replace(/<div class="tl-sec sec-now"[\s\S]*?Nothing due right now<\/div><\/div>/, '')).join('')}</div>`).join('');
}

// ---------------------------------------------------------------- QUICK CARE — bulk identical care in 2–4 interactions
function quickCare() {
  const db = store.get(), n = Date.now(), sod = startOfDay(n);
  const due = buildTimeline(db, { from: sod - 3 * DAY, to: sod + DAY, includeHistory: false }).filter((i) => i.kind === 'occ' && isOpen(i) && i.type === QC.type && i.subjectKind === 'animal');
  const dueMap = new Map(due.map((i) => [i.subject, i]));
  let animals = db.animals.filter((a) => !['sold', 'deceased'].includes(a.status));
  if (QC.scope === 'due') animals = animals.filter((a) => dueMap.has(a.id));
  const types = [['feeding', 'Feeding', 'feed'], ['water', 'Water', 'water'], ['misting', 'Misting', 'mist'], ['cleaning', 'Cleaning', 'clean'], ['weight', 'Weight', 'weight']];
  const species = [...new Set(animals.map((a) => a.species))];
  const encs = [...new Set(animals.map((a) => a.enclosureId).filter(Boolean))];
  const sel = QC.sel;
  const selTiles = animals.map((a) => {
    const i = dueMap.get(a.id), on = sel.has(a.id), plan = db.plans.find((p) => p.subject === a.id && p.type === QC.type);
    const rs = plan && QC.type === 'feeding' ? rotationState(db, plan) : null;
    return `<button class="qc-tile ${on ? 'on' : ''} ${i?.status === 'overdue' ? 'late' : ''}" data-act="qc-toggle" data-id="${a.id}" aria-pressed="${on}">
      <span class="qc-img">${avatar(a, 64)}<span class="qc-cb">${icon('check')}</span></span>
      <span class="qc-t"><b class="code">${esc(a.code)}</b>${a.kind === 'group' ? `<em>×${a.count}</em>` : ''}</span><i class="latin">${esc(latin(SPECIES[a.species]))}</i>
      <span class="qc-m">${i ? `<span class="${i.status === 'overdue' ? 'danger-t' : ''}">${hm(i.t)}${i.status === 'overdue' ? ' · late' : ''}</span>` : '<span class="muted">not due</span>'}${rs?.next ? `<span class="mt sup" style="--c:${SUPPLEMENTS[rs.next]?.color}">${esc(rs.next)}</span>` : ''}</span></button>`;
  }).join('');
  return `<div class="qc">
    <div class="qc-bar">
      <div class="qc-types">${types.map(([k, l, ic]) => `<button class="qc-type ${QC.type === k ? 'on' : ''}" data-act="qc-type" data-v="${k}" style="--c:${TYPE[k].color}">${icon(ic)}<span>${l}</span><em>${buildTimeline(db, { from: sod - 3 * DAY, to: sod + DAY, includeHistory: false }).filter((i) => i.kind === 'occ' && isOpen(i) && i.type === k).length}</em></button>`).join('')}</div>
      ${seg([['due', 'Due now'], ['all', 'All animals']], QC.scope, 'qc-scope')}
    </div>
    <div class="qc-select"><span class="muted">Select</span>
      ${chip('All', { act: 'qc-sel', data: { v: 'all' } })}${chip('Visible', { act: 'qc-sel', data: { v: 'visible' } })}${chip("Today's group", { act: 'qc-sel', data: { v: 'due' }, icon: 'clock' })}
      ${chip('By group…', { act: 'qc-selmenu', data: { v: 'group' }, icon: 'group' })}${chip('By species…', { act: 'qc-selmenu', data: { v: 'species' }, icon: 'animals' })}${chip('By enclosure…', { act: 'qc-selmenu', data: { v: 'enclosure' }, icon: 'enclosure' })}
      ${QC.lastSel.length ? chip(`Recent selection (${QC.lastSel.length})`, { act: 'qc-sel', data: { v: 'recent' }, icon: 'history' }) : ''}${sel.size ? chip('Clear', { act: 'qc-sel', data: { v: 'none' }, icon: 'x' }) : ''}</div>
    ${animals.length ? `<div class="qc-grid">${selTiles}</div>` : empty(`No ${TYPE[QC.type].label.toLowerCase()} due`, 'Switch to “All animals” to record unscheduled care.', 'tasks')}
    <div class="qc-go ${sel.size ? 'on' : ''}"><div><b>${sel.size}</b> selected<span class="muted"> · each animal receives its own history record${QC.type === 'feeding' ? ' and its next supplement from the rotation' : ''}</span></div>
      ${QC.type === 'feeding' ? `<button class="btn lg" data-act="qc-run" data-refused="1" ${sel.size ? '' : 'disabled'}>${icon('ban')}Refused</button>` : ''}
      <button class="btn primary lg" data-act="qc-run" ${sel.size ? '' : 'disabled'}>${icon('check')}${QC.type === 'weight' ? 'Enter weights' : `Complete ${TYPE[QC.type].label.toLowerCase()}`} · ${sel.size}</button></div>
  </div>`;
}
actions({
  'tk-done': (el) => { showDone = el.checked; store.emit('change'); },
  'qc-type': (el) => { QC.type = el.dataset.v; QC.sel.clear(); store.emit('change'); },
  'qc-scope': (el) => { QC.scope = el.dataset.v; store.emit('change'); },
  'qc-toggle': (el) => { const id = el.dataset.id; QC.sel.has(id) ? QC.sel.delete(id) : QC.sel.add(id); store.emit('change'); },
  'qc-sel': (el) => {
    const db = store.get(), v = el.dataset.v, n = Date.now();
    const due = buildTimeline(db, { from: startOfDay(n) - 3 * DAY, to: startOfDay(n) + DAY, includeHistory: false }).filter((i) => i.kind === 'occ' && isOpen(i) && i.type === QC.type).map((i) => i.subject);
    const vis = [...document.querySelectorAll('.qc-tile')].map((b) => b.dataset.id);
    if (v === 'none') QC.sel.clear();
    if (v === 'all' || v === 'visible') vis.forEach((id) => QC.sel.add(id));
    if (v === 'due') due.forEach((id) => QC.sel.add(id));
    if (v === 'recent') QC.lastSel.forEach((id) => QC.sel.add(id));
    store.emit('change');
  },
  'qc-selmenu': (el) => {
    const db = store.get(), v = el.dataset.v, vis = [...document.querySelectorAll('.qc-tile')].map((b) => db.animals.find((a) => a.id === b.dataset.id)).filter(Boolean);
    const pick = (fn) => { vis.filter(fn).forEach((a) => QC.sel.add(a.id)); store.emit('change'); };
    let items = [];
    if (v === 'species') items = [...new Set(vis.map((a) => a.species))].map((k) => ({ icon: 'animals', label: latin(SPECIES[k]), hint: String(vis.filter((a) => a.species === k).length), run: () => pick((a) => a.species === k) }));
    if (v === 'enclosure') { const byAs = {}; for (const a of vis) { const e = db.enclosures.find((x) => x.id === a.enclosureId); const key = e?.assemblyId || e?.id; if (key) (byAs[key] ||= []).push(a); } items = Object.entries(byAs).map(([k, arr]) => ({ icon: 'enclosure', label: db.assemblies.find((x) => x.id === k)?.name || db.enclosures.find((x) => x.id === k)?.code, hint: String(arr.length), run: () => pick((a) => arr.includes(a)) })); }
    if (v === 'group') items = [{ icon: 'group', label: 'Group enclosures (frogs)', run: () => pick((a) => a.kind === 'group') }, { icon: 'animals', label: 'Individuals only', run: () => pick((a) => a.kind !== 'group') }, { icon: 'repro', label: 'Breeding animals', run: () => pick((a) => a.breeding && a.breeding !== 'resting') }];
    menu(el, items, { title: `Select by ${v}` });
  },
  'qc-run': (el) => {
    const ids = [...QC.sel]; if (!ids.length) return;
    if (QC.type === 'weight') { openQuickRecord({ type: 'weight', subjects: [ids[0]] }); return; }
    QC.lastSel = ids; try { localStorage.setItem('irmB.qcsel', JSON.stringify(ids)); } catch {}
    const res = A.quickRecord(QC.type, ids, el.dataset.refused ? { refused: true } : {});
    QC.sel.clear(); done(res);
  },
});
