// Shared visual components (HTML-string renderers). Everything visual in Concept B is built from these.
import { esc, cls } from '../core/dom.js';
import { icon } from '../core/icons.js';
import { SPECIES, imgFor, latin, macroFor } from '../data/species.js';
import { TYPE } from '../engine/ops.js';
import { art } from './art.js';

export const sexIcon = (s) => (s === 'm' ? `<span class="sex m" title="Male">${icon('male')}</span>` : s === 'f' ? `<span class="sex f" title="Female">${icon('female')}</span>` : `<span class="sex u" title="Unsexed">${icon('unknownSex')}</span>`);
/** 2.2.0 notation for groups, ♂/♀ icon for individuals */
export function sexText(a) {
  if (a.kind === 'group') { const s = a.sexes || {}; return `<span class="mono sexes" title="males.females.unsexed">${s.m || 0}.${s.f || 0}.${s.u || 0}</span>`; }
  return sexIcon(a.sex);
}
export const spName = (key, { common = true, small = false } = {}) => {
  const sp = SPECIES[key]; if (!sp) return '';
  return `<span class="spn ${small ? 'sm' : ''}"><i class="latin">${esc(latin(sp))}</i>${common ? `<span class="common">${esc(sp.common)}</span>` : ''}</span>`;
};
export function avatar(a, size = 40, extra = '') {
  return `<span class="av ${extra}" style="--s:${size}px"><img src="${imgFor(a)}" alt="" loading="lazy" decoding="async"></span>`;
}
const STATUS = { active: ['Active', ''], 'for-sale': ['For sale', 'ok'], reserved: ['Reserved', 'info'], sold: ['Sold', 'mute'], deceased: ['Deceased', 'mute'], quarantine: ['Quarantine', 'warn'] };
export const statusPill = (s) => { const [l, k] = STATUS[s] || [s, '']; return `<span class="pill ${k}">${esc(l)}</span>`; };
const BREED = { breeding: ['Breeding', 'repro'], paired: ['Paired', 'repro'], gravid: ['Gravid', 'repro'], cycling: ['Cycling', 'repro'], 'post-lay': ['Post-lay', 'repro'], 'pre-brumation': ['Pre-brumation', 'info'], resting: ['', ''] };
export const breedPill = (b) => { const [l, k] = BREED[b] || ['', '']; return l ? `<span class="pill ${k}">${icon('repro')}${esc(l)}</span>` : ''; };
export const typeDot = (type) => `<span class="tdot" style="--c:${TYPE[type]?.color || 'var(--text-3)'}">${icon(TYPE[type]?.icon || 'dot')}</span>`;
export const originTag = (o) => ({ auto: `<span class="org auto" title="Automatic">${icon('bolt')}AUTO</span>`, 'care-plan': `<span class="org plan" title="Generated by a care plan">${icon('repeat')}PLAN</span>`, manual: `<span class="org man" title="Manual">${icon('edit')}MANUAL</span>`, reproduction: `<span class="org repro" title="Reproduction cycle">${icon('repro')}REPRO</span>` }[o] || '');
export const kbd = (k) => `<kbd>${esc(k)}</kbd>`;
export const empty = (title, text = '', artKey = 'empty', actionHTML = '') => `<div class="empty">${art(artKey)}<h3>${esc(title)}</h3>${text ? `<p>${text}</p>` : ''}${actionHTML}</div>`;

/** Visual KPI card: image/illustration layer + big figure + meaning. size: 'lg' | 'md' | 'sm' */
export function kpi({ label, value, unit = '', sub = '', img, artKey, href, tone = '', size = 'md', trend, extra = '' }) {
  const bg = img ? `<img class="kpi-img" src="${img}" alt="" loading="lazy" decoding="async">` : artKey ? `<div class="kpi-art">${art(artKey)}</div>` : '';
  const tag = href ? 'a' : 'div';
  return `<${tag} class="kpi ${size} ${tone}" ${href ? `href="${href}"` : ''}>${bg}<div class="kpi-shade"></div>
    <div class="kpi-body"><span class="kpi-l">${esc(label)}</span><span class="kpi-v">${value}<small>${esc(unit)}</small></span>${sub ? `<span class="kpi-s">${sub}</span>` : ''}${trend ? `<span class="kpi-t ${trend.dir}">${icon(trend.dir === 'up' ? 'trendUp' : 'trendDown')}${esc(trend.text)}</span>` : ''}${extra}</div></${tag}>`;
}

/** Sparkline (SVG path) */
export function spark(values, { w = 120, h = 32, color = 'var(--amber)', fill = true, dots = false } = {}) {
  if (!values.length) return '';
  const min = Math.min(...values), max = Math.max(...values), r = max - min || 1;
  const pts = values.map((v, i) => [values.length === 1 ? w / 2 : (i / (values.length - 1)) * (w - 4) + 2, h - 3 - ((v - min) / r) * (h - 6)]);
  const d = pts.map((p, i) => `${i ? 'L' : 'M'}${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join('');
  return `<svg class="spark" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" aria-hidden="true">${fill ? `<path d="${d}L${pts[pts.length - 1][0]} ${h}L${pts[0][0]} ${h}Z" fill="${color}" opacity=".12"/>` : ''}<path d="${d}" fill="none" stroke="${color}" stroke-width="1.6" stroke-linejoin="round"/>${dots ? pts.map((p) => `<circle cx="${p[0]}" cy="${p[1]}" r="1.8" fill="${color}"/>`).join('') : `<circle cx="${pts[pts.length - 1][0]}" cy="${pts[pts.length - 1][1]}" r="2.4" fill="${color}"/>`}</svg>`;
}
/** Grouped bars (income vs expense etc.) */
export function bars(series, labels, { h = 150, colors = ['var(--c-fin)', 'var(--danger)'], names = [], fmt = (v) => v } = {}) {
  const max = Math.max(1, ...series.flat());
  const n = labels.length, gw = 100 / n;
  return `<div class="bars" style="--h:${h}px">${labels.map((l, i) => `<div class="bar-g" style="width:${gw}%">${series.map((s, k) => `<i style="height:${(s[i] / max) * 100}%;background:${colors[k]}" title="${esc(names[k] || '')} ${fmt(s[i])}"></i>`).join('')}<span>${esc(l)}</span></div>`).join('')}</div>`;
}
/** Progress ring */
export function ring(p, { size = 56, stroke = 5, color = 'var(--amber)', label = '' } = {}) {
  const r = (size - stroke) / 2, c = 2 * Math.PI * r, v = Math.max(0, Math.min(1, p));
  return `<span class="ring" style="--s:${size}px"><svg viewBox="0 0 ${size} ${size}"><circle cx="${size / 2}" cy="${size / 2}" r="${r}" stroke="var(--line-2)" stroke-width="${stroke}" fill="none"/><circle cx="${size / 2}" cy="${size / 2}" r="${r}" stroke="${color}" stroke-width="${stroke}" fill="none" stroke-linecap="round" stroke-dasharray="${c}" stroke-dashoffset="${c * (1 - v)}" transform="rotate(-90 ${size / 2} ${size / 2})"/></svg><b>${label}</b></span>`;
}
/** Biological range bar: day axis 0..max, expected window [a,b], current day marker. Honest ranges, never a single date. */
export function rangeBar(day, [a, b], { max = Math.round(b * 1.12), label = true } = {}) {
  const x = (v) => `${Math.max(0, Math.min(100, (v / max) * 100))}%`;
  const state = day < a ? 'before' : day <= b ? 'in' : 'after';
  return `<div class="rangebar ${state}" role="img" aria-label="Day ${day}, expected ${a}–${b} days">
    <div class="rb-track"><i class="rb-fill" style="width:${x(day)}"></i><i class="rb-win" style="left:${x(a)};width:calc(${x(b)} - ${x(a)})"></i><i class="rb-now" style="left:${x(day)}"></i></div>
    ${label ? `<div class="rb-lab"><span style="left:0">0</span><span style="left:${x(a)}">${a}</span><span style="left:${x(b)}">${b}</span><b style="left:${x(day)}">day ${day}</b></div>` : ''}</div>`;
}
export const macroBg = (key) => `<img class="macro" src="${macroFor(key)}" alt="" loading="lazy" decoding="async">`;
export const chip = (label, { icon: ic, act, data = {}, on = false, tone = '' } = {}) => `<button class="chip ${on ? 'on' : ''} ${tone}" ${act ? `data-act="${act}"` : ''} ${Object.entries(data).map(([k, v]) => `data-${k}="${esc(v)}"`).join(' ')}>${ic ? icon(ic) : ''}${esc(label)}</button>`;
export const seg = (opts, cur, act, key = 'v') => `<div class="seg" role="radiogroup">${opts.map(([v, l, ic]) => `<button role="radio" aria-checked="${v === cur}" class="${v === cur ? 'on' : ''}" data-act="${act}" data-${key}="${esc(v)}">${ic ? icon(ic) : ''}<span>${esc(l)}</span></button>`).join('')}</div>`;
export const money = (v, cur = 'CZK') => `${Math.round(v).toLocaleString('cs-CZ').replace(/ /g, ' ')} ${cur === 'CZK' ? 'Kč' : cur}`;
export const num = (v, d = 0) => (+v).toLocaleString('en-US', { maximumFractionDigits: d, minimumFractionDigits: 0 });
export const card = (title, body, { icon: ic, actions = '', cls: c = '', sub = '' } = {}) => `<section class="card ${c}"><header class="card-h">${ic ? `<span class="card-ico">${icon(ic)}</span>` : ''}<h3>${title}</h3>${sub ? `<span class="card-sub">${sub}</span>` : ''}<span class="card-a">${actions}</span></header><div class="card-b">${body}</div></section>`;
export { cls };
