const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const BASE = 'http://localhost:8095/ir-manager-obsidian-preview/index.html';
const OUT = process.argv[2];
(async () => {
  const b = await chromium.launch({ args: ['--disable-gpu'] });
  const mk = async (w, h, dpr = 1, mobile = false) => { const ctx = await b.newContext({ viewport: { width: w, height: h }, deviceScaleFactor: dpr, timezoneId: 'Europe/Prague', locale: 'cs-CZ', hasTouch: mobile, isMobile: mobile }); const p = await ctx.newPage(); await p.clock.setFixedTime(new Date('2026-09-29T10:40:00+02:00')); await p.goto(BASE + '#/prehled'); await p.waitForTimeout(1300); return p; };
  const go = async (p, hash, ms = 900) => { await p.evaluate((x) => (location.hash = x), hash); await p.waitForTimeout(ms); await p.mouse.move(5, 890); };
  const shot = async (p, name, opt = {}) => { await p.waitForTimeout(250); await p.screenshot({ path: `${OUT}/${name}.png`, ...opt }); console.log('saved', name); };
  const top = (p) => p.evaluate(() => (document.getElementById('view').scrollTop = 0));
  const d = await mk(1440, 900);
  await shot(d, 'desktop-01-prehled');
  await go(d, '#/ukoly/planovac', 1200); await shot(d, 'desktop-02-planovac');
  await d.click('.pl-bar [data-act=pl-xs]'); await d.waitForTimeout(500); await top(d); await shot(d, 'desktop-03-planovac-rozsireny-harmonogram');
  await d.click('.pl-bar [data-act=pl-xs]');
  await go(d, '#/ukoly/dnes'); await shot(d, 'desktop-04-ukoly-dnes');
  await go(d, '#/zvirata/mrizka'); await d.hover('.an-card >> nth=2'); await d.waitForTimeout(350); await shot(d, 'desktop-05-zvirata-mrizka');
  await go(d, '#/zvirata/tabulka'); await shot(d, 'desktop-06-zvirata-tabulka');
  await go(d, '#/zvirata/karta/a_fp01'); await shot(d, 'desktop-07-karta-zvirete');
  await go(d, '#/zvirata/karta/a_pr02?sekce=chov'); await shot(d, 'desktop-08-karta-chov-reprodukce');
  await go(d, '#/reprodukce/prehled'); await shot(d, 'desktop-09-reprodukce');
  await go(d, '#/reprodukce/inkubace'); await shot(d, 'desktop-10-inkubace');
  await go(d, '#/zdravi/prehled'); await d.click('[data-act=hf-an] >> nth=0'); await d.click('[data-act=hf-obs] >> nth=2'); await d.waitForTimeout(300); await shot(d, 'desktop-11-zdravi');
  await go(d, '#/ubikace/prehled'); await shot(d, 'desktop-12-ubikace');
  await go(d, '#/sklad/prehled'); await shot(d, 'desktop-13-sklad');
  await go(d, '#/finance/prehled'); await shot(d, 'desktop-14-finance');
  await go(d, '#/adresar/kontakty'); await shot(d, 'desktop-15-adresar');
  await go(d, '#/nastroje?n=calculator'); for (const k of ['1', '2', '×', '3', '6', '=']) await d.click(`.calc-k [data-k="${k}"]`); await shot(d, 'desktop-16-nastroje');
  await go(d, '#/nastroje?n=shopping'); await shot(d, 'desktop-17-nastroje-nakupni-seznam');
  await go(d, '#/prehled'); await d.click('[data-act=ws-edit][data-ws=prehled]'); await d.waitForTimeout(500); await d.evaluate(() => { const v = document.getElementById('view'); v.scrollTop = document.querySelector('.wsp').offsetTop - 80; }); await shot(d, 'desktop-18-upravit-prehled');
  await d.click('.wsp-bar [data-act=ws-add]'); await d.waitForTimeout(500); await shot(d, 'desktop-19-knihovna-widgetu');
  await d.click('.lib-cats [data-cat="Nástroje"]'); await d.waitForTimeout(300); await shot(d, 'desktop-20-knihovna-nastroje');
  await d.click('.lib-i[data-add=shopping]'); await d.waitForTimeout(700);
  const wid = await d.locator('.wsp .w').last().getAttribute('data-wid'); await d.click(`[data-wid="${wid}"] [data-act=ws-config]`); await d.waitForTimeout(400); await d.click('[data-c-acc=blue]'); await d.click('[data-c-frame=strip]'); await d.waitForTimeout(300); await shot(d, 'desktop-21-vzhled-widgetu');
  await d.keyboard.press('Escape'); await d.click('[data-act=ws-done]'); await d.waitForTimeout(400);
  await d.evaluate((w) => document.querySelector(`[data-wid="${w}"]`).scrollIntoView({ block: 'center' }), wid); await d.waitForTimeout(300); await shot(d, 'desktop-22-osobni-widgety');
  await go(d, '#/prehled'); await top(d);
  await d.keyboard.press('q'); await d.waitForTimeout(500); await shot(d, 'desktop-23-rychly-zaznam');
  await d.click('.qa[data-v=feeding]'); await d.waitForTimeout(400); await shot(d, 'desktop-24-rychly-zaznam-komu');
  await d.locator('.qt').first().click(); await d.waitForTimeout(400); await shot(d, 'desktop-25-rychly-zaznam-ulozit');
  await d.keyboard.press('Escape'); await d.waitForTimeout(300);
  await d.keyboard.press('Control+k'); await d.waitForTimeout(300); await d.keyboard.type('pr'); await d.waitForTimeout(400); await shot(d, 'desktop-26-globalni-hledani');
  await d.keyboard.press('Escape'); await d.waitForTimeout(300);
  await d.click('[data-act=notifications]'); await d.waitForTimeout(500); await shot(d, 'desktop-27-oznameni');
  await d.keyboard.press('Escape'); await d.waitForTimeout(300);
  await d.click('[data-act=qr]'); await d.waitForTimeout(700); await shot(d, 'desktop-28-qr-skenovani');
  await d.keyboard.press('Escape'); await d.waitForTimeout(300);
  await d.click('[data-act=voice]'); await d.waitForTimeout(400); await d.click('.v-orb'); await d.waitForTimeout(350); await shot(d, 'desktop-29-hlas-posloucham');
  await d.keyboard.press('Escape'); await d.waitForTimeout(1500);
  await d.click('[data-act=profile]'); await d.waitForTimeout(300); await shot(d, 'desktop-30-profil-menu'); await d.keyboard.press('Escape');
  await go(d, '#/ukoly/planovac', 1200); await d.locator('.tl-it.st-overdue [data-act=tl-done]').first().click(); await d.waitForTimeout(140); await shot(d, 'desktop-31-dokonceni-pohyb');
  await d.waitForTimeout(700); await shot(d, 'desktop-32-toast-zapsano-zpet');
  const d2 = await mk(1440, 900, 2);
  await shot(d2, 'detail-hlavicka', { clip: { x: 256, y: 0, width: 1184, height: 72 } });
  await shot(d2, 'detail-zivy-pas', { clip: { x: 256, y: 72, width: 1184, height: 36 } });
  await d2.click('[data-act=live-next]'); await d2.waitForTimeout(500); await d2.click('[data-act=live-next]'); await d2.waitForTimeout(500); await d2.mouse.move(5, 890); await d2.waitForTimeout(200);
  await shot(d2, 'detail-zivy-pas-2', { clip: { x: 256, y: 72, width: 1184, height: 36 } });
  await shot(d2, 'detail-sidebar', { clip: { x: 0, y: 0, width: 256, height: 900 } });
  const m = await mk(390, 844, 2, true);
  await shot(m, 'mobile-01-prehled');
  await go(m, '#/zvirata/mrizka'); await shot(m, 'mobile-02-zvirata');
  await go(m, '#/zvirata/karta/a_fp01'); await shot(m, 'mobile-03-karta');
  await m.evaluate(() => (document.getElementById('view').scrollTop = 460)); await shot(m, 'mobile-03b-karta-akce');
  await go(m, '#/ukoly/dnes'); await shot(m, 'mobile-04-ukoly');
  await go(m, '#/ukoly/planovac', 1200); await shot(m, 'mobile-05-planovac');
  await go(m, '#/prehled'); await m.tap('.bn-plus'); await m.waitForTimeout(600); await shot(m, 'mobile-06-rychly-zaznam');
  await m.tap('.qa[data-v=feeding]'); await m.waitForTimeout(400); await shot(m, 'mobile-06b-rychly-zaznam-komu');
  await m.keyboard.press('Escape'); await m.waitForTimeout(400);
  await m.tap('[data-bn=more]'); await m.waitForTimeout(500); await m.locator('.more-i[data-more-i=reprodukce] [data-more-toggle]').tap(); await m.waitForTimeout(300); await shot(m, 'mobile-07-vice');
  await m.keyboard.press('Escape'); await m.waitForTimeout(300);
  await go(m, '#/reprodukce/prehled'); await m.evaluate(() => (document.getElementById('view').scrollTop = 300)); await shot(m, 'mobile-08-reprodukce');
  await go(m, '#/reprodukce/inkubace'); await shot(m, 'mobile-09-inkubace');
  await go(m, '#/sklad/prehled'); await shot(m, 'mobile-10-sklad');
  await go(m, '#/sklad/nakup'); await shot(m, 'mobile-11-nakupni-seznam');
  await go(m, '#/nastroje?n=calculator'); await shot(m, 'mobile-12-nastroje');
  await go(m, '#/prehled'); await m.tap('[data-act=notifications]'); await m.waitForTimeout(500); await shot(m, 'mobile-13-oznameni');
  await b.close();
})();
