<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';
$uid=ir_current_user_id();$animalId=ir_int($_GET['animal_id']??0);$type=trim((string)($_GET['type']??''));$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));$range=trim((string)($_GET['range']??''));
if($range==='today'){$from=$to=date('Y-m-d');}elseif($range==='week'){$from=date('Y-m-d',strtotime('-6 days'));$to=date('Y-m-d');}elseif($range==='month'){$from=date('Y-m-d',strtotime('-29 days'));$to=date('Y-m-d');}elseif($range==='year'){$from=date('Y-m-d',strtotime('-364 days'));$to=date('Y-m-d');}
$rows=ir_activity_rows($pdo,$uid,['animal_id'=>$animalId,'type'=>$type,'from'=>$from,'to'=>$to],800);$aq=$pdo->prepare('SELECT id,jmeno_kod,latinsky_nazev FROM wp_ir2_zvirata WHERE user_id=? ORDER BY jmeno_kod');$aq->execute([$uid]);$animals=$aq->fetchAll();$grouped=[];foreach($rows as $r){$day=date('Y-m-d',strtotime((string)$r['datum']));$grouped[$day][]=$r;}
ir_page_start('Historie aktivit','care');echo ir_back($animalId?'animal.php?id='.$animalId:'index.php','Zpět');
?>
<section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">ŽIVOTNÍ HISTORIE</span><h2>Kompletní historie aktivit</h2></div><a class="btn primary" href="quick.php">+ Rychlý záznam</a></header>
<div class="history-range-tabs"><a class="<?=($range==='today')?'active':''?>" href="?range=today<?=($animalId?'&animal_id='.$animalId:'')?>">Dnes</a><a class="<?=($range==='week')?'active':''?>" href="?range=week<?=($animalId?'&animal_id='.$animalId:'')?>">7 dní</a><a class="<?=($range==='month')?'active':''?>" href="?range=month<?=($animalId?'&animal_id='.$animalId:'')?>">30 dní</a><a class="<?=($range==='year')?'active':''?>" href="?range=year<?=($animalId?'&animal_id='.$animalId:'')?>">Rok</a><a class="<?=($range===''&&$from===''&&$to==='')?'active':''?>" href="?<?=($animalId?'animal_id='.$animalId:'')?>">Vše</a></div>
<form class="filter-bar" method="get"><select name="animal_id"><option value="">Všechna zvířata</option><?php foreach($animals as $a):?><option value="<?=$a['id']?>" <?=(int)$a['id']===$animalId?'selected':''?>><?=ir_e((string)$a['jmeno_kod'])?> · <?=ir_e((string)$a['latinsky_nazev'])?></option><?php endforeach;?></select><select name="type"><option value="">Všechny aktivity</option><?php foreach(array_keys(ir_activity_catalog_for_user($pdo,$uid)) as $t):?><option <?=$t===$type?'selected':''?>><?=ir_e($t)?></option><?php endforeach;?></select><input type="date" name="from" value="<?=ir_e($from)?>"><input type="date" name="to" value="<?=ir_e($to)?>"><button class="btn secondary">Filtrovat</button></form>
<div class="life-timeline"><?php foreach($grouped as $day=>$items):?><section class="timeline-day"><header><strong><?=($day===date('Y-m-d')?'Dnes':($day===date('Y-m-d',strtotime('-1 day'))?'Včera':date('d.m.Y',strtotime($day))))?></strong><span><?=count($items)?> záznamů</span></header><div class="timeline-day-items"><?php foreach($items as $r):?><a class="timeline-event" href="activity.php?id=<?=$r['id']?>"><span class="timeline-dot"><?=ir_visual_icon(ir_activity_icon_for_user($pdo,$uid,(string)$r['typ']))?></span><time><?=date('H:i',strtotime((string)$r['datum']))?></time><div class="timeline-event-copy"><strong><?=ir_e((string)$r['typ'])?></strong><span><?=ir_e((string)$r['jmeno_kod'])?><?php if(trim((string)$r['latinsky_nazev'])!==''):?> · <em><?=ir_e((string)$r['latinsky_nazev'])?></em><?php endif;?></span><small><?=ir_e(trim((string)($r['hodnota']??'').((string)($r['detail']??'')!==''?' · '.(string)$r['detail']:''),' ·'))?></small></div><b>Upravit →</b></a><?php endforeach;?></div></section><?php endforeach;if(!$grouped):?><div class="empty-state">V tomto období nejsou žádné záznamy.</div><?php endif;?></div>
</section><?php ir_page_end();
