<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';require_once __DIR__.'/includes/pedigree.php';
$uid=ir_current_user_id();$id=ir_int($_GET['id']??$_POST['id']??0);$clone=ir_int($_GET['clone']??0);$animal=$id?ir_animal($pdo,$uid,$id):($clone?ir_animal($pdo,$uid,$clone):null);$feedingTypes=ir_custom_feeding_types($pdo,$uid);$feedingTypeKey=$id?ir_animal_feeding_type_key($pdo,$uid,$id):($clone?ir_animal_feeding_type_key($pdo,$uid,$clone):'');
$textFields=['animal_id','jmeno_kod','druh','latinsky_nazev','poddruh','lokalita','pohlavi','datum_narozeni','kategorie','status_chovu','morf_linie','genetika','hetero_geni','cites_cislo','puvod','datum_porizeni','chovatel_puvod','rodokmen_info','zdravotni_historie','poznamka','prirozeny_vyskyt','biotop','aktivita','delka_doziti','teplota_den','teplota_noc','vyhrevne_misto','vlhkost','vlhkost_svlek','interval_roseni','fotoperioda','uvb','doporucena_ubikace','substrat','vybaveni_ubikace','interval_krmeni','potrava','vitaminova_rotace','pohlavni_dospelost_samec','pohlavni_dospelost_samice','min_vek_pareni_samec','min_vek_pareni_samice','min_vaha_pareni_samec','min_vaha_pareni_samice','optimalni_kondice','mesice_pareni','priprava_pareni','teplotni_cyklus_pareni','fotoperioda_pareni','vlhkost_pareni','obdobi_brumace','delka_brumace','teplota_brumace','priprava_brumace','ukonceni_brumace','reprodukcni_poznamky'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 ir_verify_csrf();$data=[];foreach($textFields as $f)$data[$f]=array_key_exists($f,$_POST)?trim((string)$_POST[$f]):($animal[$f]??null);$data['ubikace_id']=ir_int($_POST['ubikace_id']??0)?:null;$data['otec_id']=ir_int($_POST['otec_id']??0)?:null;$data['matka_id']=ir_int($_POST['matka_id']??0)?:null;$data['druh_id']=ir_int($_POST['druh_id']??0)?:null;$data['kupni_cena']=($_POST['kupni_cena']??'')!==''?max(0,(float)str_replace(',','.',(string)$_POST['kupni_cena'])):null;
$data['trzni_hodnota']=($_POST['trzni_hodnota']??'')!==''?max(0,(float)str_replace(',','.',(string)$_POST['trzni_hodnota'])):null;
$data['brumace_doporucena']=!empty($_POST['brumace_doporucena'])?1:0;$data['brumace_nutna']=!empty($_POST['brumace_nutna'])?1:0;$feedingTypeKey=trim((string)($_POST['feeding_type_key']??''));
 if($data['jmeno_kod']==='')$data['jmeno_kod']=$data['latinsky_nazev']!==''?$data['latinsky_nazev']:'Nové zvíře';if($data['druh']==='')$data['druh']=$data['latinsky_nazev']!==''?$data['latinsky_nazev']:'Neurčeno';
 try{
  if($id && !$animal)throw new RuntimeException('Zvíře nebylo nalezeno.');
  $data['datum_porizeni']=$data['datum_porizeni']?:null;
  if($data['datum_porizeni']!==null){$dt=DateTimeImmutable::createFromFormat('!Y-m-d',$data['datum_porizeni']);if(!$dt||$dt->format('Y-m-d')!==$data['datum_porizeni'])throw new RuntimeException('Zadej platné datum pořízení.');}
  foreach(['ubikace_id'=>'wp_ir2_ubikace','druh_id'=>'wp_ir2_druhy','otec_id'=>'wp_ir2_zvirata','matka_id'=>'wp_ir2_zvirata'] as $field=>$table){if($data[$field]){$check=$pdo->prepare("SELECT id FROM `$table` WHERE id=? AND user_id=?");$check->execute([$data[$field],$uid]);if(!$check->fetchColumn())throw new RuntimeException('Vybraný související záznam není dostupný.');}}
  if($id && ($data['otec_id']===$id||$data['matka_id']===$id))throw new RuntimeException('Zvíře nemůže být vlastním rodičem.');
  if($data['otec_id'] && $data['otec_id']===$data['matka_id'])throw new RuntimeException('Otec a matka musí být různí jedinci.');
  if($feedingTypeKey!==''&&!isset($feedingTypes[$feedingTypeKey]))throw new RuntimeException('Vyber platný typ krmení.');
  $pdo->beginTransaction();
  if($id){$sets=[];foreach(array_keys($data) as $c)$sets[]="`{$c}`=:{$c}";$data['user_id']=$uid;$data['id']=$id;$pdo->prepare('UPDATE wp_ir2_zvirata SET '.implode(',',$sets).',upraveno=NOW() WHERE user_id=:user_id AND id=:id')->execute($data);ir_save_animal_feeding_type($pdo,$uid,$id,$feedingTypeKey);ir_pedigree_sync_internal($pdo,$uid,$id);ir_resync_feed_task($pdo,$uid,$id);$pdo->commit();ir_flash('success','Uloženo. Karta byla upravena a plán krmení přepočítán.');ir_redirect('animal.php?id='.$id);
  }else{$cols=array_keys($data);$params=array_map(static fn($c)=>':'.$c,$cols);$data['user_id']=$uid;$pdo->prepare('INSERT INTO wp_ir2_zvirata(user_id,'.implode(',',$cols).') VALUES(:user_id,'.implode(',',$params).')')->execute($data);$new=(int)$pdo->lastInsertId();ir_save_animal_feeding_type($pdo,$uid,$new,$feedingTypeKey);ir_pedigree_sync_internal($pdo,$uid,$new);ir_resync_feed_task($pdo,$uid,$new);$pdo->commit();ir_flash('success','Uloženo. Karta byla vytvořena.');ir_redirect('animal.php?id='.$new);}
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('IR action: '.$e->getMessage());$error=$e instanceof PDOException?'Změnu se nepodařilo uložit. Zkus to znovu.':$e->getMessage();}
}
$ub=[];$parents=[];$species=[];try{$st=$pdo->prepare('SELECT id,nazev FROM wp_ir2_ubikace WHERE user_id=? ORDER BY nazev');$st->execute([$uid]);$ub=$st->fetchAll()?:[];$st=$pdo->prepare('SELECT id,jmeno_kod,latinsky_nazev,pohlavi FROM wp_ir2_zvirata WHERE user_id=? ORDER BY jmeno_kod');$st->execute([$uid]);$parents=$st->fetchAll()?:[];$st=$pdo->prepare('SELECT id,cesky_nazev,latinsky_nazev FROM wp_ir2_druhy WHERE user_id=? AND merged_into_id IS NULL ORDER BY latinsky_nazev');$st->execute([$uid]);$species=$st->fetchAll()?:[];}catch(Throwable){}
$a=isset($error)?array_merge($animal?:[],$data):($animal?:[]);ir_page_start($id?'Upravit kartu':'Nová karta','animals');echo ir_back($id?'animal.php?id='.$id:'animals.php','Zpět');if(!empty($error))echo '<div class="flash danger">'.ir_e($error).'</div>';
?>
<form class="animal-editor" method="post" enctype="multipart/form-data"><?=ir_csrf_field()?><input type="hidden" name="id" value="<?=$id?>">
<?php if($id): $editPhoto=ir_animal_photo($a); ?>
<section class="panel glow-panel animal-edit-media"><div class="animal-edit-media__photo"><?php if($editPhoto):?><img src="<?=ir_e($editPhoto)?>" alt=""><?php else:?><?=ir_visual_icon('animals')?><?php endif;?></div><div><span class="panel-kicker">MÉDIA & RODOKMEN</span><h2>Fotografie, vývoj a rodiče</h2><p>Fotografie a rodokmen včetně rodičů mimo chov.</p><div class="animal-edit-media__actions"><a class="btn primary" href="animal-media.php?id=<?=$id?>">Nahrát / spravovat fotografie</a><a class="btn secondary" href="pedigree.php?animal_id=<?=$id?>">Otevřít rodokmen</a><?php if(!empty($a['otec_id'])):?><a class="btn secondary" href="animal-media.php?id=<?=intval($a['otec_id'])?>">Foto otce</a><?php endif;?><?php if(!empty($a['matka_id'])):?><a class="btn secondary" href="animal-media.php?id=<?=intval($a['matka_id'])?>">Foto matky</a><?php endif;?></div></div></section>
<?php endif;?>
<section class="panel glow-panel form-panel"><header class="panel-head"><div><span class="panel-kicker">KARTA ZVÍŘETE</span><h2><?=$id?'Úprava karty':'Nové zvíře'?></h2></div><button class="btn primary">Uložit kartu</button></header>
<div class="form-grid cols-3">
<label>ID / kód<input name="animal_id" value="<?=ir_e((string)($a['animal_id']??''))?>"></label><label>Jméno / kód<input name="jmeno_kod" required value="<?=ir_e((string)($a['jmeno_kod']??''))?>"></label><label>Pohlaví<select name="pohlavi"><?php foreach(['Neurčeno','Samec','Samice','Skupina','Pár'] as $v):?><option <?=$v===($a['pohlavi']??'')?'selected':''?>><?=$v?></option><?php endforeach;?></select></label>
<label>Latinský název<input name="latinsky_nazev" value="<?=ir_e((string)($a['latinsky_nazev']??''))?>"></label><label>Český / pracovní název<input name="druh" value="<?=ir_e((string)($a['druh']??''))?>"></label><label>Druh z katalogu<select name="druh_id"><option value="">—</option><?php foreach($species as $s):?><option value="<?=$s['id']?>" <?=(int)($a['druh_id']??0)===(int)$s['id']?'selected':''?>><?=ir_e((string)$s['latinsky_nazev'])?></option><?php endforeach;?></select><small class="field-help">Prázdné individuální chovné údaje se na kartě doplní z katalogu druhu.</small></label>
<label>Datum narození<input name="datum_narozeni" placeholder="YYYY-MM" value="<?=ir_e((string)($a['datum_narozeni']??''))?>"></label><label>Vývojová kategorie<input name="kategorie" value="<?=ir_e((string)($a['kategorie']??'Adult'))?>"></label><label>Status<select name="status_chovu"><?php foreach(['Aktivní','Chov','Karanténa','Léčba','Rezervováno','Na prodej','Prodáno','Uhynulo','Archiv'] as $v):?><option <?=$v===($a['status_chovu']??'Aktivní')?'selected':''?>><?=$v?></option><?php endforeach;?></select></label>
<label>Ubikace<select name="ubikace_id"><option value="">Bez přiřazení</option><?php foreach($ub as $u):?><option value="<?=$u['id']?>" <?=(int)($a['ubikace_id']??0)===(int)$u['id']?'selected':''?>><?=ir_e((string)$u['nazev'])?></option><?php endforeach;?></select></label><label>Morf / linie<input name="morf_linie" value="<?=ir_e((string)($a['morf_linie']??''))?>"></label><label>Lokalita<input name="lokalita" value="<?=ir_e((string)($a['lokalita']??''))?>"></label>
<label>Otec<select name="otec_id"><option value="">—</option><?php foreach($parents as $p):if((int)$p['id']===$id)continue;?><option value="<?=$p['id']?>" <?=(int)($a['otec_id']??0)===(int)$p['id']?'selected':''?>><?=ir_e((string)$p['jmeno_kod'])?> · <?=ir_e((string)$p['latinsky_nazev'])?></option><?php endforeach;?></select></label><label>Matka<select name="matka_id"><option value="">—</option><?php foreach($parents as $p):if((int)$p['id']===$id)continue;?><option value="<?=$p['id']?>" <?=(int)($a['matka_id']??0)===(int)$p['id']?'selected':''?>><?=ir_e((string)$p['jmeno_kod'])?> · <?=ir_e((string)$p['latinsky_nazev'])?></option><?php endforeach;?></select></label><label>Poddruh<input name="poddruh" value="<?=ir_e((string)($a['poddruh']??''))?>"></label>
<label>Původ<input name="puvod" value="<?=ir_e((string)($a['puvod']??''))?>"></label><label>Chovatel / původ<input name="chovatel_puvod" value="<?=ir_e((string)($a['chovatel_puvod']??''))?>"></label><label>Datum pořízení<input type="date" name="datum_porizeni" value="<?=ir_e((string)($a['datum_porizeni']??''))?>"></label><label>Pořizovací cena (Kč)<input type="number" min="0" step="0.01" name="kupni_cena" value="<?=ir_e((string)($a['kupni_cena']??''))?>"></label><label>Aktuální odhad hodnoty (Kč)<input type="number" min="0" step="0.01" name="trzni_hodnota" value="<?=ir_e((string)($a['trzni_hodnota']??''))?>"></label><div></div>
<label>CITES / licence<input name="cites_cislo" value="<?=ir_e((string)($a['cites_cislo']??''))?>"></label><label class="span-2">Genetika<input name="genetika" value="<?=ir_e((string)($a['genetika']??''))?>"></label><label class="span-3">Rodokmen / původ<textarea name="rodokmen_info"><?=ir_e((string)($a['rodokmen_info']??''))?></textarea></label>
</div></section>

<section class="panel glow-panel form-panel"><header class="panel-head"><div><span class="panel-kicker">KRMENÍ A SUPLEMENTACE</span><h2>Automatický kolotoč krmení</h2></div><a href="supplements.php">Spravovat rotace</a></header><div class="form-grid cols-3">
<label>Interval krmení<input name="interval_krmeni" value="<?=ir_e((string)($a['interval_krmeni']??''))?>" placeholder="např. 7 dní"></label><label>Potrava<input name="potrava" value="<?=ir_e((string)($a['potrava']??''))?>"></label><label>Typ krmení<select name="feeding_type_key"><option value="">— bez výchozího typu —</option><?php foreach($feedingTypes as $key=>$meta):?><option value="<?=ir_e((string)$key)?>" <?=$feedingTypeKey===(string)$key?'selected':''?>><?=ir_e((string)$meta['label'])?></option><?php endforeach;?></select><small class="field-help">Rychlý záznam použije tento základ a automaticky připojí aktuální krok suplementační rotace.</small></label>
<label>Vitaminová rotace – poznámka<input name="vitaminova_rotace" value="<?=ir_e((string)($a['vitaminova_rotace']??''))?>"></label><label class="span-2">Poznámka ke krmení<input name="zdravotni_historie" value="<?=ir_e((string)($a['zdravotni_historie']??''))?>"></label>
</div></section>

<section class="panel glow-panel form-panel"><header class="panel-head"><div><span class="panel-kicker">PROSTŘEDÍ</span><h2>Chovné podmínky</h2></div></header><div class="form-grid cols-3">
<label>Denní teplota<input name="teplota_den" value="<?=ir_e((string)($a['teplota_den']??''))?>"></label><label>Noční teplota / pokles<input name="teplota_noc" value="<?=ir_e((string)($a['teplota_noc']??''))?>"></label><label>Výhřevné místo<input name="vyhrevne_misto" value="<?=ir_e((string)($a['vyhrevne_misto']??''))?>"></label>
<label>Vlhkost<input name="vlhkost" value="<?=ir_e((string)($a['vlhkost']??''))?>"></label><label>Vlhkost při svleku<input name="vlhkost_svlek" value="<?=ir_e((string)($a['vlhkost_svlek']??''))?>"></label><label>Rosení<input name="interval_roseni" value="<?=ir_e((string)($a['interval_roseni']??''))?>"></label>
<label>Fotoperioda<input name="fotoperioda" value="<?=ir_e((string)($a['fotoperioda']??''))?>"></label><label>UVB<input name="uvb" value="<?=ir_e((string)($a['uvb']??''))?>"></label><label>Aktivita<input name="aktivita" value="<?=ir_e((string)($a['aktivita']??''))?>"></label>
<label class="span-3">Doporučená ubikace<textarea name="doporucena_ubikace"><?=ir_e((string)($a['doporucena_ubikace']??''))?></textarea></label><label>Substrát<input name="substrat" value="<?=ir_e((string)($a['substrat']??''))?>"></label><label class="span-2">Vybavení ubikace<input name="vybaveni_ubikace" value="<?=ir_e((string)($a['vybaveni_ubikace']??''))?>"></label><label class="span-3">Biotop<textarea name="biotop"><?=ir_e((string)($a['biotop']??''))?></textarea></label>
</div></section>

<section class="panel glow-panel form-panel"><header class="panel-head"><div><span class="panel-kicker">CHOV A REPRODUKCE</span><h2>Páření, brumace a cykly</h2></div></header><div class="form-grid cols-3">
<label>Pohlavní dospělost ♂<input name="pohlavni_dospelost_samec" value="<?=ir_e((string)($a['pohlavni_dospelost_samec']??''))?>"></label><label>Pohlavní dospělost ♀<input name="pohlavni_dospelost_samice" value="<?=ir_e((string)($a['pohlavni_dospelost_samice']??''))?>"></label><label>Období páření<input name="mesice_pareni" value="<?=ir_e((string)($a['mesice_pareni']??''))?>"></label>
<label>Min. věk páření ♂<input name="min_vek_pareni_samec" value="<?=ir_e((string)($a['min_vek_pareni_samec']??''))?>"></label><label>Min. věk páření ♀<input name="min_vek_pareni_samice" value="<?=ir_e((string)($a['min_vek_pareni_samice']??''))?>"></label><label>Optimální kondice<input name="optimalni_kondice" value="<?=ir_e((string)($a['optimalni_kondice']??''))?>"></label>
<label>Min. hmotnost ♂<input name="min_vaha_pareni_samec" value="<?=ir_e((string)($a['min_vaha_pareni_samec']??''))?>"></label><label>Min. hmotnost ♀<input name="min_vaha_pareni_samice" value="<?=ir_e((string)($a['min_vaha_pareni_samice']??''))?>"></label><label>Vlhkost při páření<input name="vlhkost_pareni" value="<?=ir_e((string)($a['vlhkost_pareni']??''))?>"></label>
<label class="span-2">Teplotní cyklus páření<textarea name="teplotni_cyklus_pareni"><?=ir_e((string)($a['teplotni_cyklus_pareni']??''))?></textarea></label><label>Fotoperioda při páření<input name="fotoperioda_pareni" value="<?=ir_e((string)($a['fotoperioda_pareni']??''))?>"></label><label class="span-3">Příprava na páření<textarea name="priprava_pareni"><?=ir_e((string)($a['priprava_pareni']??''))?></textarea></label>
<label class="check-line"><input type="checkbox" name="brumace_doporucena" value="1" <?=!empty($a['brumace_doporucena'])?'checked':''?>><span>Brumace doporučená</span></label><label class="check-line"><input type="checkbox" name="brumace_nutna" value="1" <?=!empty($a['brumace_nutna'])?'checked':''?>><span>Brumace nutná</span></label><label>Období brumace<input name="obdobi_brumace" value="<?=ir_e((string)($a['obdobi_brumace']??''))?>"></label>
<label>Délka brumace<input name="delka_brumace" value="<?=ir_e((string)($a['delka_brumace']??''))?>"></label><label>Teplota brumace<input name="teplota_brumace" value="<?=ir_e((string)($a['teplota_brumace']??''))?>"></label><label>Očekávaná délka života<input name="delka_doziti" value="<?=ir_e((string)($a['delka_doziti']??''))?>"></label>
<label class="span-3">Příprava na brumaci<textarea name="priprava_brumace"><?=ir_e((string)($a['priprava_brumace']??''))?></textarea></label><label class="span-3">Ukončení brumace<textarea name="ukonceni_brumace"><?=ir_e((string)($a['ukonceni_brumace']??''))?></textarea></label><label class="span-3">Reprodukční poznámky<textarea name="reprodukcni_poznamky"><?=ir_e((string)($a['reprodukcni_poznamky']??''))?></textarea></label>
</div></section>
<section class="panel glow-panel form-panel"><header class="panel-head"><div><span class="panel-kicker">POZNÁMKY</span><h2>Další údaje</h2></div></header><div class="form-grid"><label>Přirozený výskyt<textarea name="prirozeny_vyskyt"><?=ir_e((string)($a['prirozeny_vyskyt']??''))?></textarea></label><label>Poznámka<textarea name="poznamka"><?=ir_e((string)($a['poznamka']??''))?></textarea></label></div></section>
</form>
<?php ir_page_end();
