<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';
$uid=ir_current_user_id();$id=ir_int($_GET['id']??$_POST['id']??0);$a=ir_animal($pdo,$uid,$id);if(!$a){http_response_code(404);exit('Zvíře nenalezeno.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 ir_verify_csrf();$action=(string)($_POST['action']??'upload');
 try{
  if($action==='upload' && isset($_FILES['photo'])){$path=ir_store_image_upload($_FILES['photo'],$uid,$id);$cat=(string)($_POST['category']??'galerie');$desc=trim((string)($_POST['description']??''));$pdo->prepare("INSERT INTO wp_ir2_zvire_fotky(user_id,zvire_id,kategorie,poradi,datum,popis,soubor) VALUES(?,?,?,0,CURDATE(),?,?)")->execute([$uid,$id,$cat,$desc,$path]);if(empty($a['foto']) || $cat==='profilová')$pdo->prepare("UPDATE wp_ir2_zvirata SET foto=?,upraveno=NOW() WHERE user_id=? AND id=?")->execute([$path,$uid,$id]);}
  elseif($action==='profile'){$pid=ir_int($_POST['photo_id']??0);$st=$pdo->prepare("SELECT soubor FROM wp_ir2_zvire_fotky WHERE user_id=? AND zvire_id=? AND id=?");$st->execute([$uid,$id,$pid]);$path=(string)$st->fetchColumn();if($path!=='')$pdo->prepare("UPDATE wp_ir2_zvirata SET foto=?,upraveno=NOW() WHERE user_id=? AND id=?")->execute([$path,$uid,$id]);}
  elseif($action==='delete'){$pid=ir_int($_POST['photo_id']??0);$st=$pdo->prepare("SELECT soubor FROM wp_ir2_zvire_fotky WHERE user_id=? AND zvire_id=? AND id=?");$st->execute([$uid,$id,$pid]);$path=(string)$st->fetchColumn();$pdo->prepare("DELETE FROM wp_ir2_zvire_fotky WHERE user_id=? AND zvire_id=? AND id=?")->execute([$uid,$id,$pid]);if($path!==''&&str_starts_with($path,'uploads/')){$full=IR_ROOT.'/'.$path;if(is_file($full))@unlink($full);}if((string)$a['foto']===$path)$pdo->prepare("UPDATE wp_ir2_zvirata SET foto=NULL WHERE user_id=? AND id=?")->execute([$uid,$id]);}
  ir_redirect('animal-media.php?id='.$id);
 }catch(Throwable $e){error_log('IR action: '.$e->getMessage());$error=$e instanceof PDOException?'Změnu se nepodařilo uložit. Zkus to znovu.':$e->getMessage();}
}
$photos=[];try{$st=$pdo->prepare("SELECT * FROM wp_ir2_zvire_fotky WHERE user_id=? AND zvire_id=? ORDER BY poradi,datum DESC,id DESC");$st->execute([$uid,$id]);$photos=$st->fetchAll()?:[];}catch(Throwable){}
ir_page_start('Fotografie','animals');echo ir_back('animal.php?id='.$id,'Zpět na kartu');if(!empty($error))echo '<div class="flash danger">'.ir_e($error).'</div>';
?>
<div class="two-column-layout"><section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">GALERIE</span><h2><?=ir_e(ir_animal_display($a))?></h2></div></header><div class="media-grid"><?php foreach($photos as $p):$url=ir_asset_photo_url((string)$p['soubor']);?><article><img src="<?=ir_e($url)?>" alt=""><strong><?=ir_e((string)$p['popis'])?></strong><small><?=ir_e((string)$p['kategorie'])?> · <?=ir_e((string)$p['datum'])?></small><div class="row-actions"><form method="post"><?=ir_csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="photo_id" value="<?=$p['id']?>"><button name="action" value="profile">Profilová</button><button class="danger" name="action" value="delete" onclick="return confirm('Smazat fotografii?')">Smazat</button></form></div></article><?php endforeach;if(!$photos):?><div class="empty-state">Bez fotografií.</div><?php endif;?></div></section><form class="panel glow-panel form-panel" method="post" enctype="multipart/form-data"><?=ir_csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="upload"><header class="panel-head"><div><span class="panel-kicker">UPLOAD</span><h2>Přidat fotografii</h2></div><button class="btn primary">Nahrát</button></header><div class="form-grid"><label>Soubor<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required></label><label>Kategorie<select name="category"><option value="profilová">profilová</option><option>galerie</option><option>vývoj</option><option>rodič</option><option>zdraví</option></select></label><label>Popis<input name="description"></label></div></form></div>
<?php ir_page_end();
