<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';
$uid=ir_current_user_id();ir_automation_ensure_table($pdo);
if($_SERVER['REQUEST_METHOD']==='POST'){
 ir_verify_csrf();$op=(string)($_POST['op']??'');
 try{
  if($op==='save'){$id=ir_int($_POST['id']??0);$title=trim((string)($_POST['title']??''));$trigger=trim((string)($_POST['trigger_type']??''));$delay=max(0,min(3650,(int)($_POST['delay_days']??0)));$task=trim((string)($_POST['task_title']??''));$cat=trim((string)($_POST['task_category']??'Péče'))?:'Péče';$enabled=!empty($_POST['enabled'])?1:0;if($title===''||$trigger===''||$task==='')throw new RuntimeException('Vyplň název, spouštěč a výsledný úkol.');if($id){$pdo->prepare('UPDATE wp_ir2_automation_rules SET title=?,trigger_type=?,delay_days=?,task_title=?,task_category=?,enabled=?,updated_at=NOW() WHERE user_id=? AND id=?')->execute([$title,$trigger,$delay,$task,$cat,$enabled,$uid,$id]);}else{$pdo->prepare('INSERT INTO wp_ir2_automation_rules(user_id,title,trigger_type,delay_days,task_title,task_category,enabled,source_module,trigger_text,action_text,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),NOW())')->execute([$uid,$title,$trigger,$delay,$task,$cat,$enabled,'planner',$trigger,$task]);}}
  elseif($op==='toggle'){$id=ir_int($_POST['id']??0);$pdo->prepare('UPDATE wp_ir2_automation_rules SET enabled=1-enabled,updated_at=NOW() WHERE user_id=? AND id=?')->execute([$uid,$id]);}
  elseif($op==='delete'){$id=ir_int($_POST['id']??0);$pdo->prepare('DELETE FROM wp_ir2_automation_rules WHERE user_id=? AND id=?')->execute([$uid,$id]);}
  ir_redirect('automation.php');
 }catch(Throwable $e){error_log('Automation: '.$e->getMessage());$error='Pravidlo se nepodařilo uložit. Zkontroluj údaje a databázovou migraci.';}
}
$rules=[];$edit=null;try{$st=$pdo->prepare('SELECT * FROM wp_ir2_automation_rules WHERE user_id=? ORDER BY enabled DESC,updated_at DESC,id DESC');$st->execute([$uid]);$rules=$st->fetchAll()?:[];$eid=ir_int($_GET['edit']??0);if($eid>0){$q=$pdo->prepare('SELECT * FROM wp_ir2_automation_rules WHERE user_id=? AND id=? LIMIT 1');$q->execute([$uid,$eid]);$edit=$q->fetch()?:null;if(!$edit)ir_flash('danger','Automatizace nebyla nalezena.');}}catch(Throwable $e){error_log('IR automation edit: '.$e->getMessage());}
$catalog=ir_activity_catalog_for_user($pdo,$uid);
ir_page_start('Automatizace','tasks');echo ir_back('tasks.php','Plánovač');if(!empty($error))echo '<div class="flash danger">'.ir_e($error).'</div>';
?>
<div class="module-toolbar"><div><span class="panel-kicker">PLANNER CORE</span><h1>Automatizace</h1><p>Strukturovaná pravidla propojují skutečné aktivity s Plánovačem. Pravidlo se vykoná po uložení aktivity, ne jen v prohlížeči.</p></div><a class="btn secondary" href="tasks.php">Plánovač</a></div>
<div class="automation-grid"><section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">PRAVIDLA</span><h2>Aktivní návaznosti</h2></div></header><div class="automation-list"><?php foreach($rules as $r):?><article class="automation-rule <?=$r['enabled']?'':'is-disabled'?>"><span class="automation-rule-icon"><?=ir_visual_icon(ir_activity_icon_for_user($pdo,$uid,(string)($r['trigger_type']??$r['trigger_text']??'')))?></span><div><strong><?=ir_e((string)$r['title'])?></strong><small>Po „<?=ir_e((string)($r['trigger_type']??$r['trigger_text']??''))?>“ → za <?=ir_int(($r['delay_days']??0))?> dní vytvořit „<?=ir_e((string)($r['task_title']??$r['action_text']??''))?>“</small></div><form method="post"><?=ir_csrf_field()?><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn tiny" name="op" value="toggle"><?=$r['enabled']?'Aktivní':'Pozastaveno'?></button></form><a class="btn tiny" href="automation.php?edit=<?=$r['id']?>#automation-editor">Upravit</a><form method="post" onsubmit="return confirm('Smazat pravidlo?')"><?=ir_csrf_field()?><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn tiny danger" name="op" value="delete">×</button></form></article><?php endforeach;if(!$rules):?><div class="empty-state small">Zatím žádná vlastní pravidla. Vestavěné návaznosti krmení, suplementace a reprodukce zůstávají aktivní.</div><?php endif;?></div></section>
<form id="automation-editor" class="panel glow-panel form-panel" method="post"><?=ir_csrf_field()?><input type="hidden" name="op" value="save"><input type="hidden" name="id" value="<?=ir_int($edit['id']??0)?>"><header class="panel-head"><div><span class="panel-kicker">RULE BUILDER</span><h2><?=$edit?'Upravit pravidlo':'Nové pravidlo'?></h2></div><button class="btn primary">Uložit</button></header><div class="form-grid"><label>Název<input name="title" required value="<?=ir_e((string)($edit['title']??''))?>" placeholder="Krmení → kontrola kondice"></label><label>Po aktivitě<select name="trigger_type" required><?php foreach($catalog as $name=>$meta):?><option value="<?=ir_e($name)?>" <?=($edit['trigger_type']??'')===$name?'selected':''?>><?=ir_e($name)?></option><?php endforeach;?></select></label><label>Za kolik dní<input type="number" min="0" max="3650" name="delay_days" value="<?=ir_int($edit['delay_days']??0)?>"></label><label>Vytvořit úkol<input name="task_title" required value="<?=ir_e((string)($edit['task_title']??''))?>" placeholder="Kontrola kondice"></label><label>Kategorie<select name="task_category"><?php foreach(['Péče','Krmení','Zdraví','Reprodukce','Údržba','Kontrola'] as $c):?><option <?=($edit['task_category']??'')===$c?'selected':''?>><?=$c?></option><?php endforeach;?></select></label><label class="check-row"><input type="checkbox" name="enabled" value="1" <?=!isset($edit['enabled'])||$edit['enabled']?'checked':''?>> Aktivní</label></div><?php if($edit):?><a class="btn secondary" href="automation.php">Zrušit úpravu</a><?php endif;?></form></div>
<?php if($edit):?><script>addEventListener('DOMContentLoaded',()=>document.getElementById('automation-editor')?.scrollIntoView({behavior:'smooth',block:'start'}));</script><?php endif;?>
<?php ir_page_end();
