<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';
$uid=ir_current_user_id();
if($_SERVER['REQUEST_METHOD']==='POST'){
 ir_verify_csrf();
 try{
  $count=max(1,min(100,(int)($_POST['count']??1)));$prefix=trim((string)($_POST['prefix']??'Odchov'));$druh=trim((string)($_POST['druh']??''));$latin=trim((string)($_POST['latinsky_nazev']??''));$sex=trim((string)($_POST['pohlavi']??'Neurčeno'));$birth=trim((string)($_POST['datum_narozeni']??date('Y-m')));$status=trim((string)($_POST['status_chovu']??'Odchov'));$morph=trim((string)($_POST['morf_linie']??''));$father=ir_int($_POST['otec_id']??0)?:null;$mother=ir_int($_POST['matka_id']??0)?:null;$ub=ir_int($_POST['ubikace_id']??0)?:null;
  if($latin===''&&$druh==='')throw new RuntimeException('Vyplň druh nebo latinský název.');
  $pdo->beginTransaction();for($i=1;$i<=$count;$i++){$name=$prefix.' '.str_pad((string)$i,2,'0',STR_PAD_LEFT);$pdo->prepare("INSERT INTO wp_ir2_zvirata(user_id,jmeno_kod,druh,latinsky_nazev,pohlavi,datum_narozeni,kategorie,status_chovu,morf_linie,otec_id,matka_id,ubikace_id,vytvoreno,upraveno) VALUES(?,?,?,?,?,?,'Juvenile',?,?,?,?,?,NOW(),NOW())")->execute([$uid,$name,$druh!==''?$druh:$latin,$latin!==''?$latin:null,$sex,$birth,$status,$morph!==''?$morph:null,$father,$mother,$ub]);}$pdo->commit();ir_flash('success','Vytvořeno '.$count.' karet.');ir_redirect('animals.php');
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('IR action: '.$e->getMessage());$error=$e instanceof PDOException?'Změnu se nepodařilo uložit. Zkus to znovu.':$e->getMessage();}
}
$animals=[];$cages=[];try{$st=$pdo->prepare('SELECT id,jmeno_kod,latinsky_nazev FROM wp_ir2_zvirata WHERE user_id=? ORDER BY jmeno_kod');$st->execute([$uid]);$animals=$st->fetchAll()?:[];$st=$pdo->prepare('SELECT id,nazev FROM wp_ir2_ubikace WHERE user_id=? ORDER BY nazev');$st->execute([$uid]);$cages=$st->fetchAll()?:[];}catch(Throwable){}
ir_page_start('Hromadné vytvoření','animals');echo ir_back('animals.php','Zpět na zvířata');if(!empty($error))echo '<div class="flash danger">'.ir_e($error).'</div>';
?>
<form class="panel glow-panel form-panel" method="post"><?=ir_csrf_field()?><header class="panel-head"><div><span class="panel-kicker">BATCH CREATE</span><h2>Hromadně vytvořit karty</h2></div><button class="btn primary">Vytvořit</button></header><div class="form-grid cols-3"><label>Počet<input type="number" name="count" min="1" max="100" value="10" required></label><label>Prefix jména / ID<input name="prefix" value="Odchov"></label><label>Pohlaví<select name="pohlavi"><option>Neurčeno</option><option>Samec</option><option>Samice</option></select></label><label>Latinský název<input name="latinsky_nazev"></label><label>Druh<input name="druh"></label><label>Datum narození<input name="datum_narozeni" value="<?=date('Y-m')?>"></label><label>Status<select name="status_chovu"><option>Odchov</option><option>Aktivní</option><option>Chov</option></select></label><label>Morf / linie<input name="morf_linie"></label><label>Ubikace<select name="ubikace_id"><option value="">—</option><?php foreach($cages as $c):?><option value="<?=$c['id']?>"><?=ir_e((string)$c['nazev'])?></option><?php endforeach;?></select></label><label>Otec<select name="otec_id"><option value="">—</option><?php foreach($animals as $a):?><option value="<?=$a['id']?>"><?=ir_e((string)$a['jmeno_kod'])?></option><?php endforeach;?></select></label><label>Matka<select name="matka_id"><option value="">—</option><?php foreach($animals as $a):?><option value="<?=$a['id']?>"><?=ir_e((string)$a['jmeno_kod'])?></option><?php endforeach;?></select></label></div></form>
<?php ir_page_end();
