<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';
$uid=ir_current_user_id();$id=ir_int($_GET['id']??$_POST['id']??0);$animalFilter=ir_int($_GET['animal_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
 ir_verify_csrf();$action=(string)($_POST['action']??'');
 try{
  if($action==='save'){
   $name=trim((string)($_POST['nazev']??''));if($name==='')throw new RuntimeException('Chybí název cyklu / snůšky.');$mother=ir_int($_POST['matka_id']??0)?:null;$father=ir_int($_POST['otec_id']??0)?:null;$speciesId=null;foreach([$mother,$father] as $parentId)if($parentId&&!ir_animal($pdo,$uid,(int)$parentId))throw new RuntimeException('Rodič nebyl nalezen.');foreach([$mother,$father] as $pid){if($pid){$pa=ir_animal($pdo,$uid,(int)$pid);if($pa&&!empty($pa['druh_id'])){$speciesId=(int)$pa['druh_id'];break;}}}
   $state=trim((string)($_POST['stav']??'Aktivní'))?:'Aktivní';$phase=trim((string)($_POST['aktualni_faze']??''));if($phase==='')$phase=$state==='Inkubace'?'Inkubace':'Příprava';$nextAction=trim((string)($_POST['dalsi_akce']??''));if($nextAction==='')$nextAction=ir_repro_next_action_for_phase($phase);$nextDate=trim((string)($_POST['dalsi_akce_datum']??''))?:null;
   $vals=['druh_id'=>$speciesId,'matka_id'=>$mother,'otec_id'=>$father,'nazev'=>$name,'datum_zahajeni'=>trim((string)($_POST['datum_zahajeni']??''))?:null,'datum_pareni'=>trim((string)($_POST['datum_pareni']??''))?:null,'datum_ovulace'=>trim((string)($_POST['datum_ovulace']??''))?:null,'datum_pos'=>trim((string)($_POST['datum_pos']??''))?:null,'datum_snusky'=>trim((string)($_POST['datum_snusky']??''))?:null,'pocet_celkem'=>ir_int($_POST['pocet_celkem']??0),'pocet_fertilnich'=>ir_int($_POST['pocet_fertilnich']??0),'pocet_infertilnich'=>ir_int($_POST['pocet_infertilnich']??0),'predpoklad_lihnuti'=>trim((string)($_POST['predpoklad_lihnuti']??''))?:null,'stav'=>$state,'aktualni_faze'=>$phase,'dalsi_akce'=>$nextAction,'dalsi_akce_datum'=>$nextDate,'poznamka'=>trim((string)($_POST['poznamka']??''))];$vals=ir_repro_autofill($pdo,$uid,$vals);
   if($vals['pocet_fertilnich']+$vals['pocet_infertilnich']>$vals['pocet_celkem'])throw new RuntimeException('Fertilní + infertilní nesmí být více než celkový počet.');
   if($id){$sets=[];foreach(array_keys($vals) as $c)$sets[]="`{$c}`=:{$c}";$vals['uid']=$uid;$vals['id']=$id;$pdo->prepare('UPDATE wp_ir2_snusky SET '.implode(',',$sets).' WHERE user_id=:uid AND id=:id')->execute($vals);}else{$cols=array_keys($vals);$params=array_map(static fn($c)=>':'.$c,$cols);$vals['uid']=$uid;$pdo->prepare('INSERT INTO wp_ir2_snusky(user_id,'.implode(',',$cols).') VALUES(:uid,'.implode(',',$params).')')->execute($vals);$id=(int)$pdo->lastInsertId();}
   ir_sync_repro_task($pdo,$uid,$id);ir_flash('success','Reprodukční cyklus byl uložen a synchronizován s Plánovačem.');ir_redirect('clutches.php?id='.$id);
  }
  if($action==='hatch'&&$id){$pdo->beginTransaction();$st=$pdo->prepare('SELECT * FROM wp_ir2_snusky WHERE user_id=? AND id=? FOR UPDATE');$st->execute([$uid,$id]);$c=$st->fetch();if(!$c)throw new RuntimeException('Snůška nenalezena.');if((int)($c['pocet_mladat']??0)>0||$c['stav']==='Ukončeno')throw new RuntimeException('Tato snůška už byla dokončena.');$count=max(1,ir_int($_POST['hatch_count']??$c['pocet_fertilnich']??1));if($count>max(1,(int)$c['pocet_celkem']))throw new RuntimeException('Počet mláďat překračuje počet vajec.');$parent=$c['matka_id']?ir_animal($pdo,$uid,(int)$c['matka_id']):($c['otec_id']?ir_animal($pdo,$uid,(int)$c['otec_id']):null);for($i=1;$i<=$count;$i++){$pdo->prepare("INSERT INTO wp_ir2_zvirata(user_id,druh_id,animal_id,jmeno_kod,druh,latinsky_nazev,pohlavi,datum_narozeni,kategorie,status_chovu,morf_linie,otec_id,matka_id,vytvoreno,upraveno) VALUES(?,?,?,?,?,?,'Neurčeno',?,'Juvenile','Odchov',?,?,?,NOW(),NOW())")->execute([$uid,$parent['druh_id']??null,null,$c['nazev'].' #'.$i,$parent['druh']??'Odchov',$parent['latinsky_nazev']??null,substr((string)($c['datum_lihnuti']?:date('Y-m-d')),0,7),$parent['morf_linie']??null,$c['otec_id']?:null,$c['matka_id']?:null]);}
   $pdo->prepare("UPDATE wp_ir2_snusky SET datum_lihnuti=COALESCE(datum_lihnuti,CURDATE()),pocet_mladat=?,stav='Ukončeno',aktualni_faze='Líhnutí',dalsi_akce='Hotovo',dalsi_akce_datum=NULL,datum_ukonceni=CURDATE() WHERE user_id=? AND id=?")->execute([$count,$uid,$id]);ir_sync_repro_task($pdo,$uid,$id);$pdo->commit();ir_flash('success','Vytvořeno '.$count.' mláďat a cyklus byl ukončen.');ir_redirect('clutches.php?id='.$id);
  }
  if($action==='advance'&&$id){$pdo->beginTransaction();$result=ir_repro_advance_cycle($pdo,$uid,$id);$pdo->commit();ir_flash('success','Cyklus posunut do fáze: '.(string)$result['phase'].'.');$returnTo=(string)($_POST['return_to']??'');if(!preg_match('~^(?:index|clutches)\.php(?:[?#].*)?$~',$returnTo))$returnTo='clutches.php?id='.$id;ir_redirect($returnTo);}
  if($action==='delete'&&$id){$q=$pdo->prepare('SELECT stav FROM wp_ir2_snusky WHERE user_id=? AND id=?');$q->execute([$uid,$id]);if($q->fetchColumn()===false)throw new RuntimeException('Cyklus nebyl nalezen.');$pdo->prepare("UPDATE wp_ir2_planovac SET stav='Zrušeno' WHERE user_id=? AND poznamka LIKE ? AND stav='Aktivní'")->execute([$uid,'[IR-REPRO:'.$id.']%']);$pdo->prepare('DELETE FROM wp_ir2_snusky WHERE user_id=? AND id=?')->execute([$uid,$id]);ir_flash('success','Reprodukční cyklus byl smazán.');ir_redirect('clutches.php');}
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Reproduction: '.$e->getMessage());$error=$e instanceof PDOException?'Změnu se nepodařilo uložit. Zkus to znovu.':$e->getMessage();}
}
$animals=[];$clutches=[];$current=null;try{$st=$pdo->prepare('SELECT id,jmeno_kod,latinsky_nazev,pohlavi FROM wp_ir2_zvirata WHERE user_id=? ORDER BY jmeno_kod');$st->execute([$uid]);$animals=$st->fetchAll()?:[];$sql="SELECT c.*,m.jmeno_kod matka_name,o.jmeno_kod otec_name FROM wp_ir2_snusky c LEFT JOIN wp_ir2_zvirata m ON m.id=c.matka_id AND m.user_id=c.user_id LEFT JOIN wp_ir2_zvirata o ON o.id=c.otec_id AND o.user_id=c.user_id WHERE c.user_id=?";$params=[$uid];if($animalFilter){$sql.=' AND (c.matka_id=? OR c.otec_id=?)';$params[]=$animalFilter;$params[]=$animalFilter;}$sql.=' ORDER BY (c.stav=\'Aktivní\') DESC,COALESCE(c.dalsi_akce_datum,c.predpoklad_lihnuti,c.datum_snusky,c.datum_zahajeni,c.vytvoreno) DESC';$st=$pdo->prepare($sql);$st->execute($params);$clutches=$st->fetchAll()?:[];if($id)foreach($clutches as $c)if((int)$c['id']===$id){$current=$c;break;}}catch(Throwable){}
ir_page_start('Reprodukční cykly','reproduction');if(!empty($error))echo '<div class="flash danger">'.ir_e($error).'</div>';
?>
<?php
$activeCycles=array_values(array_filter($clutches,static fn($c)=>(string)$c['stav']==='Aktivní'&&mb_strtolower((string)($c['aktualni_faze']??''),'UTF-8')!=='inkubace'));
$incubations=array_values(array_filter($clutches,static fn($c)=>(string)$c['stav']==='Inkubace'||mb_strtolower((string)$c['aktualni_faze'])==='inkubace'));
$closedCycles=array_values(array_filter($clutches,static fn($c)=>!in_array((string)$c['stav'],['Aktivní','Inkubace'],true)));
$renderCycle=static function(array $c) use($pdo,$uid): void {
 $phase=(string)($c['aktualni_faze']?:$c['stav']);$isInc=(string)$c['stav']==='Inkubace'||mb_strtolower($phase,'UTF-8')==='inkubace';
 $window=ir_repro_phase_window($pdo,$uid,(int)($c['druh_id']??0),$phase);$from=(int)($window['from']??0);$to=(int)($window['to']??0);
 $start=(string)($c['datum_snusky']?:$c['datum_zahajeni']?:'');$elapsed=$start&&strtotime($start)?max(0,(int)floor((time()-strtotime($start))/86400)):0;
 if($isInc&&$to<=0&&$start&&!empty($c['predpoklad_lihnuti'])&&strtotime((string)$c['predpoklad_lihnuti'])>strtotime($start)){$to=max(1,(int)round((strtotime((string)$c['predpoklad_lihnuti'])-strtotime($start))/86400));$from=$to;}
 $range=$from>0?($to>$from?$from.'–'.$to.' dní':$from.' dní'):''; ?>
<article class="repro-cycle-card <?=$isInc?'is-incubation':''?>">
 <a class="repro-cycle-main" href="clutches.php?id=<?=$c['id']?>"><span class="repro-cycle-icon"><?=ir_visual_icon($isInc?'calendar':'reproduction')?></span><span><strong><?=ir_e((string)$c['nazev'])?></strong><small><?=ir_e((string)($c['matka_name']??'—'))?> × <?=ir_e((string)($c['otec_name']??'—'))?></small></span><b><?=ir_e($phase)?></b></a>
 <?php if($isInc):
   if($from<=0)$from=max(1,$to);if($to<$from)$to=$from;
   $p1=max(0,min(100,($elapsed/max(1,$from))*100));$p2=$elapsed<=$from?0:max(0,min(100,(($elapsed-$from)/max(1,$to-$from))*100));
   if($to>0&&$elapsed>$to){$status='+'.($elapsed-$to).' dní nad horní hranicí · zkontrolovat vejce';$cls=' is-overdue';}
   elseif($elapsed>=$from&&$to>$from){$status='OKNO LÍHNUTÍ · den '.($elapsed-$from+1).' z '.($to-$from+1).' · do horní hranice '.max(0,$to-$elapsed).' dní';$cls=' is-window';}
   else{$status='Do začátku okna '.max(0,$from-$elapsed).' dní';$cls='';}
 ?>
 <div class="repro-incubation-progress<?=$cls?>">
   <div class="repro-incubation-head"><strong>Den <?=$elapsed?><?php if($to>0):?> / <?=$to?><?php endif;?></strong><span><?=ir_e($range?:'Rozsah není nastaven')?></span></div>
   <div class="incubation-dual-progress"><div class="incubation-stage incubation-stage-primary"><span><b style="width:<?=number_format($p1,2,'.','')?>%"></b></span><small>0–<?=$from?>. den · <?=round($p1)?>%</small></div><div class="incubation-stage incubation-stage-window"><span><b style="width:<?=number_format($p2,2,'.','')?>%"></b></span><small><?=$from?>–<?=$to?>. den · okno líhnutí</small></div></div>
   <em><?=ir_e($status)?></em>
 </div>
 <?php else:
   $plan=ir_repro_phase_plan($pdo,$uid,(int)($c['druh_id']??0));$phaseTotal=max(1,count($plan));$phaseIndex=0;foreach($plan as $i=>$pp)if(mb_strtolower(trim((string)($pp['faze']??'')),'UTF-8')===mb_strtolower(trim($phase),'UTF-8')){$phaseIndex=$i+1;break;}
 ?>
 <div class="repro-phase-progress"><div class="cycle-progress is-segmented"><?php for($si=1;$si<=$phaseTotal;$si++):?><b class="cycle-segment <?=$si<$phaseIndex?'is-done':($si===$phaseIndex?'is-current':'')?>"></b><?php endfor;?></div><small>Fáze <?=max(1,$phaseIndex)?> / <?=$phaseTotal?> · <?=ir_e($phase)?></small></div>
 <?php endif;?>
 <div class="repro-cycle-meta"><?php if($range!==''&&!$isInc):?><span><?=ir_visual_icon('clock')?><?=ir_e($range)?></span><?php endif;?><?php if($c['dalsi_akce_datum']):?><span><?=ir_visual_icon('calendar')?><?=date('d.m.Y',strtotime((string)$c['dalsi_akce_datum']))?></span><?php endif;?></div>
 <div class="repro-cycle-actions"><a class="btn tiny" href="clutches.php?id=<?=$c['id']?>"><?=$isInc?'Detail inkubace':'Upravit'?></a><?php if(!$isInc&&!in_array((string)$c['stav'],['Ukončeno'],true)):?><form method="post"><?=ir_csrf_field()?><input type="hidden" name="id" value="<?=$c['id']?>"><button class="btn tiny primary" name="action" value="advance" onclick="return confirm('Potvrdit dokončení aktuální fáze a přejít na další?')">Potvrdit další fázi</button></form><?php endif;?><form method="post"><?=ir_csrf_field()?><input type="hidden" name="id" value="<?=$c['id']?>"><button class="btn tiny danger" name="action" value="delete" onclick="return confirm('Smazat tento reprodukční cyklus?')">Smazat</button></form></div>
</article><?php };
?>
<div class="two-column-layout repro-overview"><section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">REPRODUKCE</span><h2>Přehled cyklů</h2></div><a href="tasks.php">Plánovač</a></header>
<div class="repro-category"><header><span><?=ir_visual_icon('reproduction')?></span><div><strong>Probíhající cykly</strong><small><?=count($activeCycles)?> aktivní</small></div></header><?php foreach($activeCycles as $c)$renderCycle($c);if(!$activeCycles):?><p class="empty-state small">Žádný aktivní cyklus.</p><?php endif;?></div>
<div class="repro-category"><header><span><?=ir_visual_icon('calendar')?></span><div><strong>Inkubace</strong><small><?=count($incubations)?> probíhá</small></div></header><?php foreach($incubations as $c)$renderCycle($c);if(!$incubations):?><p class="empty-state small">Žádná probíhající inkubace.</p><?php endif;?></div>
<details class="repro-archive"><summary>Historie / plánování (<?=count($closedCycles)?>)</summary><?php foreach($closedCycles as $c)$renderCycle($c);?></details></section>
<section class="panel glow-panel form-panel"><header class="panel-head"><div><span class="panel-kicker">CYKLUS</span><h2><?=$current?'Detail / editace':'Nový reprodukční cyklus'?></h2></div><?php if($current):?><a href="print.php?type=clutch&id=<?=$current['id']?>" target="_blank">Štítek / QR</a><?php endif;?></header><form method="post"><?=ir_csrf_field()?><input type="hidden" name="id" value="<?=ir_int($current['id']??0)?>"><div class="form-grid cols-2">
<label>Název<input name="nazev" required value="<?=ir_e((string)($current['nazev']??''))?>"></label><label>Stav<select name="stav"><?php foreach(['Plánování','Aktivní','Inkubace','Ukončeno'] as $v):?><option <?=$v===($current['stav']??'Aktivní')?'selected':''?>><?=$v?></option><?php endforeach;?></select></label>
<label>Matka<select name="matka_id"><option value="">—</option><?php foreach($animals as $a):?><option value="<?=$a['id']?>" <?=(int)($current['matka_id']??0)===(int)$a['id']?'selected':''?>><?=ir_e((string)$a['jmeno_kod'])?> · <?=ir_e((string)$a['latinsky_nazev'])?></option><?php endforeach;?></select></label><label>Otec<select name="otec_id"><option value="">—</option><?php foreach($animals as $a):?><option value="<?=$a['id']?>" <?=(int)($current['otec_id']??0)===(int)$a['id']?'selected':''?>><?=ir_e((string)$a['jmeno_kod'])?> · <?=ir_e((string)$a['latinsky_nazev'])?></option><?php endforeach;?></select></label>
<label>Zahájení<input type="date" name="datum_zahajeni" value="<?=ir_e((string)($current['datum_zahajeni']??''))?>"></label><label>Aktuální fáze<select name="aktualni_faze"><?php foreach(['Příprava','Cyklování','Spojení páru','Páření','Ovulace','Předsnůškový svlek','Snůška','Inkubace','Líhnutí','Ukončení'] as $v):?><option <?=$v===($current['aktualni_faze']??'Příprava')?'selected':''?>><?=$v?></option><?php endforeach;?></select></label>
<label>Datum páření<input type="date" name="datum_pareni" value="<?=ir_e((string)($current['datum_pareni']??''))?>"></label><label>Ovulace<input type="date" name="datum_ovulace" value="<?=ir_e((string)($current['datum_ovulace']??''))?>"></label><label>Předsnůškový svlek<input type="date" name="datum_pos" value="<?=ir_e((string)($current['datum_pos']??''))?>"></label><label>Datum snůšky<input type="date" name="datum_snusky" value="<?=ir_e((string)($current['datum_snusky']??''))?>"></label>
<label>Počet celkem<input type="number" min="0" name="pocet_celkem" value="<?=ir_int($current['pocet_celkem']??0)?>"></label><label>Fertilní<input type="number" min="0" name="pocet_fertilnich" value="<?=ir_int($current['pocet_fertilnich']??0)?>"></label><label>Infertilní<input type="number" min="0" name="pocet_infertilnich" value="<?=ir_int($current['pocet_infertilnich']??0)?>"></label><label>Předpoklad líhnutí<input type="date" name="predpoklad_lihnuti" value="<?=ir_e((string)($current['predpoklad_lihnuti']??''))?>"></label>
<label>Další akce<input name="dalsi_akce" value="<?=ir_e((string)($current['dalsi_akce']??''))?>" placeholder="prázdné = podle fáze"></label><label>Termín další akce<input type="date" name="dalsi_akce_datum" value="<?=ir_e((string)($current['dalsi_akce_datum']??''))?>"><small class="field-help">Nech prázdné: hlavní mozek dopočítá další termín podle fáze a dostupných druhových dat a propíše jej do Plánovače.</small></label><label class="span-2">Poznámka<input name="poznamka" value="<?=ir_e((string)($current['poznamka']??''))?>"></label>
</div><button class="btn primary" name="action" value="save">Uložit a synchronizovat</button></form><?php if($current&&$current['stav']!=='Ukončeno'):?><form class="hatch-form" method="post"><?=ir_csrf_field()?><input type="hidden" name="id" value="<?=$current['id']?>"><label>Počet vylíhlých<input type="number" min="1" name="hatch_count" value="<?=max(1,(int)$current['pocet_fertilnich'])?>"></label><button class="btn secondary" name="action" value="hatch" onclick="return confirm('Vytvořit mláďata jako nové karty zvířat?')">Vylíhnout → vytvořit mláďata</button></form><?php endif;?></section></div>
<?php ir_page_end();
