<?php declare(strict_types=1);require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require_once __DIR__.'/includes/events_catalog.php';$uid=ir_current_user_id();$ok=ir_table_exists($pdo,'wp_ir2_events');$error='';
$seriesReady=ir_table_exists($pdo,'wp_ir2_event_series')&&ir_db_column_exists($pdo,'wp_ir2_events','series_id');
if($ok&&$_SERVER['REQUEST_METHOD']==='POST'){ir_verify_csrf();try{
 $title=trim((string)($_POST['title']??''));$sid=(int)($_POST['series_id']??0);$action=$_POST['action']??'date';
 if($action==='series'&&$seriesReady){
  if($title===''||mb_strlen($title)>190)throw new InvalidArgumentException('Vyplň název akce.');
  $fields=[];foreach(['organizer','place','city','country','website','source','description','event_type'] as $f)$fields[]=trim((string)($_POST[$f]??''));
  if($fields[4]!==''&&!preg_match('~^https?://~i',$fields[4]))throw new InvalidArgumentException('Web musí začínat http:// nebo https://.');
  $pdo->prepare('INSERT INTO wp_ir2_event_series(user_id,name,organizer,place,city,country,website,source,description,event_type) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$uid,$title,...$fields]);ir_redirect('events.php');
 }
 $date=(string)($_POST['starts_at']??'');$dt=DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',$date);if(!$dt||$dt->format('Y-m-d\TH:i')!==$date)throw new InvalidArgumentException('Vyplň platné datum a čas.');
 if($sid&&$seriesReady){$q=$pdo->prepare('SELECT * FROM wp_ir2_event_series WHERE user_id=? AND id=?');$q->execute([$uid,$sid]);$series=$q->fetch();if(!$series)throw new InvalidArgumentException('Akce nebyla nalezena.');$title=$series['name'];$city=$series['city'];$country=$series['country'];$address=$series['place'];$website=$series['website'];$notes=$series['description'];$type=$series['event_type'];}
 else{$city=trim((string)($_POST['city']??''));$country=trim((string)($_POST['country']??''));$address=trim((string)($_POST['address']??''));$website=trim((string)($_POST['website']??''));$notes=trim((string)($_POST['notes']??''));$type='vlastní';}
 if($title===''||mb_strlen($title)>190)throw new InvalidArgumentException('Vyplň název akce.');
 if($website!==''&&!preg_match('~^https?://~i',$website))throw new InvalidArgumentException('Web musí začínat http:// nebo https://.');
 $pdo->prepare('INSERT INTO wp_ir2_events(user_id,title,event_type,starts_at,city,country,address,website,notes,want_visit'.($seriesReady?',series_id':'').') VALUES(?,?,?,?,?,?,?,?,?,?'.($seriesReady?',?':'').')')->execute([$uid,$title,$type,$dt->format('Y-m-d H:i:s'),$city,$country,$address,$website,$notes,1,...($seriesReady?[$sid?:null]:[])]);ir_redirect('events.php');
}catch(Throwable $e){error_log('Events: '.$e->getMessage());$error=$e instanceof InvalidArgumentException?$e->getMessage():'Akci se nepodařilo uložit. Zkontroluj údaje.';}}
$ownSeries=[];if($seriesReady){$q=$pdo->prepare('SELECT * FROM wp_ir2_event_series WHERE user_id=? ORDER BY name');$q->execute([$uid]);$ownSeries=$q->fetchAll();}
$public=ir_upcoming_public_events();$own=[];if($ok){$q=$pdo->prepare('SELECT * FROM wp_ir2_events WHERE user_id=? AND starts_at>=NOW() ORDER BY starts_at');$q->execute([$uid]);$own=$q->fetchAll()?:[];}ir_page_start('Burzy & akce','other');if($error)echo '<p class="flash danger" role="alert">'.ir_e($error).'</p>';?>
<?php
$eventDetail=null;
if(isset($_GET['public'])){$key=filter_var($_GET['public'],FILTER_VALIDATE_INT);$catalog=ir_public_event_catalog();if($key!==false&&isset($catalog[$key])){$e=$catalog[$key];$eventDetail=['title'=>$e[1],'starts_at'=>$e[0],'city'=>$e[2],'country'=>$e[3],'address'=>$e[4],'website'=>$e[5],'notes'=>'Termín z přiloženého katalogu aplikace.'];}}
if(isset($_GET['id'])){$q=$pdo->prepare('SELECT * FROM wp_ir2_events WHERE user_id=? AND id=?');$q->execute([$uid,(int)$_GET['id']]);$eventDetail=$q->fetch()?:null;if($eventDetail&&!empty($eventDetail['series_id'])&&$seriesReady){$q=$pdo->prepare('SELECT organizer,source FROM wp_ir2_event_series WHERE user_id=? AND id=?');$q->execute([$uid,$eventDetail['series_id']]);$eventDetail=array_merge($eventDetail,$q->fetch()?:[]);}}
if($eventDetail):?>
<section class="panel glow-panel"><header class="panel-head"><h2><?=ir_e($eventDetail['title'])?></h2><a href="events.php">Zpět na burzy</a></header><dl><?php foreach(['starts_at'=>'Datum a čas','city'=>'Město','country'=>'Stát','address'=>'Místo','notes'=>'Popis / poznámky','organizer'=>'Pořadatel','source'=>'Zdroj'] as $field=>$label):?><dt><?=ir_e($label)?></dt><dd><?=ir_e((string)($eventDetail[$field]??''))?:'Neuvedeno'?></dd><?php endforeach?></dl><?php if(preg_match('~^https?://~i',(string)$eventDetail['website'])):?><a target="_blank" rel="noopener noreferrer" href="<?=ir_e($eventDetail['website'])?>">Web / zdroj akce →</a><?php endif?></section>
<?php elseif(isset($_GET['public'])||isset($_GET['id'])):?><p class="flash danger">Akce nebyla nalezena.</p><?php endif;?>
<section class="panel glow-panel"><header class="panel-head"><h2>Akce a jejich termíny</h2></header><div class="workspace-grid">
<?php foreach(ir_event_series() as $series):?><details class="panel workspace-widget"><summary><strong><?=ir_e($series['name'])?></strong> · <?=ir_e($series['city'])?></summary><p><?=ir_e($series['place'])?></p><?php if(!$series['dates']):?><p>Termíny nejsou v přiložených zdrojích uvedeny.</p><?php endif;foreach($series['dates'] as $date):?><a class="widget-row" href="events.php?public=<?=$date['id']?>"><?=ir_e($date['starts_at'])?></a><?php endforeach?></details><?php endforeach?>
</div></section>
<div class="module-toolbar"><div class="module-tabs"><a href="contacts.php">Adresář</a><a href="documents.php">Dokumenty</a><a href="genetics.php">Genetika</a><a class="is-active" href="events.php">Burzy & akce</a></div></div>
<section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">KALENDÁŘ BURZ</span><h2>Nadcházející termíny</h2></div><span class="muted">Veřejný přehled + vlastní termíny</span></header><div class="event-list"><?php foreach($public as $e):$days=max(0,(int)ceil((strtotime($e[0])-time())/86400));?><a class="event-row" href="events.php?public=<?=array_search($e,ir_public_event_catalog(),true)?>"><time><b><?=date('d',strtotime($e[0]))?></b><span><?=date('m.Y',strtotime($e[0]))?></span></time><div><strong><?=ir_e($e[1])?></strong><small><?=ir_e($e[2].' · '.$e[3])?><?=trim($e[4])?' · '.ir_e($e[4]):''?></small></div><span><?=$days===0?'dnes':'za '.$days.' d.'?></span></a><?php endforeach?><?php foreach($own as $e):?><a class="event-row is-own" href="events.php?id=<?=$e['id']?>"><time><b><?=date('d',strtotime($e['starts_at']))?></b><span><?=date('m.Y',strtotime($e['starts_at']))?></span></time><div><strong><?=ir_e($e['title'])?></strong><small>Vlastní termín · <?=ir_e($e['city'])?></small></div><span>Detail →</span></a><?php endforeach?></div></section>
<details class="panel glow-panel event-own"><summary>+ Přidat vlastní akci, která v přehledu není</summary><form method="post" class="form-grid cols-3"><?=ir_csrf_field()?><?php if($ownSeries):?><label>Akce / série<select name="series_id"><option value="">Jednorázová vlastní akce</option><?php foreach($ownSeries as $series):?><option value="<?=$series['id']?>"><?=ir_e($series['name'])?></option><?php endforeach?></select></label><?php endif?><label>Název (pro jednorázovou akci)<input name="title"></label><label>Datum a čas<input type="datetime-local" name="starts_at" required></label><label>Město<input name="city"></label><label>Země<input name="country"></label><label>Web<input name="website"></label><label>Adresa<input name="address"></label><label class="span-3">Poznámka<textarea name="notes"></textarea></label><button class="btn primary">Uložit vlastní akci</button></form></details>
<?php if($seriesReady):?>
<section class="panel"><h2>Vlastní pravidelné akce</h2><div class="workspace-grid"><?php foreach($ownSeries as $series):?><details class="panel"><summary><?=ir_e($series['name'])?> · <?=ir_e($series['city'])?></summary><p><?=ir_e($series['place'].' · '.$series['organizer'])?></p><p><?=ir_e($series['description'])?></p><?php $q=$pdo->prepare('SELECT id,starts_at FROM wp_ir2_events WHERE user_id=? AND series_id=? ORDER BY starts_at');$q->execute([$uid,$series['id']]);$dates=$q->fetchAll();if(!$dates)echo '<p>Zatím bez termínů. Přidej termín ve formuláři výše.</p>';foreach($dates as $date):?><a class="widget-row" href="events.php?id=<?=$date['id']?>"><?=ir_e($date['starts_at'])?></a><?php endforeach?></details><?php endforeach?></div>
<details><summary>+ Založit pravidelnou akci</summary><form method="post" class="form-grid cols-3"><?=ir_csrf_field()?><input type="hidden" name="action" value="series"><?php foreach(['title'=>'Název','organizer'=>'Pořadatel','place'=>'Místo / adresa','city'=>'Město','country'=>'Stát','website'=>'URL','source'=>'Zdroj','event_type'=>'Typ akce'] as $key=>$label):?><label><?=$label?><input name="<?=$key?>" <?=$key==='title'?'required':''?> maxlength="<?=$key==='website'||$key==='source'?500:120?>"></label><?php endforeach?><label>Popis<textarea name="description"></textarea></label><button class="btn primary">Uložit pravidelnou akci</button></form></details></section>
<?php endif;ir_page_end();
