<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';$uid=ir_current_user_id();
try{$pdo->exec("CREATE TABLE IF NOT EXISTS wp_ir2_finance (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,typ VARCHAR(30) NOT NULL,kategorie VARCHAR(100) NULL,castka DECIMAL(12,2) NOT NULL DEFAULT 0,datum DATE NOT NULL,zvire_id BIGINT UNSIGNED NULL,popis TEXT NULL,vytvoreno TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id),INDEX(zvire_id),INDEX(datum)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}catch(Throwable $e){}
if($_SERVER['REQUEST_METHOD']==='POST'){ir_verify_csrf();try{$op=(string)($_POST['op']??'');if($op==='save'){$typ=(string)($_POST['typ']??'Výdaj');$amount=(float)str_replace(',','.',(string)($_POST['castka']??0));if($amount<0)throw new RuntimeException('Částka musí být kladná.');$aid=ir_int($_POST['zvire_id']??0)?:null;if($aid&&!ir_animal($pdo,$uid,$aid))throw new RuntimeException('Zvíře nebylo nalezeno.');if(!in_array($typ,['Příjem','Výdaj'],true))throw new RuntimeException('Neplatný typ transakce.');$pdo->prepare("INSERT INTO wp_ir2_finance(user_id,typ,kategorie,castka,datum,zvire_id,popis) VALUES(?,?,?,?,?,?,?)")->execute([$uid,$typ,trim((string)$_POST['kategorie']),$amount,$_POST['datum']?:date('Y-m-d'),$aid,trim((string)$_POST['popis'])]);ir_redirect('finance.php');}if($op==='delete'){$pdo->prepare('DELETE FROM wp_ir2_finance WHERE user_id=? AND id=?')->execute([$uid,ir_int($_POST['id']??0)]);ir_redirect('finance.php');}}catch(Throwable $e){error_log('Finance: '.$e->getMessage());$error=$e instanceof PDOException?'Transakci se nepodařilo uložit.':$e->getMessage();}}
$rows=[];$animals=[];$categories=[];try{
 $q=$pdo->prepare("SELECT f.*,z.jmeno_kod,z.latinsky_nazev FROM wp_ir2_finance f LEFT JOIN wp_ir2_zvirata z ON z.id=f.zvire_id AND z.user_id=f.user_id WHERE f.user_id=? ORDER BY f.datum DESC,f.id DESC LIMIT 300");$q->execute([$uid]);$rows=$q->fetchAll()?:[];
 $q=$pdo->prepare("SELECT id,jmeno_kod,latinsky_nazev,kupni_cena,trzni_hodnota,status_chovu FROM wp_ir2_zvirata WHERE user_id=? ORDER BY latinsky_nazev,jmeno_kod");$q->execute([$uid]);$animals=$q->fetchAll()?:[];
 $q=$pdo->prepare("SELECT COALESCE(kategorie,'Ostatní') kategorie,SUM(CASE WHEN typ='Výdaj' THEN castka ELSE 0 END) expense,SUM(CASE WHEN typ='Příjem' THEN castka ELSE 0 END) income FROM wp_ir2_finance WHERE user_id=? AND datum>=DATE_FORMAT(CURDATE(),'%Y-%m-01') GROUP BY COALESCE(kategorie,'Ostatní') ORDER BY expense DESC,income DESC LIMIT 8");$q->execute([$uid]);$categories=$q->fetchAll()?:[];
}catch(Throwable $e){}
$q=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN typ='Příjem' THEN castka ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN typ='Výdaj' THEN castka ELSE 0 END),0) expense,COALESCE(SUM(CASE WHEN typ='Příjem' AND datum>=DATE_FORMAT(CURDATE(),'%Y-%m-01') THEN castka ELSE 0 END),0) month_income,COALESCE(SUM(CASE WHEN typ='Výdaj' AND datum>=DATE_FORMAT(CURDATE(),'%Y-%m-01') THEN castka ELSE 0 END),0) month_expense FROM wp_ir2_finance WHERE user_id=?");$q->execute([$uid]);$totals=$q->fetch();$income=(float)$totals['income'];$expense=(float)$totals['expense'];$monthIncome=(float)$totals['month_income'];$monthExpense=(float)$totals['month_expense'];
$purchaseValue=0.0;$marketValue=0.0;foreach($animals as $a){if(in_array((string)$a['status_chovu'],['Prodáno','Uhynulo','Archiv'],true))continue;$purchaseValue+=(float)($a['kupni_cena']??0);$marketValue+=(float)($a['trzni_hodnota']??0);}
ir_page_start('Finance','finance');if(!empty($error))echo '<div class="flash danger">'.ir_e($error).'</div>';
?>
<section class="metric-grid finance-kpis">
 <article class="mini-metric glow-panel"><span><?=ir_visual_icon('finance')?></span><div><small>Bilance</small><strong><?=number_format($income-$expense,0,',',' ')?> Kč</strong><em>celkem</em></div></article>
 <article class="mini-metric glow-panel"><span><?=ir_visual_icon('calendar')?></span><div><small>Výdaje tento měsíc</small><strong><?=number_format($monthExpense,0,',',' ')?> Kč</strong><em>provoz chovu</em></div></article>
 <article class="mini-metric glow-panel"><span><?=ir_visual_icon('animals')?></span><div><small>Pořizovací cena chovu</small><strong><?=number_format($purchaseValue,0,',',' ')?> Kč</strong><em>aktivní zvířata</em></div></article>
 <article class="mini-metric glow-panel"><span><?=ir_visual_icon('dashboard')?></span><div><small>Odhad hodnoty chovu</small><strong><?=number_format($marketValue,0,',',' ')?> Kč</strong><em>z karet zvířat</em></div></article>
</section>
<div class="finance-layout">
<section class="panel glow-panel finance-records"><header class="panel-head"><div><span class="panel-kicker">FINANCE</span><h2>Transakce</h2></div><div><strong><?=number_format($monthIncome-$monthExpense,0,',',' ')?> Kč</strong><small>bilance měsíce</small></div></header><div class="table-scroll"><table class="data-table"><thead><tr><th>Datum</th><th>Typ</th><th>Kategorie</th><th>Zvíře</th><th>Popis</th><th>Částka</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=date('d.m.Y',strtotime((string)$r['datum']))?></td><td><span class="finance-type <?=((string)$r['typ']==='Příjem'?'income':'expense')?>"><?=ir_e((string)$r['typ'])?></span></td><td><?=ir_e((string)$r['kategorie'])?></td><td><?=ir_e((string)($r['latinsky_nazev']?:$r['jmeno_kod']?:'—'))?></td><td><?=ir_e((string)$r['popis'])?></td><td><strong><?=((string)$r['typ']==='Příjem'?'+':'−')?><?=number_format((float)$r['castka'],0,',',' ')?> Kč</strong></td><td><form method="post"><?=ir_csrf_field()?><input type="hidden" name="op" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn tiny danger" aria-label="Smazat transakci" onclick="return confirm('Smazat tuto transakci?')">×</button></form></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="7"><div class="table-empty">Bez finančních záznamů.</div></td></tr><?php endif;?></tbody></table></div></section>
<aside class="finance-side">
 <form class="panel glow-panel form-panel" method="post"><?=ir_csrf_field()?><input type="hidden" name="op" value="save"><header class="panel-head"><div><span class="panel-kicker">NOVÝ ZÁZNAM</span><h2>Příjem / výdaj</h2></div><button class="btn primary">Uložit</button></header><div class="form-grid"><label>Typ<select name="typ"><option>Výdaj</option><option>Příjem</option></select></label><label>Částka<input type="number" min="0" step="0.01" name="castka" required></label><label>Datum<input type="date" name="datum" value="<?=date('Y-m-d')?>"></label><label>Kategorie<input name="kategorie" placeholder="Krmivo, technika, prodej…"></label><label>Zvíře<select name="zvire_id"><option value="">Bez vazby</option><?php foreach($animals as $a):?><option value="<?=$a['id']?>"><?=ir_e((string)($a['latinsky_nazev']?:$a['jmeno_kod']))?> · <?=ir_e((string)$a['jmeno_kod'])?></option><?php endforeach;?></select></label><label>Popis<textarea name="popis"></textarea></label></div></form>
 <section class="panel glow-panel finance-category-summary"><header class="panel-head"><div><span class="panel-kicker">TENTO MĚSÍC</span><h2>Kategorie</h2></div></header><?php foreach($categories as $c):?><div class="finance-category-row"><span><?=ir_e((string)$c['kategorie'])?></span><strong><?=number_format((float)$c['expense'],0,',',' ')?> Kč</strong></div><?php endforeach;if(!$categories):?><p class="empty-state small">Zatím bez záznamů v tomto měsíci.</p><?php endif?></section>
</aside>
</div>
<?php ir_page_end();