<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';$uid=ir_current_user_id();
try{$pdo->exec("CREATE TABLE IF NOT EXISTS wp_ir2_finance (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,typ VARCHAR(30) NOT NULL,kategorie VARCHAR(100) NULL,castka DECIMAL(12,2) NOT NULL DEFAULT 0,datum DATE NOT NULL,zvire_id BIGINT UNSIGNED NULL,popis TEXT NULL,vytvoreno TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id),INDEX(zvire_id),INDEX(datum)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}catch(Throwable $e){}
if($_SERVER['REQUEST_METHOD']==='POST'){ir_verify_csrf();try{$op=(string)($_POST['op']??'');
 if($op==='save'){ir_require_perm('write');$ls=[];$items=(array)($_POST['line_item']??[]);foreach($items as $k=>$it)$ls[]=['item'=>$it,'qty'=>$_POST['line_qty'][$k]??1,'unit'=>$_POST['line_unit'][$k]??'','unit_price'=>$_POST['line_price'][$k]??0,'discount_pct'=>$_POST['line_disc'][$k]??0,'vat_pct'=>$_POST['line_vat'][$k]??0];
  if(!$ls&&($_POST['castka']??'')!=='')$ls[]=['item'=>trim((string)($_POST['popis']??''))?:trim((string)($_POST['kategorie']??''))?:'Položka','qty'=>1,'unit_price'=>$_POST['castka']];
  $fid=ir_finance_save($pdo,$uid,['typ'=>$_POST['typ']??'','kategorie'=>$_POST['kategorie']??'','datum'=>$_POST['datum']??'','zvire_id'=>ir_int($_POST['zvire_id']??0),'popis'=>$_POST['popis']??'','doklad'=>$_POST['doklad']??'','sold'=>!empty($_POST['sold'])],$ls,ir_int($_POST['id']??0));
  ir_flash('success','Doklad uložen.'.(!empty($_POST['sold'])&&ir_int($_POST['zvire_id']??0)?' Zvíře je označeno jako prodané (historie zůstává).':''));ir_redirect('finance.php');}
 if($op==='delete'){ir_require_perm('delete');ir_finance_delete($pdo,$uid,ir_int($_POST['id']??0));ir_flash('success','Doklad odstraněn.');ir_redirect('finance.php');}
}catch(Throwable $e){error_log('Finance: '.$e->getMessage());$error=$e instanceof PDOException?'Doklad se nepodařilo uložit. Nic nebylo zapsáno.':$e->getMessage();}}
$editFin=null;$editLines=[];if($eid=ir_int($_GET['edit']??0)){$q=$pdo->prepare('SELECT * FROM wp_ir2_finance WHERE user_id=? AND id=? AND smazano IS NULL');$q->execute([$uid,$eid]);$editFin=$q->fetch()?:null;if($editFin)$editLines=ir_finance_lines($pdo,$uid,$eid);}
$rows=[];$animals=[];$categories=[];try{
 $q=$pdo->prepare("SELECT f.*,z.jmeno_kod,z.latinsky_nazev,(SELECT COUNT(*) FROM wp_ir2_finance_lines l WHERE l.user_id=f.user_id AND l.finance_id=f.id) AS nlines FROM wp_ir2_finance f LEFT JOIN wp_ir2_zvirata z ON z.id=f.zvire_id AND z.user_id=f.user_id WHERE f.user_id=? AND f.smazano IS NULL ORDER BY f.datum DESC,f.id DESC LIMIT 300");$q->execute([$uid]);$rows=$q->fetchAll()?:[];
 $q=$pdo->prepare("SELECT id,jmeno_kod,latinsky_nazev,kupni_cena,trzni_hodnota,status_chovu FROM wp_ir2_zvirata WHERE user_id=? ORDER BY latinsky_nazev,jmeno_kod");$q->execute([$uid]);$animals=$q->fetchAll()?:[];
 $q=$pdo->prepare("SELECT COALESCE(kategorie,'Ostatní') kategorie,SUM(CASE WHEN typ='Výdaj' THEN castka ELSE 0 END) expense,SUM(CASE WHEN typ='Příjem' THEN castka ELSE 0 END) income FROM wp_ir2_finance WHERE user_id=? AND smazano IS NULL AND datum>=DATE_FORMAT(CURDATE(),'%Y-%m-01') GROUP BY COALESCE(kategorie,'Ostatní') ORDER BY expense DESC,income DESC LIMIT 8");$q->execute([$uid]);$categories=$q->fetchAll()?:[];
}catch(Throwable $e){}
$q=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN typ='Příjem' THEN castka ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN typ='Výdaj' THEN castka ELSE 0 END),0) expense,COALESCE(SUM(CASE WHEN typ='Příjem' AND datum>=DATE_FORMAT(CURDATE(),'%Y-%m-01') THEN castka ELSE 0 END),0) month_income,COALESCE(SUM(CASE WHEN typ='Výdaj' AND datum>=DATE_FORMAT(CURDATE(),'%Y-%m-01') THEN castka ELSE 0 END),0) month_expense FROM wp_ir2_finance WHERE user_id=? AND smazano IS NULL");$q->execute([$uid]);$totals=$q->fetch();$income=(float)$totals['income'];$expense=(float)$totals['expense'];$monthIncome=(float)$totals['month_income'];$monthExpense=(float)$totals['month_expense'];
$purchaseValue=0.0;$marketValue=0.0;foreach($animals as $a){if(in_array((string)$a['status_chovu'],['Prodáno','Uhynulo','Archiv'],true))continue;$purchaseValue+=(float)($a['kupni_cena']??0);$marketValue+=(float)($a['trzni_hodnota']??0);}
ir_page_start('Finance','finance');if(!empty($error))echo '<div class="flash danger">'.ir_e($error).'</div>';
?>
<section class="metric-grid finance-kpis">
 <article class="mini-metric glow-panel"><span><?=ir_visual_icon('finance')?></span><div><small>Bilance</small><strong><?=number_format($income-$expense,0,',',' ')?> Kč</strong><em>celkem</em></div></article>
 <article class="mini-metric glow-panel"><span><?=ir_visual_icon('calendar')?></span><div><small>Výdaje tento měsíc</small><strong><?=number_format($monthExpense,0,',',' ')?> Kč</strong><em>provoz chovu</em></div></article>
 <article class="mini-metric glow-panel"><span><?=ir_visual_icon('animals')?></span><div><small>Pořizovací cena chovu</small><strong><?=number_format($purchaseValue,0,',',' ')?> Kč</strong><em>aktivní zvířata</em></div></article>
 <article class="mini-metric glow-panel"><span><?=ir_visual_icon('dashboard')?></span><div><small>Odhad hodnoty chovu</small><strong><?=number_format($marketValue,0,',',' ')?> Kč</strong><em>z karet zvířat</em></div></article>
</section>
<div class="finance-layout">
<section class="panel glow-panel finance-records"><header class="panel-head"><div><span class="panel-kicker">FINANCE</span><h2>Transakce</h2></div><div><strong><?=number_format($monthIncome-$monthExpense,0,',',' ')?> Kč</strong><small>bilance měsíce</small></div></header><div class="table-scroll"><table class="data-table"><thead><tr><th>Datum</th><th>Typ</th><th>Kategorie</th><th>Zvíře</th><th>Popis</th><th>Částka</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=date('d.m.Y',strtotime((string)$r['datum']))?></td><td><span class="finance-type <?=((string)$r['typ']==='Příjem'?'income':'expense')?>"><?=ir_e((string)$r['typ'])?></span></td><td><?=ir_e((string)$r['kategorie'])?></td><td><?=ir_e((string)($r['latinsky_nazev']?:$r['jmeno_kod']?:'—'))?></td><td><?=ir_e((string)$r['popis'])?><?=(int)$r['nlines']>1?' <small class="muted">· '.(int)$r['nlines'].' položek</small>':''?></td><td><strong><?=((string)$r['typ']==='Příjem'?'+':'−')?><?=number_format((float)$r['castka'],0,',',' ')?> Kč</strong></td><td class="b1-rowact"><a class="btn tiny" href="finance.php?edit=<?=(int)$r['id']?>#fin-form">Upravit</a><form method="post" class="b1-inline-mini"><?=ir_csrf_field()?><input type="hidden" name="op" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn tiny danger" aria-label="Smazat transakci" onclick="return confirm('Smazat tuto transakci?')">×</button></form></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="7"><div class="table-empty">Bez finančních záznamů.</div></td></tr><?php endif;?></tbody></table></div></section>
<aside class="finance-side">
 <form id="fin-form" class="panel glow-panel form-panel b1-fin" method="post" data-fin><?=ir_csrf_field()?><input type="hidden" name="op" value="save"><input type="hidden" name="id" value="<?=(int)($editFin['id']??0)?>"><header class="panel-head"><div><span class="panel-kicker"><?=$editFin?'ÚPRAVA DOKLADU':'NOVÝ DOKLAD'?></span><h2>Příjem / výdaj</h2></div><button class="btn primary">Uložit</button></header>
 <div class="b1-form-grid"><label>Typ<select class="input" name="typ" data-fin-type><option <?=($editFin['typ']??'')==='Výdaj'?'selected':''?>>Výdaj</option><option <?=($editFin['typ']??'')==='Příjem'?'selected':''?>>Příjem</option></select></label><label>Datum<input class="input" type="date" name="datum" value="<?=ir_e((string)($editFin['datum']??date('Y-m-d')))?>"></label><label>Kategorie<input class="input" name="kategorie" list="fin-cats" value="<?=ir_e((string)($editFin['kategorie']??''))?>" placeholder="Krmivo, technika, prodej…"></label><label>Číslo dokladu<input class="input" name="doklad" value="<?=ir_e((string)($editFin['doklad']??''))?>"></label>
 <label class="b1-wide">Zvíře (nepovinné)<select class="input" name="zvire_id"><option value="">Bez vazby</option><?php foreach($animals as $a):?><option value="<?=$a['id']?>" <?=(int)($editFin['zvire_id']??0)===(int)$a['id']?'selected':''?>><?=ir_e((string)($a['latinsky_nazev']?:$a['jmeno_kod']))?> · <?=ir_e((string)$a['jmeno_kod'])?></option><?php endforeach;?></select></label>
 <label class="b1-check b1-wide" data-fin-sold hidden><input type="checkbox" name="sold" value="1"> Prodej zvířete — označit zvíře jako prodané (karta i historie zůstanou)</label></div>
 <div class="b1-fin-lines"><div class="b1-fin-head"><span>Položka</span><span>Množ.</span><span>Jedn.</span><span>Cena/j.</span><span>Sleva %</span><span>DPH %</span><span>Celkem</span><span></span></div><div data-fin-rows>
 <?php foreach(($editLines?:[['item'=>'','qty'=>1,'unit'=>'ks','unit_price'=>'','discount_pct'=>'','vat_pct'=>'','total'=>0]]) as $l):?><div class="b1-fin-row"><input class="input" name="line_item[]" value="<?=ir_e((string)$l['item'])?>" placeholder="Např. Dubia M" aria-label="Položka"><input class="input" name="line_qty[]" value="<?=ir_e(rtrim(rtrim((string)$l['qty'],'0'),'.'))?>" inputmode="decimal" aria-label="Množství"><input class="input" name="line_unit[]" value="<?=ir_e((string)($l['unit']??''))?>" aria-label="Jednotka"><input class="input" name="line_price[]" value="<?=ir_e((string)$l['unit_price'])?>" inputmode="decimal" aria-label="Cena za jednotku"><input class="input" name="line_disc[]" value="<?=ir_e((string)($l['discount_pct']??''))?>" inputmode="decimal" aria-label="Sleva"><input class="input" name="line_vat[]" value="<?=ir_e((string)($l['vat_pct']??''))?>" inputmode="decimal" aria-label="DPH"><output>0</output><button type="button" class="b1-icon-btn danger" data-fin-del aria-label="Odebrat řádek">✕</button></div><?php endforeach;?>
 </div><div class="b1-fin-foot"><button type="button" class="btn small" data-fin-add>+ Řádek</button><strong>Celkem <span data-fin-sum>0</span> Kč</strong></div></div>
 <label class="b1-wide" style="display:block;padding:0 12px 12px">Poznámka<textarea class="input" name="popis"><?=ir_e((string)($editFin['popis']??''))?></textarea></label>
 <datalist id="fin-cats"><option>Krmivo</option><option>Technika</option><option>Vybavení</option><option>Veterinář</option><option>Zvířata — nákup</option><option>Prodej zvířat</option><option>Burzy a doprava</option><option>Energie</option></datalist>
 </form>
 <section class="panel glow-panel finance-category-summary"><header class="panel-head"><div><span class="panel-kicker">TENTO MĚSÍC</span><h2>Kategorie</h2></div></header><?php foreach($categories as $c):?><div class="finance-category-row"><span><?=ir_e((string)$c['kategorie'])?></span><strong><?=number_format((float)$c['expense'],0,',',' ')?> Kč</strong></div><?php endforeach;if(!$categories):?><p class="empty-state small">Zatím bez záznamů v tomto měsíci.</p><?php endif?></section>
</aside>
</div>
<script>
addEventListener('DOMContentLoaded',()=>{const f=document.querySelector('[data-fin]');if(!f)return;const rows=f.querySelector('[data-fin-rows]');
const num=v=>parseFloat(String(v||'').replace(',','.'))||0;
const calc=()=>{let s=0;rows.querySelectorAll('.b1-fin-row').forEach(r=>{const i=r.querySelectorAll('input');const t=num(i[1].value||1)*num(i[3].value)*(1-num(i[4].value)/100)*(1+num(i[5].value)/100);r.querySelector('output').textContent=t.toLocaleString('cs-CZ',{maximumFractionDigits:2});s+=t;});f.querySelector('[data-fin-sum]').textContent=s.toLocaleString('cs-CZ',{maximumFractionDigits:2});};
f.addEventListener('input',calc);f.querySelector('[data-fin-add]').addEventListener('click',()=>{const r=rows.lastElementChild.cloneNode(true);r.querySelectorAll('input').forEach((i,k)=>i.value=k===1?'1':(k===2?'ks':''));rows.append(r);r.querySelector('input').focus();calc();});
rows.addEventListener('click',e=>{if(e.target.closest('[data-fin-del]')&&rows.children.length>1){e.target.closest('.b1-fin-row').remove();calc();}});
const t=f.querySelector('[data-fin-type]'),a=f.querySelector('[name=zvire_id]'),sold=f.querySelector('[data-fin-sold]');const sv=()=>{sold.hidden=!(t.value==='Příjem'&&a.value);};t.addEventListener('change',sv);a.addEventListener('change',sv);sv();calc();});
</script>
<?php ir_page_end();