<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';
require __DIR__.'/includes/live.php';
require __DIR__.'/includes/shell.php';
require __DIR__.'/includes/reptile_core.php';
require_once __DIR__.'/includes/assembly-layout.php';
require_once __DIR__.'/includes/habitat-types.php';
$uid=ir_current_user_id();
$view=preg_replace('/[^a-z-]/','',(string)($_GET['view']??'overview'));
if(!in_array($view,['overview','new','assemblies'],true))$view='overview';
if(!empty($_GET['id']))$view='new';

function ir_habitats_parse_dims(string $raw): array {
    preg_match_all('/\d+(?:[\.,]\d+)?/',mb_strtolower(trim($raw),'UTF-8'),$m);
    $n=array_map(static fn($v)=>(float)str_replace(',','.',$v),$m[0]??[]);
    if(count($n)<3)throw new RuntimeException('Rozměry zadej jako šířka × hloubka × výška, např. 60×45×60 cm.');
    return [max(10,min(600,$n[0])),max(10,min(300,$n[1])),max(10,min(400,$n[2]))];
}
function ir_habitats_fmt(float $n): string {$s=number_format($n,1,'.','');return rtrim(rtrim($s,'0'),'.');}
function ir_habitats_recalc_rack(PDO $pdo,int $uid,int $rackId): void {
    if($rackId<=0||!ir_db_table_exists($pdo,'wp_ir2_habitat_rack_meta_71')||!ir_db_table_exists($pdo,'wp_ir2_habitat_assembly_blocks_130')||!ir_db_table_exists($pdo,'wp_ir2_habitat_geometry_74')||!function_exists('ir_assembly_dimensions'))return;
    try{[$w,$h,$d]=ir_assembly_dimensions($pdo,$uid,$rackId);$pdo->prepare("INSERT INTO wp_ir2_habitat_rack_meta_71 (user_id,rack_id,assembly_type,width_cm,depth_cm,height_cm) VALUES (?,?,'modular',?,?,?) ON DUPLICATE KEY UPDATE width_cm=VALUES(width_cm),depth_cm=VALUES(depth_cm),height_cm=VALUES(height_cm)")->execute([$uid,$rackId,$w,$d,$h]);if(ir_db_table_exists($pdo,'wp_ir2_habitat_room_items_71'))$pdo->prepare('UPDATE wp_ir2_habitat_room_items_71 SET width_cm=?,depth_cm=? WHERE user_id=? AND rack_id=?')->execute([$w,$d,$uid,$rackId]);}catch(Throwable $e){error_log('IR habitat rack recalc: '.$e->getMessage());}
}

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    ir_verify_csrf();$action=(string)($_POST['action']??'');$id=ir_int($_POST['id']??0);
    try{
        if($action==='save-rack'){
            $name=trim((string)($_POST['nazev']??''));if($name==='')throw new RuntimeException('Chybí název sestavy.');
            $location=trim((string)($_POST['umisteni']??''));$rows=max(1,min(20,(int)($_POST['rows']??1)));$cols=max(1,min(20,(int)($_POST['cols']??1)));$note=trim((string)($_POST['poznamka']??''));
            if($id>0){if(!ir_action_owned($pdo,'wp_ir2_racky',$uid,$id))throw new RuntimeException('Sestava nebyla nalezena.');$pdo->prepare('UPDATE wp_ir2_racky SET nazev=?,umisteni=?,pocet_radku=?,pocet_sloupcu=?,poznamka=? WHERE user_id=? AND id=?')->execute([$name,$location,$rows,$cols,$note,$uid,$id]);ir_habitats_recalc_rack($pdo,$uid,$id);}else{$pdo->prepare('INSERT INTO wp_ir2_racky(user_id,nazev,umisteni,pocet_radku,pocet_sloupcu,poznamka) VALUES(?,?,?,?,?,?)')->execute([$uid,$name,$location,$rows,$cols,$note]);$id=(int)$pdo->lastInsertId();}
            ir_redirect('habitats.php?view=assemblies&rack='.$id.'&saved=1');
        }
        if($action==='delete-rack'&&$id){
            $pdo->beginTransaction();$q=$pdo->prepare('SELECT id FROM wp_ir2_racky WHERE user_id=? AND id=? FOR UPDATE');$q->execute([$uid,$id]);if(!$q->fetchColumn())throw new RuntimeException('Sestava nebyla nalezena.');
            foreach(['wp_ir2_ubikace','wp_ir2_habitat_room_items_71','wp_ir2_habitat_assembly_blocks_130'] as $table){if(!ir_db_table_exists($pdo,$table))continue;$q=$pdo->prepare("SELECT COUNT(*) FROM $table WHERE user_id=? AND rack_id=?");$q->execute([$uid,$id]);if((int)$q->fetchColumn())throw new RuntimeException('Sestava obsahuje ubikace nebo je umístěna v místnosti. Nejdřív ji vyprázdni / odeber z místnosti.');}
            if(ir_db_table_exists($pdo,'wp_ir2_habitat_rack_meta_71'))$pdo->prepare('DELETE FROM wp_ir2_habitat_rack_meta_71 WHERE user_id=? AND rack_id=?')->execute([$uid,$id]);$pdo->prepare('DELETE FROM wp_ir2_racky WHERE user_id=? AND id=?')->execute([$uid,$id]);$pdo->commit();ir_redirect('habitats.php?view=assemblies');
        }
        if($action==='save-cage'){
            $hid=ir_int($_POST['id']??0);$name=trim((string)($_POST['nazev']??''));if($name==='')throw new RuntimeException('Chybí název ubikace.');$type=ir_habitat_type((string)($_POST['typ']??'Terárium'));[$w,$d,$h]=ir_habitats_parse_dims((string)($_POST['rozmery']??''));$dims=ir_habitats_fmt($w).'x'.ir_habitats_fmt($d).'x'.ir_habitats_fmt($h);$rid=ir_int($_POST['rack_id']??0);if($rid&&!ir_action_owned($pdo,'wp_ir2_racky',$uid,$rid))throw new RuntimeException('Sestava nebyla nalezena.');$row=ir_int($_POST['grid_row']??0)?:null;$col=ir_int($_POST['grid_col']??0)?:null;$tempDay=($_POST['teplota_den']??'')!==''?(float)str_replace(',','.',(string)$_POST['teplota_den']):null;$tempNight=($_POST['teplota_noc']??'')!==''?(float)str_replace(',','.',(string)$_POST['teplota_noc']):null;$humidity=($_POST['vlhkost']??'')!==''?max(0,min(100,(int)$_POST['vlhkost'])):null;$note=trim((string)($_POST['poznamka']??''));$oldRack=0;$pdo->beginTransaction();
            if($hid>0){if(!ir_action_owned($pdo,'wp_ir2_ubikace',$uid,$hid))throw new RuntimeException('Ubikace nebyla nalezena.');$q=$pdo->prepare('SELECT rack_id FROM wp_ir2_ubikace WHERE id=? AND user_id=? FOR UPDATE');$q->execute([$hid,$uid]);$oldRack=(int)($q->fetchColumn()?:0);$pdo->prepare('UPDATE wp_ir2_ubikace SET nazev=?,typ=?,rozmery=?,teplota_den=?,teplota_noc=?,vlhkost=?,rack_id=?,grid_row=?,grid_col=?,poznamka=? WHERE id=? AND user_id=?')->execute([$name,$type,$dims,$tempDay,$tempNight,$humidity,$rid?:null,$row,$col,$note,$hid,$uid]);if($oldRack!==$rid&&ir_db_table_exists($pdo,'wp_ir2_habitat_assembly_blocks_130'))$pdo->prepare('DELETE FROM wp_ir2_habitat_assembly_blocks_130 WHERE user_id=? AND habitat_id=?')->execute([$uid,$hid]);}
            else{$pdo->prepare('INSERT INTO wp_ir2_ubikace(user_id,nazev,typ,rozmery,teplota_den,teplota_noc,vlhkost,rack_id,grid_row,grid_col,poznamka) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$uid,$name,$type,$dims,$tempDay,$tempNight,$humidity,$rid?:null,$row,$col,$note]);$hid=(int)$pdo->lastInsertId();}
            if(ir_db_table_exists($pdo,'wp_ir2_habitat_geometry_74'))$pdo->prepare("INSERT INTO wp_ir2_habitat_geometry_74 (user_id,habitat_id,shape,width_cm,depth_cm,height_cm) VALUES (?,?,'rect',?,?,?) ON DUPLICATE KEY UPDATE width_cm=VALUES(width_cm),depth_cm=VALUES(depth_cm),height_cm=VALUES(height_cm)")->execute([$uid,$hid,$w,$d,$h]);$pdo->commit();if($oldRack)ir_habitats_recalc_rack($pdo,$uid,$oldRack);if($rid&&$rid!==$oldRack)ir_habitats_recalc_rack($pdo,$uid,$rid);ir_redirect('habitats.php?view=overview&saved=1');
        }
        if($action==='delete-cage'&&$id){if(!ir_action_owned($pdo,'wp_ir2_ubikace',$uid,$id))throw new RuntimeException('Ubikace nebyla nalezena.');$q=$pdo->prepare('SELECT COUNT(*) FROM wp_ir2_zvirata WHERE user_id=? AND ubikace_id=?');$q->execute([$uid,$id]);if((int)$q->fetchColumn()>0)throw new RuntimeException('Obsazenou ubikaci nelze smazat.');$q=$pdo->prepare('SELECT rack_id FROM wp_ir2_ubikace WHERE id=? AND user_id=?');$q->execute([$id,$uid]);$oldRack=(int)($q->fetchColumn()?:0);$pdo->beginTransaction();if(ir_db_table_exists($pdo,'wp_ir2_habitat_assembly_blocks_130'))$pdo->prepare('DELETE FROM wp_ir2_habitat_assembly_blocks_130 WHERE user_id=? AND habitat_id=?')->execute([$uid,$id]);if(ir_db_table_exists($pdo,'wp_ir2_habitat_geometry_74'))$pdo->prepare('DELETE FROM wp_ir2_habitat_geometry_74 WHERE user_id=? AND habitat_id=?')->execute([$uid,$id]);$pdo->prepare('DELETE FROM wp_ir2_ubikace WHERE id=? AND user_id=?')->execute([$id,$uid]);$pdo->commit();if($oldRack)ir_habitats_recalc_rack($pdo,$uid,$oldRack);ir_redirect('habitats.php?view=overview');}
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Habitats action: '.$e->getMessage());$error=$e instanceof PDOException?'Změnu se nepodařilo uložit.':$e->getMessage();}
}

$racks=[];$cages=[];$editCage=null;$editRack=null;
try{$st=$pdo->prepare("SELECT r.*,(SELECT COUNT(*) FROM wp_ir2_ubikace u WHERE u.user_id=r.user_id AND u.rack_id=r.id) cage_count FROM wp_ir2_racky r WHERE r.user_id=? ORDER BY r.poradi,r.nazev");$st->execute([$uid]);$racks=$st->fetchAll()?:[];$st=$pdo->prepare("SELECT u.*,(SELECT COUNT(*) FROM wp_ir2_zvirata z WHERE z.user_id=u.user_id AND z.ubikace_id=u.id AND ".ir_status_active_sql('z').") animal_count FROM wp_ir2_ubikace u WHERE u.user_id=? ORDER BY u.rack_id,u.grid_row,u.grid_col,u.nazev");$st->execute([$uid]);$cages=$st->fetchAll()?:[];$editId=ir_int($_GET['id']??0);if($editId){$st=$pdo->prepare('SELECT * FROM wp_ir2_ubikace WHERE user_id=? AND id=?');$st->execute([$uid,$editId]);$editCage=$st->fetch()?:null;}$rackId=ir_int($_GET['rack']??0);if($rackId){$st=$pdo->prepare('SELECT * FROM wp_ir2_racky WHERE user_id=? AND id=?');$st->execute([$uid,$rackId]);$editRack=$st->fetch()?:null;}}catch(Throwable $e){error_log('Habitats load: '.$e->getMessage());}
$cagesByRack=[];foreach($cages as $c)if(!empty($c['rack_id']))$cagesByRack[(int)$c['rack_id']][]=$c;
$totalCages=count($cages);$occupied=count(array_filter($cages,fn($c)=>(int)$c['animal_count']>0));$free=$totalCages-$occupied;$byType=[];foreach($cages as $c){$t=(string)($c['typ']?:'Neurčeno');$byType[$t]=($byType[$t]??0)+1;}
ir_page_start('Ubikace & sestavy','habitat');
if(!empty($error))echo '<div class="flash danger">'.ir_e($error).'</div>';if(isset($_GET['saved']))echo '<div class="flash success">Změna byla uložena.</div>';
?>
<nav class="module-tabs habitat-tabs-063"><a class="<?=$view==='overview'?'is-active':''?>" href="habitats.php?view=overview">Přehled</a><a class="<?=$view==='new'?'is-active':''?>" href="habitats.php?view=new">+ Nová ubikace</a><a class="<?=$view==='assemblies'?'is-active':''?>" href="habitats.php?view=assemblies">Sestavy</a><a href="habitat-studio.php">Habitat Studio</a></nav>
<?php if($view==='overview'): ?>
<section class="metric-grid habitat-kpis"><article class="mini-metric glow-panel"><span><?=ir_visual_icon('habitat')?></span><div><small>Ubikace</small><strong><?=$totalCages?></strong><em>celkem</em></div></article><article class="mini-metric glow-panel"><span><?=ir_visual_icon('status-ok')?></span><div><small>Obsazené</small><strong><?=$occupied?></strong><em>aktivní chov</em></div></article><article class="mini-metric glow-panel"><span><?=ir_visual_icon('inventory')?></span><div><small>Sestavy</small><strong><?=count($racks)?></strong><em>racky / moduly</em></div></article><article class="mini-metric glow-panel"><span><?=ir_visual_icon('add')?></span><div><small>Volné</small><strong><?=$free?></strong><em>připravené</em></div></article></section>
<section class="panel glow-panel habitat-type-overview"><header class="panel-head"><div><span class="panel-kicker">RYCHLÝ PŘEHLED</span><h2>Ubikace podle typu</h2></div><a class="btn primary" href="habitats.php?view=new">+ Ubikace</a></header><div class="habitat-type-grid"><?php foreach($byType as $type=>$count):?><article class="habitat-type-card"><span><?=ir_visual_icon('habitat')?></span><div><strong><?=ir_e($type)?></strong><small><?=$count?> ubikací</small></div></article><?php endforeach;if(!$byType):?><div class="empty-state small">Bez ubikací.</div><?php endif?></div></section>
<section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">UBIKACE</span><h2>Aktivní prostor</h2></div></header><div class="cage-overview-grid"><?php foreach($cages as $c):$isOcc=(int)$c['animal_count']>0;?><article class="cage-overview-card <?=$isOcc?'is-occupied':'is-empty'?>"><div class="cage-state-dot"></div><div class="cage-overview-main"><?=ir_visual_icon('habitat')?><div><strong><?=ir_e((string)$c['nazev'])?></strong><small><?=ir_e((string)$c['typ'])?> · <?=ir_e((string)$c['rozmery'])?> cm</small></div></div><div class="cage-overview-meta"><span><?=$c['animal_count']?> zvířat</span><span><?=!empty($c['teplota_den'])?ir_e((string)$c['teplota_den']).' °C':'—'?></span><span><?=!empty($c['vlhkost'])?ir_e((string)$c['vlhkost']).' %':'—'?></span></div><div class="row-actions"><a href="print.php?type=cage&id=<?=$c['id']?>" target="_blank">QR</a><a href="habitats.php?view=new&id=<?=$c['id']?>">Upravit</a></div></article><?php endforeach;if(!$cages):?><div class="empty-state small">Bez ubikací.</div><?php endif?></div></section>
<?php elseif($view==='assemblies'): ?>
<section class="panel glow-panel assemblies-panel-063"><header class="panel-head"><div><span class="panel-kicker">SESTAVY</span><h2>Racky bez kilometrového seznamu</h2><p>Náhled obsahu, rozložení buněk a editace na jednom místě.</p></div><a class="btn" href="print.php?type=racks" target="_blank">QR všech sestav</a></header><div class="assembly-card-grid-063"><?php foreach($racks as $r):$items=$cagesByRack[(int)$r['id']]??[];$map=[];$overflow=[];foreach($items as $c){$rr=(int)($c['grid_row']??0);$cc=(int)($c['grid_col']??0);if($rr>0&&$cc>0)$map[$rr.'-'.$cc]=$c;else $overflow[]=$c;}?><article class="assembly-card-063"><header><div><?=ir_visual_icon('inventory')?><span><strong><?=ir_e((string)$r['nazev'])?></strong><small><?=ir_e((string)($r['umisteni']?:'Bez umístění'))?> · <?=$r['pocet_radku']?>×<?=$r['pocet_sloupcu']?></small></span></div><b><?=$r['cage_count']?> ubikací</b></header><div class="assembly-mini-grid-063" style="--cols:<?=max(1,(int)$r['pocet_sloupcu'])?>"><?php for($rr=1;$rr<=max(1,(int)$r['pocet_radku']);$rr++)for($cc=1;$cc<=max(1,(int)$r['pocet_sloupcu']);$cc++):$c=$map[$rr.'-'.$cc]??null;?><span class="<?=$c?'is-filled':'is-empty'?>" title="<?=$c?ir_e((string)$c['nazev']):'Volná pozice'?>"><?=$c?ir_visual_icon('habitat'):''?></span><?php endfor?></div><?php if($overflow):?><div class="assembly-overflow-063"><strong>Bez pozice:</strong> <?php foreach($overflow as $c):?><span><?=ir_e((string)$c['nazev'])?></span><?php endforeach?></div><?php endif?><footer><a class="btn small" href="habitats.php?view=assemblies&rack=<?=$r['id']?>">Upravit sestavu</a><a class="btn small" href="habitat-studio.php?rack=<?=$r['id']?>">Studio</a><a class="btn small" href="print.php?type=rack&id=<?=$r['id']?>" target="_blank">QR</a></footer></article><?php endforeach;if(!$racks):?><div class="empty-state">Zatím žádné sestavy.</div><?php endif?></div></section>
<?php $rf=$editRack?:['id'=>0,'nazev'=>'','umisteni'=>'','pocet_radku'=>4,'pocet_sloupcu'=>4,'poznamka'=>''];?><section class="panel glow-panel assembly-editor-063"><header class="panel-head"><div><span class="panel-kicker"><?=$editRack?'ÚPRAVA SESTAVY':'NOVÁ SESTAVA'?></span><h2><?=$editRack?ir_e((string)$editRack['nazev']):'Přidat sestavu'?></h2></div><?php if($editRack):?><a class="btn" href="habitats.php?view=assemblies">Nová sestava</a><?php endif?></header><form method="post" class="form-grid cols-3"><?=ir_csrf_field()?><input type="hidden" name="action" value="save-rack"><input type="hidden" name="id" value="<?=intval($rf['id'])?>"><label>Název<input name="nazev" required value="<?=ir_e((string)$rf['nazev'])?>"></label><label>Umístění<input name="umisteni" value="<?=ir_e((string)$rf['umisteni'])?>"></label><label>Poznámka<input name="poznamka" value="<?=ir_e((string)$rf['poznamka'])?>"></label><label>Řádky<input type="number" min="1" max="20" name="rows" value="<?=intval($rf['pocet_radku'])?>"></label><label>Sloupce<input type="number" min="1" max="20" name="cols" value="<?=intval($rf['pocet_sloupcu'])?>"></label><button class="btn primary"><?=$editRack?'Uložit sestavu':'Vytvořit sestavu'?></button></form><?php if($editRack):?><form method="post" class="danger-zone" onsubmit="return confirm('Smazat sestavu?')"><?=ir_csrf_field()?><input type="hidden" name="id" value="<?=intval($rf['id'])?>"><button class="btn danger" name="action" value="delete-rack">Smazat sestavu</button></form><?php endif?></section>
<?php else: $form=$editCage?:['id'=>0,'nazev'=>'','typ'=>'Terárium','rozmery'=>'60x45x60','rack_id'=>'','grid_row'=>'','grid_col'=>'','teplota_den'=>'','teplota_noc'=>'','vlhkost'=>'','poznamka'=>'']; ?>
<section id="habitat-editor" class="panel glow-panel habitat-editor-panel"><header class="panel-head"><div><span class="panel-kicker"><?=$editCage?'ÚPRAVA':'NOVÁ UBIKACE'?></span><h2><?=$editCage?ir_e((string)$editCage['nazev']):'Přidat ubikaci'?></h2></div><?php if($editCage):?><a class="btn secondary" href="habitats.php?view=new">Nová ubikace</a><?php endif?></header><form class="form-grid cols-3 compact-form" method="post"><?=ir_csrf_field()?><input type="hidden" name="action" value="save-cage"><input type="hidden" name="id" value="<?=intval($form['id']??0)?>"><label>Název<input name="nazev" value="<?=ir_e((string)($form['nazev']??''))?>" required></label><label>Typ<select name="typ"><?php foreach(ir_habitat_types() as $type):?><option value="<?=ir_e($type)?>" <?=((string)($form['typ']??''))===$type?'selected':''?>><?=ir_e($type)?></option><?php endforeach?></select></label><label>Rozměry<input name="rozmery" value="<?=ir_e((string)($form['rozmery']??''))?>" placeholder="60×45×60 cm" required></label><label>Sestava<select name="rack_id"><option value="">Bez sestavy</option><?php foreach($racks as $r):?><option value="<?=$r['id']?>" <?=((int)($form['rack_id']??0)===(int)$r['id']?'selected':'')?>><?=ir_e((string)$r['nazev'])?></option><?php endforeach?></select></label><label>Řádek<input type="number" min="1" name="grid_row" value="<?=ir_e((string)($form['grid_row']??''))?>"></label><label>Sloupec<input type="number" min="1" name="grid_col" value="<?=ir_e((string)($form['grid_col']??''))?>"></label><label>Denní teplota °C<input type="number" step="0.1" name="teplota_den" value="<?=ir_e((string)($form['teplota_den']??''))?>"></label><label>Noční teplota °C<input type="number" step="0.1" name="teplota_noc" value="<?=ir_e((string)($form['teplota_noc']??''))?>"></label><label>Vlhkost %<input type="number" min="0" max="100" name="vlhkost" value="<?=ir_e((string)($form['vlhkost']??''))?>"></label><label class="span-3">Poznámka<input name="poznamka" value="<?=ir_e((string)($form['poznamka']??''))?>"></label><button class="btn primary span-3"><?=$editCage?'Uložit změny':'+ Přidat ubikaci'?></button></form><?php if($editCage&&(int)($editCage['animal_count']??0)===0):?><form method="post" class="danger-zone" onsubmit="return confirm('Trvale smazat ubikaci?')"><?=ir_csrf_field()?><input type="hidden" name="id" value="<?=$editCage['id']?>"><button class="btn danger" name="action" value="delete-cage">Smazat ubikaci</button></form><?php endif?></section>
<?php endif; ir_page_end();
