<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require_once __DIR__.'/includes/habitat-connectors.php';
$uid=ir_current_user_id();$notice='';$error='';
try{ir_habitat_connector_ensure_tables($pdo);}catch(Throwable $e){$error='Databázové tabulky Home Assistant se nepodařilo připravit.';error_log($e->getMessage());}
if($_SERVER['REQUEST_METHOD']==='POST')try{ir_verify_csrf();$action=(string)($_POST['action']??'');if($action==='save_source'){$name=trim((string)($_POST['name']??'Home Assistant'))?:'Home Assistant';$url=rtrim(trim((string)($_POST['base_url']??'')),'/');$token=trim((string)($_POST['token']??''));if($url===''||$token==='')throw new RuntimeException('Vyplň URL Home Assistant a Long-Lived Access Token.');$url=ir_habitat_validate_base_url($url);ir_habitat_request($url,$token,'/api/');$q=$pdo->prepare("INSERT INTO wp_ir2_habitat_sources_15(user_id,name,kind,base_url,token_enc,enabled,last_sync,last_error) VALUES (?,?, 'home_assistant',?,?,1,NOW(),NULL)");$q->execute([$uid,$name,$url,ir_habitat_secret_encrypt($token)]);$notice='Home Assistant byl připojen a API odpovědělo správně.';}
if($action==='delete_source'){$id=(int)($_POST['source_id']??0);$pdo->prepare('DELETE FROM wp_ir2_habitat_sensor_bindings_15 WHERE user_id=? AND source_id=?')->execute([$uid,$id]);$pdo->prepare('DELETE FROM wp_ir2_habitat_sources_15 WHERE user_id=? AND id=?')->execute([$uid,$id]);$notice='Zdroj byl odebrán.';}
if($action==='bind'){$sid=(int)$_POST['source_id'];$hid=(int)($_POST['habitat_id']??0);$entity=trim((string)$_POST['entity_id']);$metric=(string)($_POST['metric']??'temperature');if($sid<1||$entity==='')throw new RuntimeException('Vyber zdroj a entitu.');$q=$pdo->prepare("INSERT INTO wp_ir2_habitat_sensor_bindings_15(user_id,source_id,habitat_id,entity_id,label,metric,enabled) VALUES (?,?,?,?,?,?,1) ON DUPLICATE KEY UPDATE label=VALUES(label),metric=VALUES(metric),enabled=1");$q->execute([$uid,$sid,$hid?:null,$entity,trim((string)($_POST['label']??'')),$metric]);$notice='Entita byla přiřazena k ubikaci.';}
if($action==='sync'){$sid=(int)$_POST['source_id'];$q=$pdo->prepare('SELECT * FROM wp_ir2_habitat_sources_15 WHERE user_id=? AND id=?');$q->execute([$uid,$sid]);$src=$q->fetch();if(!$src)throw new RuntimeException('Zdroj nebyl nalezen.');$token=ir_habitat_secret_decrypt((string)$src['token_enc']);if($token==='')throw new RuntimeException('Token konektoru nelze dešifrovat. Ulož zdroj znovu.');$states=ir_habitat_request((string)$src['base_url'],$token,'/api/states');$map=[];foreach($states as $st)if(isset($st['entity_id']))$map[(string)$st['entity_id']]=$st;$q=$pdo->prepare('SELECT * FROM wp_ir2_habitat_sensor_bindings_15 WHERE user_id=? AND source_id=? AND enabled=1');$q->execute([$uid,$sid]);$upd=$pdo->prepare('UPDATE wp_ir2_habitat_sensor_bindings_15 SET last_value=?,unit=?,last_seen=NOW() WHERE id=? AND user_id=?');foreach($q->fetchAll()?:[] as $b){$st=$map[$b['entity_id']]??null;if(!$st)continue;$upd->execute([(string)($st['state']??''),(string)($st['attributes']['unit_of_measurement']??''),(int)$b['id'],$uid]);}$pdo->prepare('UPDATE wp_ir2_habitat_sources_15 SET last_sync=NOW(),last_error=NULL WHERE id=? AND user_id=?')->execute([$sid,$uid]);$notice='Hodnoty senzorů byly synchronizovány.';}}
catch(Throwable $e){$error=$e->getMessage();}
$sources=[];$bindings=[];$habitats=[];try{$q=$pdo->prepare('SELECT * FROM wp_ir2_habitat_sources_15 WHERE user_id=? ORDER BY id');$q->execute([$uid]);$sources=$q->fetchAll()?:[];$q=$pdo->prepare('SELECT b.*,u.nazev habitat_name,s.name source_name FROM wp_ir2_habitat_sensor_bindings_15 b LEFT JOIN wp_ir2_ubikace u ON u.id=b.habitat_id AND u.user_id=b.user_id JOIN wp_ir2_habitat_sources_15 s ON s.id=b.source_id AND s.user_id=b.user_id WHERE b.user_id=? ORDER BY u.nazev,b.metric');$q->execute([$uid]);$bindings=$q->fetchAll()?:[];$q=$pdo->prepare('SELECT id,nazev FROM wp_ir2_ubikace WHERE user_id=? ORDER BY nazev');$q->execute([$uid]);$habitats=$q->fetchAll()?:[];}catch(Throwable $e){}
ir_page_start('Home Assistant','habitat');echo ir_back('habitat-studio.php?mode=room','Habitat Studio');
?>
<section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">HABITAT STUDIO · CONNECTORS</span><h2>Home Assistant</h2></div></header><p class="module-intro">Připojení používá Home Assistant REST API a Long-Lived Access Token. Senzory se mapují přímo na skutečné ubikace, takže teplota/vlhkost nejsou vedlejší evidence.</p><?php if($notice):?><div class="flash success"><?=ir_e($notice)?></div><?php endif;if($error):?><div class="flash danger"><?=ir_e($error)?></div><?php endif;?></section>
<div class="ha15-grid"><section class="panel glow-panel"><header class="panel-head"><h3>Připojit zdroj</h3></header><form method="post" class="ha15-form"><?=ir_csrf_field()?><input type="hidden" name="action" value="save_source"><label>Název<input name="name" value="Home Assistant"></label><label>URL<input name="base_url" placeholder="https://homeassistant.example.cz"></label><label>Long-Lived Access Token<input name="token" type="password" autocomplete="new-password"></label><button class="btn primary">Ověřit a připojit</button></form></section>
<section class="panel glow-panel"><header class="panel-head"><h3>Zdroje</h3></header><div class="ha15-list"><?php foreach($sources as $s):?><article><?=ir_visual_icon('automation')?><div><strong><?=ir_e($s['name'])?></strong><small><?=ir_e($s['base_url'])?> · poslední sync <?=ir_e((string)($s['last_sync']?:'—'))?></small></div><form method="post"><?=ir_csrf_field()?><input type="hidden" name="action" value="sync"><input type="hidden" name="source_id" value="<?=(int)$s['id']?>"><button class="btn tiny">Synchronizovat</button></form><form method="post" onsubmit="return confirm('Odebrat zdroj a jeho vazby?')"><?=ir_csrf_field()?><input type="hidden" name="action" value="delete_source"><input type="hidden" name="source_id" value="<?=(int)$s['id']?>"><button class="btn tiny danger">Odebrat</button></form></article><?php endforeach;if(!$sources):?><div class="empty-state">Zatím není připojen žádný zdroj.</div><?php endif;?></div></section></div>
<section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">SENZORY / ENTITY</span><h3>Mapování na ubikace</h3></div></header><form method="post" class="ha15-bind"><?=ir_csrf_field()?><input type="hidden" name="action" value="bind"><select name="source_id" required><option value="">Zdroj…</option><?php foreach($sources as $s):?><option value="<?=(int)$s['id']?>"><?=ir_e($s['name'])?></option><?php endforeach;?></select><input name="entity_id" placeholder="sensor.terrarium_01_temperature" required><select name="habitat_id"><option value="0">Bez ubikace</option><?php foreach($habitats as $h):?><option value="<?=(int)$h['id']?>"><?=ir_e($h['nazev'])?></option><?php endforeach;?></select><select name="metric"><option value="temperature">Teplota</option><option value="humidity">Vlhkost</option><option value="water">Voda</option><option value="switch">Spínač / stav</option><option value="other">Jiné</option></select><input name="label" placeholder="Popisek"><button class="btn primary">Přiřadit</button></form><div class="ha15-sensors"><?php foreach($bindings as $b):?><article><span><?=ir_visual_icon($b['metric']==='humidity'?'humidity':($b['metric']==='temperature'?'temperature':'automation'))?></span><div><strong><?=ir_e($b['label']?:$b['entity_id'])?></strong><small><?=ir_e($b['habitat_name']?:'Bez ubikace')?> · <?=ir_e($b['entity_id'])?></small></div><b><?=ir_e((string)($b['last_value']??'—'))?> <?=ir_e((string)($b['unit']??''))?></b></article><?php endforeach;?></div></section>
<?php ir_page_end();
