<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';
$uid=ir_current_user_id();
try{$pdo->exec("CREATE TABLE IF NOT EXISTS wp_ir2_zdravi (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,zvire_id BIGINT UNSIGNED NOT NULL,typ_zaznamu VARCHAR(100) NOT NULL DEFAULT 'Preventivní kontrola',status VARCHAR(60) NOT NULL DEFAULT 'Aktivní řešení',datum_od DATE NULL,datum_do DATE NULL,veterinar VARCHAR(190) NULL,priznaky TEXT NULL,diagnoza TEXT NULL,lecba TEXT NULL,lek VARCHAR(190) NULL,davkovani VARCHAR(190) NULL,poznamka TEXT NULL,vytvoreno TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id),INDEX(zvire_id),INDEX(datum_do)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}catch(Throwable $e){}
if($_SERVER['REQUEST_METHOD']==='POST'){ir_verify_csrf();$op=(string)($_POST['op']??'');try{if($op==='save'){$aid=ir_int($_POST['zvire_id']??0);if(!$aid||!ir_animal($pdo,$uid,$aid))throw new RuntimeException('Vyber platné zvíře.');$pdo->prepare("INSERT INTO wp_ir2_zdravi(user_id,zvire_id,typ_zaznamu,status,datum_od,datum_do,veterinar,priznaky,diagnoza,lecba,lek,davkovani,poznamka) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)")->execute([$uid,$aid,trim((string)$_POST['typ']),trim((string)$_POST['status']),$_POST['datum_od']?:date('Y-m-d'),$_POST['datum_do']?:null,trim((string)$_POST['veterinar']),trim((string)$_POST['priznaky']),trim((string)$_POST['diagnoza']),trim((string)$_POST['lecba']),trim((string)$_POST['lek']),trim((string)$_POST['davkovani']),trim((string)$_POST['poznamka'])]);$detail=trim((string)$_POST['diagnoza']);ir_log_activity($pdo,$uid,$aid,'Zdravotní kontrola',($_POST['datum_od']?:date('Y-m-d')).'T12:00',trim((string)$_POST['typ']),$detail);ir_sync_health_tasks($pdo,$uid);ir_redirect('health.php');}if($op==='close'){$id=ir_int($_POST['id']??0);$pdo->prepare("UPDATE wp_ir2_zdravi SET status='Ukončeno' WHERE id=? AND user_id=?")->execute([$id,$uid]);ir_sync_health_tasks($pdo,$uid);ir_redirect('health.php');}}catch(Throwable $e){error_log('IR action: '.$e->getMessage());$error=$e instanceof PDOException?'Změnu se nepodařilo uložit. Zkus to znovu.':$e->getMessage();}}
$animals=[];$rows=[];try{$q=$pdo->prepare("SELECT id,jmeno_kod,latinsky_nazev FROM wp_ir2_zvirata z WHERE user_id=? AND ".ir_status_active_sql('z')." ORDER BY latinsky_nazev,jmeno_kod");$q->execute([$uid]);$animals=$q->fetchAll()?:[];$q=$pdo->prepare("SELECT h.*,z.jmeno_kod,z.latinsky_nazev FROM wp_ir2_zdravi h LEFT JOIN wp_ir2_zvirata z ON z.id=h.zvire_id AND z.user_id=h.user_id WHERE h.user_id=? ORDER BY COALESCE(h.datum_od,DATE(h.vytvoreno)) DESC,h.id DESC LIMIT 150");$q->execute([$uid]);$rows=$q->fetchAll()?:[];}catch(Throwable $e){}
$active=count(array_filter($rows,fn($r)=>(string)$r['status']!=='Ukončeno'));$follow=count(array_filter($rows,fn($r)=>(string)$r['status']!=='Ukončeno'&&!empty($r['datum_do'])));$overdue=count(array_filter($rows,fn($r)=>(string)$r['status']!=='Ukončeno'&&!empty($r['datum_do'])&&(string)$r['datum_do']<date('Y-m-d')));$serious=count(array_filter($rows,static fn($r)=>!in_array((string)$r['status'],['Ukončeno'],true)&&(bool)preg_match('~(léčba|úraz|medikace|akut|karant)~iu',(string)($r['typ_zaznamu'].' '.$r['status']))));
ir_page_start('Zdraví','care');echo ir_back('index.php','Přehled');if(!empty($error))echo '<div class="flash danger">'.ir_e($error).'</div>';
?>
<section class="metric-grid health-kpis"><article class="mini-metric glow-panel"><span><?=ir_visual_icon('health')?></span><div><small>Aktivní řešení</small><strong><?=$active?></strong><em>léčba / sledování</em></div></article><article class="mini-metric glow-panel <?=$serious?'is-alert':''?>"><span><?=ir_visual_icon($serious?'warning':'status-ok')?></span><div><small>Závažnější upozornění</small><strong><?=$serious?></strong><em><?=$serious?'vyžaduje pozornost':'bez akutního záznamu'?></em></div></article><article class="mini-metric glow-panel <?=$overdue?'is-alert':''?>"><span><?=ir_visual_icon('calendar')?></span><div><small>Kontroly po termínu</small><strong><?=$overdue?></strong><em>zkontrolovat dnes</em></div></article><a class="mini-metric glow-panel" href="tasks.php"><span><?=ir_visual_icon('tasks')?></span><div><small>Planner zdraví</small><strong><?=ir_scalar($pdo,"SELECT COUNT(*) FROM wp_ir2_planovac WHERE user_id=? AND stav='Aktivní' AND kategorie='Zdraví'",[$uid],0)?></strong><em>synchronizováno</em></div></a></section>
<div class="dashboard-main-2col"><section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">ZDRAVOTNÍ HISTORIE</span><h2>Zdravotní evidence</h2></div></header><div class="dashboard-list"><?php foreach($rows as $r):?><div class="dashboard-list-row"><span><?=ir_visual_icon((string)$r['status']==='Ukončeno'?'check':'health')?></span><div><strong><?=ir_e((string)$r['typ_zaznamu'])?> · <?=ir_e((string)($r['latinsky_nazev']?:$r['jmeno_kod']))?></strong><small><?=ir_e((string)($r['diagnoza']?:$r['priznaky']?:$r['lecba']?:'Bez detailu'))?></small></div><time><?=ir_e((string)$r['datum_od'])?></time><?php if((string)$r['status']!=='Ukončeno'):?><form method="post"><?=ir_csrf_field()?><input type="hidden" name="op" value="close"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn tiny">Ukončit</button></form><?php endif;?></div><?php endforeach;if(!$rows):?><div class="empty-state small">Bez zdravotních záznamů.</div><?php endif;?></div></section>
<form class="panel glow-panel form-panel" method="post"><?=ir_csrf_field()?><input type="hidden" name="op" value="save"><header class="panel-head"><div><span class="panel-kicker">NOVÝ ZÁZNAM</span><h2>Léčba / kontrola</h2></div><button class="btn primary">Uložit</button></header><div class="form-grid cols-2"><label>Zvíře<select name="zvire_id" required><option value="">Vyber</option><?php foreach($animals as $a):?><option value="<?=$a['id']?>"><?=ir_e((string)($a['latinsky_nazev']?:$a['jmeno_kod']))?> · <?=ir_e((string)$a['jmeno_kod'])?></option><?php endforeach;?></select></label><label>Typ<select name="typ"><option>Preventivní kontrola</option><option>Léčba</option><option>Úraz</option><option>Karanténa</option><option>Medikace</option></select></label><label>Stav<select name="status"><option>Aktivní řešení</option><option>Sledování</option><option>Ukončeno</option></select></label><label>Datum<input type="date" name="datum_od" value="<?=date('Y-m-d')?>"></label><label>Kontrola / do<input type="date" name="datum_do"></label><label>Veterinář<input name="veterinar"></label><label>Příznaky<textarea name="priznaky"></textarea></label><label>Diagnóza<textarea name="diagnoza"></textarea></label><label>Léčba<textarea name="lecba"></textarea></label><label>Lék / dávkování<input name="lek" placeholder="Lék"><input name="davkovani" placeholder="Dávkování"></label><label class="span-2">Poznámka<textarea name="poznamka"></textarea></label></div></form></div>
<?php ir_page_end();
