<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';
$uid=ir_current_user_id();$error='';
$extended=ir_table_exists($pdo,'wp_ir2_inventory_details')&&ir_table_exists($pdo,'wp_ir2_inventory_categories');
$shoppingReady=ir_table_exists($pdo,'wp_ir2_nakupni_list');
$tab=preg_replace('/[^a-z\-]/','',(string)($_GET['tab']??'overview'));
if(!in_array($tab,['overview','items','shopping','calculator','categories'],true))$tab='overview';
function stock_number(string $key): string {$value=str_replace(',', '.',trim((string)($_POST[$key]??'0')));if(!preg_match('/^\d{1,9}(?:\.\d{1,2})?$/D',$value))throw new InvalidArgumentException('Číslo musí být nezáporné, nejvýše se dvěma desetinnými místy.');return $value;}

if($_SERVER['REQUEST_METHOD']==='POST'){
    ir_verify_csrf();$action=(string)($_POST['action']??'');$id=ir_int($_POST['id']??0);
    try{
        $pdo->beginTransaction();
        if($action==='save'){
            $name=trim((string)($_POST['nazev']??''));$category=trim((string)($_POST['kategorie']??''));
            if($name===''||mb_strlen($name)>180||$category===''||mb_strlen($category)>100)throw new InvalidArgumentException('Vyplň platný název a vlastní kategorii skladu.');
            if($id&&!ir_action_owned($pdo,'wp_ir2_sklad',$uid,$id))throw new InvalidArgumentException('Položka nebyla nalezena.');
            $expiry=(string)($_POST['expirace']??'');if($expiry!==''&&(!preg_match('/^\d{4}-\d{2}-\d{2}$/D',$expiry)||date('Y-m-d',strtotime($expiry))!==$expiry))throw new InvalidArgumentException('Neplatná expirace.');
            $vals=[$name,$category,stock_number('mnozstvi'),trim((string)($_POST['jednotka']??'ks'))?:'ks',stock_number('minimum'),$expiry?:null,trim((string)($_POST['poznamka']??'')),$uid];
            if($id)$pdo->prepare('UPDATE wp_ir2_sklad SET nazev=?,kategorie=?,mnozstvi=?,jednotka=?,minimum=?,expirace=?,poznamka=? WHERE user_id=? AND id=?')->execute([...$vals,$id]);
            else{$pdo->prepare('INSERT INTO wp_ir2_sklad(nazev,kategorie,mnozstvi,jednotka,minimum,expirace,poznamka,user_id) VALUES(?,?,?,?,?,?,?,?)')->execute($vals);$id=(int)$pdo->lastInsertId();}
            if($extended){$v=[$uid,$id];foreach(['variant','size_label','weight_class'] as $key)$v[]=mb_substr(trim((string)($_POST[$key]??'')),0,100);$v[]=stock_number('purchase_price');$v[]=stock_number('sale_price');$v[]=mb_substr(trim((string)($_POST['supplier']??'')),0,190);$v[]=($_POST['purchased_on']??'')?:null;$v[]=mb_substr(trim((string)($_POST['storage_place']??'')),0,190);$pdo->prepare('INSERT INTO wp_ir2_inventory_details(user_id,item_id,variant,size_label,weight_class,purchase_price,sale_price,supplier,purchased_on,storage_place) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE variant=VALUES(variant),size_label=VALUES(size_label),weight_class=VALUES(weight_class),purchase_price=VALUES(purchase_price),sale_price=VALUES(sale_price),supplier=VALUES(supplier),purchased_on=VALUES(purchased_on),storage_place=VALUES(storage_place)')->execute($v);}
        }elseif($action==='delete'){
            $q=$pdo->prepare('SELECT mnozstvi FROM wp_ir2_sklad WHERE user_id=? AND id=? FOR UPDATE');$q->execute([$uid,$id]);$qty=$q->fetchColumn();if($qty===false||(float)$qty!==0.0)throw new InvalidArgumentException('Smazat lze pouze existující položku s nulovou zásobou.');
            if($extended)$pdo->prepare('DELETE FROM wp_ir2_inventory_details WHERE user_id=? AND item_id=?')->execute([$uid,$id]);$pdo->prepare('DELETE FROM wp_ir2_sklad WHERE user_id=? AND id=?')->execute([$uid,$id]);
        }elseif($extended&&$action==='category-adopt'){
            $name=trim((string)($_POST['name']??''));if($name==='')throw new InvalidArgumentException('Chybí název kategorie.');
            $exists=(int)ir_scalar($pdo,'SELECT COUNT(*) FROM wp_ir2_inventory_categories WHERE user_id=? AND name=?',[$uid,$name],0);if(!$exists)$pdo->prepare('INSERT INTO wp_ir2_inventory_categories(user_id,name,icon,position) VALUES(?,?,?,?)')->execute([$uid,$name,'inventory',500]);
        }elseif($extended&&in_array($action,['category-save','category-delete'],true)){
            $q=$pdo->prepare('SELECT name FROM wp_ir2_inventory_categories WHERE user_id=? AND id=? FOR UPDATE');$q->execute([$uid,$id]);$old=$q->fetchColumn();if($id&&!$old)throw new InvalidArgumentException('Kategorie nebyla nalezena.');
            if($action==='category-delete'){$q=$pdo->prepare('SELECT COUNT(*) FROM wp_ir2_sklad WHERE user_id=? AND kategorie=?');$q->execute([$uid,$old]);if((int)$q->fetchColumn()>0)throw new InvalidArgumentException('Kategorie obsahuje položky. Nejdřív je přesuň nebo přejmenuj.');$pdo->prepare('DELETE FROM wp_ir2_inventory_categories WHERE user_id=? AND id=?')->execute([$uid,$id]);}
            else{$name=trim((string)($_POST['name']??''));if($name===''||mb_strlen($name)>100)throw new InvalidArgumentException('Zvol název kategorie.');$icon=in_array($_POST['icon']??'',['inventory','feeding','medicine','habitat','supplement','water','cleaning','health','reproduction'],true)?$_POST['icon']:'inventory';$position=max(0,min(999,(int)($_POST['position']??0)));$dup=(int)ir_scalar($pdo,'SELECT COUNT(*) FROM wp_ir2_inventory_categories WHERE user_id=? AND name=? AND id<>?',[$uid,$name,$id],0);if($dup)throw new InvalidArgumentException('Kategorie s tímto názvem už existuje.');if($id){$pdo->prepare('UPDATE wp_ir2_inventory_categories SET name=?,icon=?,position=? WHERE user_id=? AND id=?')->execute([$name,$icon,$position,$uid,$id]);$pdo->prepare('UPDATE wp_ir2_sklad SET kategorie=? WHERE user_id=? AND kategorie=?')->execute([$name,$uid,$old]);}else $pdo->prepare('INSERT INTO wp_ir2_inventory_categories(user_id,name,icon,position) VALUES(?,?,?,?)')->execute([$uid,$name,$icon,$position]);}
        }elseif($shoppingReady&&$action==='shopping-add'){$name=trim((string)($_POST['shopping_name']??''));if($name==='')throw new InvalidArgumentException('Zadej položku nákupního listu.');$qty=mb_substr(trim((string)($_POST['shopping_qty']??'')),0,80);$priority=in_array((string)($_POST['shopping_priority']??''),['Nízká','Normální','Vysoká'],true)?(string)$_POST['shopping_priority']:'Normální';$pdo->prepare('INSERT INTO wp_ir2_nakupni_list(user_id,nazev,mnozstvi,priorita) VALUES(?,?,?,?)')->execute([$uid,mb_substr($name,0,190),$qty?:null,$priority]);
        }elseif($shoppingReady&&$action==='shopping-toggle')$pdo->prepare('UPDATE wp_ir2_nakupni_list SET hotovo=1-hotovo,completed_at=CASE WHEN hotovo=0 THEN NOW() ELSE NULL END WHERE user_id=? AND id=?')->execute([$uid,$id]);
        elseif($shoppingReady&&$action==='shopping-delete')$pdo->prepare('DELETE FROM wp_ir2_nakupni_list WHERE user_id=? AND id=?')->execute([$uid,$id]);
        else throw new InvalidArgumentException('Neplatná akce.');
        $pdo->commit();
        $retTab=(string)($_POST['return_tab']??($action==='save'?'items':($action==='shopping-add'||str_starts_with($action,'shopping-')?'shopping':(str_starts_with($action,'category-')?'categories':$tab))));
        ir_redirect('inventory.php?tab='.rawurlencode($retTab));
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Inventory: '.$e->getMessage());$error=$e instanceof InvalidArgumentException?$e->getMessage():'Změnu se nepodařilo uložit.';}
}

$q=$pdo->prepare($extended?'SELECT s.*,d.variant,d.size_label,d.weight_class,d.purchase_price,d.sale_price,d.supplier,d.purchased_on,d.storage_place FROM wp_ir2_sklad s LEFT JOIN wp_ir2_inventory_details d ON d.user_id=s.user_id AND d.item_id=s.id WHERE s.user_id=? ORDER BY s.kategorie,s.nazev':'SELECT * FROM wp_ir2_sklad WHERE user_id=? ORDER BY kategorie,nazev');$q->execute([$uid]);$items=$q->fetchAll()?:[];
$custom=[];if($extended){$q=$pdo->prepare('SELECT * FROM wp_ir2_inventory_categories WHERE user_id=? ORDER BY position,name');$q->execute([$uid]);$custom=$q->fetchAll()?:[];}
$shopping=[];if($shoppingReady){$q=$pdo->prepare('SELECT * FROM wp_ir2_nakupni_list WHERE user_id=? ORDER BY hotovo,FIELD(priorita,\'Vysoká\',\'Normální\',\'Nízká\'),created_at DESC');$q->execute([$uid]);$shopping=$q->fetchAll()?:[];}
$categories=array_values(array_unique(array_filter(array_merge(array_column($custom,'name'),array_column($items,'kategorie')))));sort($categories,SORT_NATURAL|SORT_FLAG_CASE);
$category=(string)($_GET['category']??'');$view=(string)($_GET['view']??'');$search=trim((string)($_GET['q']??''));$edit=null;foreach($items as $i)if((int)$i['id']===(int)($_GET['edit']??0))$edit=$i;
$filtered=array_values(array_filter($items,fn($i)=>($category===''||$i['kategorie']===$category)&&($view!=='low'||(float)$i['mnozstvi']<=(float)$i['minimum'])&&($search===''||mb_stripos($i['nazev'].' '.($i['variant']??''),$search)!==false)));
$low=array_values(array_filter($items,fn($i)=>(float)$i['mnozstvi']<=(float)$i['minimum']));$expiring=array_values(array_filter($items,fn($i)=>!empty($i['expirace'])&&strtotime((string)$i['expirace'])<=strtotime('+30 days')));
$stockValue=0.0;foreach($items as $i)$stockValue+=(float)$i['mnozstvi']*(float)($i['purchase_price']??0);
$customMap=[];foreach($custom as $c)$customMap[(string)$c['name']]=$c;
$iconFor=function(string $cat)use($customMap):string{if(isset($customMap[$cat]))return (string)$customMap[$cat]['icon'];$l=mb_strtolower($cat,'UTF-8');if(str_contains($l,'krm')||str_contains($l,'myš')||str_contains($l,'hmyz'))return 'feeding';if(str_contains($l,'vit')||str_contains($l,'supl'))return 'supplement';if(str_contains($l,'veter')||str_contains($l,'léč'))return 'medicine';if(str_contains($l,'substr')||str_contains($l,'vybav')||str_contains($l,'technik'))return 'habitat';return 'inventory';};

ir_page_start('Sklad','inventory');if($error)echo '<p class="flash danger" role="alert">'.ir_e($error).'</p>';
?>
<nav class="module-tabs inventory-tabs" aria-label="Skladové sekce">
 <a class="<?=$tab==='overview'?'is-active':''?>" href="inventory.php?tab=overview">Přehled</a>
 <a class="<?=$tab==='items'?'is-active':''?>" href="inventory.php?tab=items">Položky</a>
 <a class="<?=$tab==='shopping'?'is-active':''?>" href="inventory.php?tab=shopping">Nákupní list</a>
 <a class="<?=$tab==='calculator'?'is-active':''?>" href="inventory.php?tab=calculator">Kalkulace</a>
 <a class="<?=$tab==='categories'?'is-active':''?>" href="inventory.php?tab=categories">Kategorie</a>
</nav>

<section class="metric-grid inventory-metrics">
 <article class="mini-metric glow-panel"><span><?=ir_visual_icon('inventory')?></span><div><small>Položky</small><strong><?=count($items)?></strong><em>celkem</em></div></article>
 <article class="mini-metric glow-panel"><span><?=ir_visual_icon('warning')?></span><div><small>Nízké zásoby</small><strong><?=count($low)?></strong><em>k dokoupení</em></div></article>
 <article class="mini-metric glow-panel"><span><?=ir_visual_icon('calendar')?></span><div><small>Expirace do 30 dní</small><strong><?=count($expiring)?></strong><em>zkontrolovat</em></div></article>
 <article class="mini-metric glow-panel"><span><?=ir_visual_icon('finance')?></span><div><small>Hodnota zásob</small><strong><?=number_format($stockValue,0,',',' ')?> Kč</strong><em>pořizovací ceny</em></div></article>
</section>

<?php if($tab==='overview'):?>
<section class="inventory-overview-layout">
 <section class="panel glow-panel inventory-custom-space">
  <header class="panel-head"><div><span class="panel-kicker">MOJE SKLADOVÉ SEKCE</span><h2>Uspořádej sklad podle svého provozu</h2></div><a class="btn primary" href="inventory.php?tab=categories">+ Nová kategorie</a></header>
  <div class="inventory-category-grid inventory-category-grid--custom">
   <?php foreach($categories as $cat):$catItems=array_values(array_filter($items,fn($i)=>$i['kategorie']===$cat));$lowCount=count(array_filter($catItems,fn($i)=>(float)$i['mnozstvi']<=(float)$i['minimum']));?>
   <a class="inventory-block" href="inventory.php?tab=items&category=<?=rawurlencode($cat)?>"><span class="inventory-block-icon"><?=ir_visual_icon($iconFor($cat))?></span><span><strong><?=ir_e($cat)?></strong><small><?=count($catItems)?> položek<?=$lowCount?' · '.$lowCount.' pod minimem':''?></small></span><b>›</b></a>
   <?php endforeach;?>
   <?php if(!$categories):?><a class="inventory-create-first" href="inventory.php?tab=categories"><?=ir_visual_icon('add')?><strong>Vytvořit první kategorii</strong><small>Mražené krmivo, živý hmyz, substráty, technika… názvy jsou jen na tobě.</small></a><?php endif;?>
  </div>
 </section>
 <aside class="panel glow-panel inventory-attention-panel"><header class="panel-head"><div><?=ir_visual_icon('warning')?><strong>Vyžaduje pozornost</strong></div><a href="inventory.php?tab=items&view=low">Vše →</a></header><div class="inventory-attention-list"><?php foreach(array_slice($low,0,7) as $i):?><a href="inventory.php?tab=items&edit=<?=$i['id']?>"><span><?=ir_visual_icon($iconFor((string)$i['kategorie']))?></span><div><strong><?=ir_e((string)$i['nazev'])?></strong><small><?=ir_e((string)$i['kategorie'])?></small></div><b><?=ir_e((string)$i['mnozstvi'].' '.(string)$i['jednotka'])?></b></a><?php endforeach;if(!$low):?><div class="empty-state small">Zásoby jsou nad nastavenými minimy.</div><?php endif;?></div></aside>
</section>
<?php elseif($tab==='items'):?>
<div class="module-toolbar inventory-toolbar"><form method="get"><input type="hidden" name="tab" value="items"><input type="search" name="q" placeholder="Hledat položku" value="<?=ir_e($search)?>"><select name="category"><option value="">Všechny kategorie</option><?php foreach($categories as $cat):?><option <?=$cat===$category?'selected':''?>><?=ir_e($cat)?></option><?php endforeach?></select><select name="view"><option value="">Všechny stavy</option><option value="low" <?=$view==='low'?'selected':''?>>Nízké zásoby</option></select><button class="btn">Filtrovat</button></form><a class="btn primary" href="inventory.php?tab=items&new=1#item-form">+ Přidat položku</a></div>
<section class="panel glow-panel inventory-items-panel"><header class="panel-head"><div><span class="panel-kicker">POLOŽKY</span><h2><?=ir_e($category?:($view==='low'?'Nízké zásoby':'Skladové položky'))?></h2></div><strong><?=count($filtered)?> záznamů</strong></header><div class="table-scroll"><table class="data-table"><thead><tr><th>Položka</th><th>Varianta</th><th>Počet</th><th>Nákup / ks</th><th>Prodej / ks</th><th>Hodnota</th><th>Minimum</th><th>Expirace</th><th>Akce</th></tr></thead><tbody><?php foreach($filtered as $i):?><tr><td><strong><?=ir_e((string)$i['nazev'])?></strong><small><?=ir_e((string)$i['kategorie'])?></small></td><td><?=ir_e(trim((string)($i['variant']??'').' '.(string)($i['size_label']??'').' '.(string)($i['weight_class']??''))?:'—')?></td><td><?=ir_e($i['mnozstvi'].' '.$i['jednotka'])?></td><td><?=number_format((float)($i['purchase_price']??0),2,',',' ')?></td><td><?=number_format((float)($i['sale_price']??0),2,',',' ')?></td><td><?=number_format((float)$i['mnozstvi']*(float)($i['purchase_price']??0),2,',',' ')?></td><td><?=ir_e((string)$i['minimum'])?></td><td><?=ir_e($i['expirace']??'—')?></td><td><div class="row-actions"><a href="inventory.php?tab=items&edit=<?=$i['id']?>#item-form">Upravit</a><?php if((float)$i['mnozstvi']===0.0):?><form method="post"><?=ir_csrf_field()?><input type="hidden" name="return_tab" value="items"><input type="hidden" name="id" value="<?=$i['id']?>"><button name="action" value="delete" onclick="return confirm('Smazat prázdnou skladovou položku?')">Smazat</button></form><?php endif?></div></td></tr><?php endforeach;if(!$filtered):?><tr><td colspan="9"><div class="table-empty">Žádné položky pro zvolený filtr.</div></td></tr><?php endif?></tbody></table></div></section>
<?php if($edit||isset($_GET['new'])):?><form id="item-form" class="panel glow-panel form-panel inventory-item-form" method="post"><?=ir_csrf_field()?><input type="hidden" name="return_tab" value="items"><input type="hidden" name="id" value="<?=$edit['id']??0?>"><input type="hidden" name="action" value="save"><header class="panel-head"><h2><?=$edit?'Upravit položku':'Nová položka'?></h2><div class="row-actions"><a class="btn secondary" href="inventory.php?tab=items">Zrušit</a><button class="btn primary">Uložit</button></div></header><div class="form-grid cols-3"><label>Název<input name="nazev" required maxlength="180" value="<?=ir_e($edit['nazev']??'')?>"></label><label>Kategorie<select name="kategorie" required><option value="">Vyber kategorii…</option><?php foreach($categories as $cat):?><option <?=$cat===($edit['kategorie']??$category)?'selected':''?>><?=ir_e($cat)?></option><?php endforeach?></select></label><label>Jednotka<input name="jednotka" value="<?=ir_e($edit['jednotka']??'ks')?>"></label><?php foreach(['mnozstvi'=>'Množství','minimum'=>'Minimální zásoba'] as $key=>$label):?><label><?=$label?><input type="number" name="<?=$key?>" step=".01" min="0" required value="<?=ir_e((string)($edit[$key]??0))?>"></label><?php endforeach?><label>Expirace<input type="date" name="expirace" value="<?=ir_e($edit['expirace']??'')?>"></label><label>Poznámka<input name="poznamka" value="<?=ir_e($edit['poznamka']??'')?>"></label></div><?php if($extended):?><details open><summary>Varianta, ceny a skladování</summary><div class="form-grid cols-3"><?php foreach(['variant'=>'Varianta','size_label'=>'Velikost','weight_class'=>'Váhová kategorie','supplier'=>'Dodavatel','storage_place'=>'Skladovací místo'] as $key=>$label):?><label><?=$label?><input name="<?=$key?>" value="<?=ir_e((string)($edit[$key]??''))?>"></label><?php endforeach;foreach(['purchase_price'=>'Pořizovací cena / jednotka','sale_price'=>'Prodejní cena / jednotka'] as $key=>$label):?><label><?=$label?><input type="number" step=".01" min="0" name="<?=$key?>" value="<?=ir_e((string)($edit[$key]??0))?>"></label><?php endforeach?><label>Datum nákupu<input type="date" name="purchased_on" value="<?=ir_e($edit['purchased_on']??'')?>"></label></div></details><?php endif?></form><?php endif;?>
<?php elseif($tab==='shopping'):?>
<section class="panel glow-panel shopping-list shopping-list-full"><header class="panel-head"><div><span class="panel-kicker">NÁKUPNÍ LIST</span><h2>Co dokoupit</h2></div><strong><?=count(array_filter($shopping,static fn($x)=>(int)$x['hotovo']===0))?> aktivních</strong></header><?php if($shoppingReady):?><form method="post" class="shopping-add-form"><?=ir_csrf_field()?><input type="hidden" name="return_tab" value="shopping"><input type="hidden" name="action" value="shopping-add"><input name="shopping_name" placeholder="Co koupit…" required><input name="shopping_qty" placeholder="Množství"><select name="shopping_priority"><option>Normální</option><option>Vysoká</option><option>Nízká</option></select><button class="btn primary">+ Přidat</button></form><?php endif;?><div class="shopping-list-rows"><?php foreach($shopping as $i):?><div class="shopping-manual-row <?=((int)$i['hotovo']?'is-done':'')?>"><form method="post"><?=ir_csrf_field()?><input type="hidden" name="return_tab" value="shopping"><input type="hidden" name="action" value="shopping-toggle"><input type="hidden" name="id" value="<?=$i['id']?>"><button class="shopping-check"><?=((int)$i['hotovo']?'✓':'○')?></button></form><span><strong><?=ir_e((string)$i['nazev'])?></strong><small><?=ir_e((string)($i['mnozstvi']?:'bez množství'))?> · <?=ir_e((string)$i['priorita'])?></small></span><form method="post"><?=ir_csrf_field()?><input type="hidden" name="return_tab" value="shopping"><input type="hidden" name="action" value="shopping-delete"><input type="hidden" name="id" value="<?=$i['id']?>"><button class="icon-action">×</button></form></div><?php endforeach;if(!$shopping):?><div class="empty-state">Nákupní list je prázdný.</div><?php endif;?></div></section>
<?php elseif($tab==='calculator'):?>
<section id="sale-calc" class="panel glow-panel inventory-calculator"><header class="panel-head"><div><span class="panel-kicker">KALKULACE</span><h2>Prodej krmiva / položek</h2><p>Samostatný pracovní nástroj, ne součást hlavního přehledu skladu.</p></div></header><div class="table-scroll"><table class="data-table"><thead><tr><th>Položka</th><th>Počet</th><th>Cena / ks</th><th>Mezisoučet</th><th>Akce</th></tr></thead><tbody data-sale-rows></tbody></table></div><div class="module-toolbar"><button class="btn" type="button" data-sale-add>+ Přidat řádek</button><button class="btn" type="button" data-sale-reset>Resetovat</button><strong>Celkem: <output data-sale-total>0,00 Kč</output></strong></div></section>
<?php elseif($tab==='categories'):?>
<section class="panel glow-panel inventory-category-manager"><header class="panel-head"><div><span class="panel-kicker">PŘIZPŮSOBENÍ</span><h2>Vlastní skladové kategorie</h2><p>Žádné povinné šablony. Sklad si rozděl přesně podle svého chovu.</p></div></header>
 <?php if(!$extended):?><div class="flash danger">Databáze ještě nemá tabulku vlastních kategorií.</div><?php else:?>
 <div class="category-manager-list">
  <?php foreach($categories as $name):$cat=$customMap[$name]??null;if($cat):?><form method="post" class="category-manager-row"><?=ir_csrf_field()?><input type="hidden" name="return_tab" value="categories"><input type="hidden" name="id" value="<?=$cat['id']?>"><input name="name" maxlength="100" value="<?=ir_e($cat['name'])?>"><select name="icon"><?php foreach(['inventory'=>'Sklad','feeding'=>'Krmivo','medicine'=>'Veterina','habitat'=>'Vybavení','supplement'=>'Suplementy','water'=>'Voda','cleaning'=>'Údržba','health'=>'Zdraví','reproduction'=>'Reprodukce'] as $icon=>$label):?><option value="<?=$icon?>" <?=$icon===$cat['icon']?'selected':''?>><?=$label?></option><?php endforeach?></select><input type="number" min="0" max="999" name="position" value="<?=$cat['position']?>"><button class="btn" name="action" value="category-save">Uložit</button><button class="btn danger" name="action" value="category-delete" onclick="return confirm('Smazat prázdnou kategorii?')">Smazat</button></form><?php else:?><form method="post" class="category-manager-row is-unmanaged"><?=ir_csrf_field()?><input type="hidden" name="return_tab" value="categories"><input type="hidden" name="name" value="<?=ir_e($name)?>"><span><?=ir_visual_icon($iconFor($name))?><strong><?=ir_e($name)?></strong><small>Existující kategorie z položek</small></span><button class="btn" name="action" value="category-adopt">Převzít do správy</button></form><?php endif;endforeach;?>
  <form method="post" class="category-manager-row is-new"><?=ir_csrf_field()?><input type="hidden" name="return_tab" value="categories"><input type="hidden" name="id" value="0"><input name="name" maxlength="100" placeholder="Např. Mražené myši" required><select name="icon"><option value="feeding">Krmivo</option><option value="inventory">Sklad</option><option value="supplement">Suplementy</option><option value="habitat">Vybavení</option><option value="medicine">Veterina</option><option value="water">Voda</option><option value="cleaning">Údržba</option></select><input type="number" min="0" max="999" name="position" value="100"><button class="btn primary" name="action" value="category-save">+ Vytvořit kategorii</button></form>
 </div><?php endif;?>
</section>
<?php endif;?>
<script type="application/json" id="sale-items"><?=json_encode(array_map(fn($i)=>['id'=>(int)$i['id'],'name'=>$i['nazev'],'price'=>(float)($i['sale_price']??0)],$items),JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?></script><script src="assets/js/inventory-calc.js?v=62"></script>
<?php ir_page_end();
