<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';
$uid=ir_current_user_id();$result=null;$issues=[];
if($_SERVER['REQUEST_METHOD']==='POST'){ir_verify_csrf();try{$result=ir_planner_brain_sync($pdo,$uid);ir_flash('success','Synchronizace hlavního mozku dokončena.');}catch(Throwable $e){$issues[]=$e->getMessage();}}
$stats=['active'=>0,'today'=>0,'upcoming'=>0,'overdue'=>0,'auto'=>0,'repro'=>0,'health'=>0];
try{$q=$pdo->prepare("SELECT COUNT(*) FROM wp_ir2_planovac WHERE user_id=? AND stav='Aktivní'");$q->execute([$uid]);$stats['active']=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT COUNT(*) FROM wp_ir2_planovac WHERE user_id=? AND stav='Aktivní' AND datum_termin=CURDATE()");$q->execute([$uid]);$stats['today']=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT COUNT(*) FROM wp_ir2_planovac WHERE user_id=? AND stav='Aktivní' AND datum_termin>CURDATE()");$q->execute([$uid]);$stats['upcoming']=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT COUNT(*) FROM wp_ir2_planovac WHERE user_id=? AND stav='Aktivní' AND datum_termin<CURDATE()");$q->execute([$uid]);$stats['overdue']=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT COUNT(*) FROM wp_ir2_planovac WHERE user_id=? AND stav='Aktivní' AND poznamka LIKE '[IR-%'");$q->execute([$uid]);$stats['auto']=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT COUNT(*) FROM wp_ir2_planovac WHERE user_id=? AND stav='Aktivní' AND poznamka LIKE '[IR-REPRO:%'");$q->execute([$uid]);$stats['repro']=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT COUNT(*) FROM wp_ir2_planovac WHERE user_id=? AND stav='Aktivní' AND poznamka LIKE '[IR-HEALTH:%'");$q->execute([$uid]);$stats['health']=(int)$q->fetchColumn();}catch(Throwable $e){$issues[]=$e->getMessage();}
ir_page_start('Synchronizace Plánovače','tasks');echo ir_back('tasks.php','Úkoly');?>
<section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">HLAVNÍ MOZEK</span><h2>Audit a synchronizace Plánovače</h2><p>Jedním během sjednotí krmení, suplementaci, reprodukci a zdravotní termíny do centrálního Plánovače.</p></div><form method="post"><?=ir_csrf_field()?><button class="btn primary">Spustit synchronizaci</button></form></header>
<div class="kpi-grid"><div class="kpi"><strong><?=$stats['active']?></strong><span>Aktivní úkoly</span></div><div class="kpi"><strong><?=$stats['today']?></strong><span>Dnes</span></div><div class="kpi"><strong><?=$stats['upcoming']?></strong><span>Nadcházející</span></div><div class="kpi"><strong><?=$stats['overdue']?></strong><span>Po termínu</span></div><div class="kpi"><strong><?=$stats['auto']?></strong><span>Automatické vazby</span></div><div class="kpi"><strong><?=$stats['repro']?></strong><span>Reprodukce</span></div><div class="kpi"><strong><?=$stats['health']?></strong><span>Zdraví</span></div></div>
<?php if($result):?><div class="simple-list"><div><strong>Krmení</strong><span><?=$result['feeding']?> karet přepočítáno</span></div><div><strong>Reprodukce</strong><span><?=$result['reproduction']?> cyklů synchronizováno</span></div><div><strong>Zdraví</strong><span><?=$result['health']?> aktivních kontrol</span></div><div><strong>Duplicitní automatické zdroje</strong><span><?=$result['duplicates']?></span></div><div><strong>Kolize termínů</strong><span><?=$result['conflicts']?> zvířat / dnů s více úkoly</span></div></div><?php endif;?>
<?php if($issues):?><div class="flash danger"><?=ir_e(implode(' · ',$issues))?></div><?php endif;?></section>
<section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">VAZBY</span><h2>Jednotná logika</h2></div></header><div class="simple-list"><div><strong>Krmení → suplementace → sklad → další termín</strong><span>Aktivita je zdroj skutečnosti; další krmení vzniká z posledního záznamu.</span></div><div><strong>Reprodukce → další fáze → Plánovač</strong><span>Každý aktivní cyklus má nejvýše jeden aktuální automatický úkol.</span></div><div><strong>Zdraví → kontrola léčby</strong><span>Neukončený zdravotní záznam s datem do vytváří kontrolní termín.</span></div><div><strong>Vlastní automatizace</strong><span>Pravidla po aktivitě vytvářejí úkol s unikátním markerem a neduplikují se.</span></div></div></section>
<?php ir_page_end();
