<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/reptile_core.php';
$uid=ir_current_user_id();$type=(string)($_GET['type']??'animal');$id=ir_int($_GET['id']??0);
function qr_html(string $payload,int $size=260,string $class='qr',string $alt='QR'): string { return '<span class="'.ir_e($class).' qr-local" style="width:'.$size.'px;max-width:100%;aspect-ratio:1/1" data-qr-render="'.ir_e($payload).'" role="img" aria-label="'.ir_e($alt).'"></span>'; }
function ir_qr_scan_payload(string $code): string { return IR_PUBLIC_URL.'/scan.php?code='.rawurlencode($code); }
function ir_action_qr(string $label,string $icon,string $payload,string $hint=''): void {
    echo '<article class="action-qr">'.qr_html($payload,190,'qr','QR '.$label).'<div><b>'.ir_e($icon).' '.ir_e($label).'</b>'.($hint!==''?'<small>'.ir_e($hint).'</small>':'').'</div></article>';
}
?><!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IR Manager · QR / dokument</title><style>.qr-local{display:inline-block;box-sizing:border-box}.qr-local svg{width:100%;height:auto;display:block}.label-code .qr-local{width:180px!important}
.qr-local{display:inline-block}.qr-local svg{width:100%;height:100%;display:block}
*{box-sizing:border-box}body{font:14px/1.35 Arial,sans-serif;color:#171717;margin:20px;background:#f2f2f2}.sheet{max-width:980px;margin:auto}.actions{display:flex;gap:8px;margin:0 0 14px}.actions button{padding:9px 14px;border:1px solid #444;border-radius:8px;background:#111;color:#fff;cursor:pointer}.card{background:#fff;border:1px solid #777;border-radius:14px;padding:20px;margin:0 0 16px;break-inside:avoid}.head{display:flex;justify-content:space-between;gap:22px;align-items:flex-start}.head h1{margin:0 0 5px;font-size:25px}.head p{margin:4px 0;color:#555}.qr{width:150px;height:150px;object-fit:contain}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px 22px;margin-top:16px}.grid div{border-bottom:1px solid #ddd;padding:7px 0}.grid small{display:block;color:#777}.history{width:100%;border-collapse:collapse;margin-top:18px}.history td,.history th{border-bottom:1px solid #ddd;padding:7px;text-align:left}.label-card{padding:14px}.label-main{display:grid;grid-template-columns:minmax(0,1fr) 150px;gap:16px;align-items:center}.label-title{display:flex;align-items:center;gap:12px}.label-photo{width:118px;aspect-ratio:16/9;border-radius:9px;border:1px solid #aaa;background:#111;object-fit:contain}.label-title h1{font-size:22px;margin:0}.label-title strong{display:block;font-size:15px}.label-title small{display:block;color:#666;margin-top:3px}.label-code{text-align:center}.label-code img{width:140px;height:140px}.label-code b{display:block;font-size:11px}.action-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:14px;padding-top:13px;border-top:2px solid #222}.action-qr{border:1px solid #aaa;border-radius:10px;padding:7px;text-align:center;break-inside:avoid}.action-qr img{width:100%;max-width:120px;aspect-ratio:1;object-fit:contain}.action-qr b{display:block;font-size:11px}.action-qr small{display:block;font-size:9px;color:#666;margin-top:2px}.label-note{font-size:10px;color:#666;margin:10px 0 0}.bulk-label{display:grid;grid-template-columns:minmax(0,1fr) 145px;gap:16px;align-items:center}.bulk-actions{grid-template-columns:repeat(3,1fr)}
@media(max-width:680px){.action-grid{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.label-main,.bulk-label{grid-template-columns:1fr}.label-code{text-align:left}}
@media print{body{margin:0;background:#fff}.actions{display:none}.sheet{max-width:none}.card{border-color:#555;box-shadow:none}.action-grid{gap:6px}.action-qr{padding:5px}}
</style></head><body><div class="sheet"><div class="actions"><button onclick="print()">Tisk / uložit PDF</button></div>
<?php if(in_array($type,['animal','label','sales'],true)):
$a=ir_animal($pdo,$uid,$id);if(!$a)exit('Nenalezeno.');$history=ir_activity_rows($pdo,$uid,['animal_id'=>$id],300);$detailPayload=ir_qr_scan_payload(ir_qr_payload($pdo,'animal',$uid,$id));$photo=function_exists('ir_asset_photo_url')?ir_asset_photo_url((string)($a['foto']??'')):'';
if($type==='label'):?>
<div class="card label-card">
 <div class="label-main">
  <div class="label-title"><?php if($photo):?><img class="label-photo" src="<?=ir_e($photo)?>" alt=""><?php endif;?><div><small>IR MANAGER · TERARISTIKA</small><h1><?=ir_e(ir_animal_display($a))?></h1><strong><?=ir_e((string)($a['animal_id']?:'IR-'.$id))?></strong><small><?=ir_e((string)($a['latinsky_nazev']?:$a['druh']))?> · <?=ir_e((string)($a['pohlavi']?:'—'))?></small></div></div>
  <div class="label-code"><?=qr_html($detailPayload,220,'qr','QR detail')?><b>DETAIL ZVÍŘETE</b></div>
 </div>
 <div class="action-grid">
  <?php ir_action_qr('Krmení','🍽',ir_qr_scan_payload(ir_qr_payload($pdo,'animal',$uid,$id).':FEED'),'sken → potvrdit → další'); ?>
  <?php ir_action_qr('Voda','💧',ir_qr_scan_payload(ir_qr_payload($pdo,'animal',$uid,$id).':WATER'),'rychlý zápis'); ?>
  <?php ir_action_qr('Úklid','🧹',ir_qr_scan_payload(ir_qr_payload($pdo,'animal',$uid,$id).':CLEAN'),'rychlý zápis'); ?>
  <?php ir_action_qr('Svlek','◉',ir_qr_scan_payload(ir_qr_payload($pdo,'animal',$uid,$id).':SHED'),'rychlý zápis'); ?>
 </div>
 <p class="label-note">Stejný kód lze zapsat i do NFC tagu. Akční QR otevře předvyplněný záznam konkrétního zvířete; stačí zkontrolovat a potvrdit.</p>
</div>
<?php else:?>
<div class="card"><div class="head"><div><h1><?=ir_e(ir_animal_display($a))?></h1><strong><?=ir_e((string)$a['jmeno_kod'])?> · <?=ir_e((string)($a['animal_id']?:'IR-'.$id))?></strong><p><?=ir_e((string)$a['pohlavi'])?> · <?=ir_e((string)$a['morf_linie'])?></p></div><?=qr_html($detailPayload,260,'qr','QR')?></div><div class="grid"><?php foreach(['Druh'=>$a['druh'],'Latinský název'=>$a['latinsky_nazev'],'Narození'=>$a['datum_narozeni'],'Původ'=>$a['puvod'],'CITES'=>$a['cites_cislo'],'Status'=>$a['status_chovu'],'Potrava'=>$a['potrava'],'Poznámka'=>$a['poznamka']] as $k=>$v):?><div><small><?=ir_e($k)?></small><?=ir_e((string)($v?:'—'))?></div><?php endforeach;?></div><?php if($type==='animal'):?><table class="history"><thead><tr><th>Datum</th><th>Aktivita</th><th>Hodnota</th><th>Detail</th></tr></thead><tbody><?php foreach($history as $r):?><tr><td><?=date('d.m.Y H:i',strtotime((string)$r['datum']))?></td><td><?=ir_e((string)$r['typ'])?></td><td><?=ir_e((string)$r['hodnota'])?></td><td><?=ir_e((string)$r['detail'])?></td></tr><?php endforeach;?></tbody></table><?php endif;?></div>
<?php endif;?>
<?php elseif($type==='rack'):$st=$pdo->prepare('SELECT * FROM wp_ir2_racky WHERE user_id=? AND id=?');$st->execute([$uid,$id]);$r=$st->fetch();if(!$r)exit('Nenalezeno.');$payload=ir_qr_scan_payload('IR:RACK:'.$id);?><div class="card"><div class="bulk-label"><div><h1><?=ir_e((string)$r['nazev'])?></h1><p><?=ir_e((string)$r['umisteni'])?> · <?=$r['pocet_radku']?>×<?=$r['pocet_sloupcu']?></p><strong>QR racku · hromadná péče</strong></div><?=qr_html($payload,260,'qr','QR')?></div><div class="action-grid bulk-actions"><?php ir_action_qr('Krmení','🍽',ir_qr_scan_payload('IR:RACK:'.$id.':FEED'));ir_action_qr('Voda','💧',ir_qr_scan_payload('IR:RACK:'.$id.':WATER'));ir_action_qr('Úklid','🧹',ir_qr_scan_payload('IR:RACK:'.$id.':CLEAN'));?></div></div>
<?php elseif($type==='cage'):$st=$pdo->prepare('SELECT * FROM wp_ir2_ubikace WHERE user_id=? AND id=?');$st->execute([$uid,$id]);$r=$st->fetch();if(!$r)exit('Nenalezeno.');$payload=ir_qr_scan_payload(ir_qr_payload($pdo,'enclosure',$uid,$id));?><div class="card"><div class="bulk-label"><div><h1><?=ir_e((string)$r['nazev'])?></h1><p><?=ir_e((string)$r['typ'])?> · <?=ir_e((string)$r['rozmery'])?></p><strong>QR ubikace · obyvatelé a rychlá péče</strong></div><?=qr_html($payload,260,'qr','QR')?></div><div class="action-grid bulk-actions"><?php ir_action_qr('Krmení','🍽',ir_qr_scan_payload(ir_qr_payload($pdo,'enclosure',$uid,$id).':FEED'));ir_action_qr('Voda','💧',ir_qr_scan_payload(ir_qr_payload($pdo,'enclosure',$uid,$id).':WATER'));ir_action_qr('Úklid','🧹',ir_qr_scan_payload(ir_qr_payload($pdo,'enclosure',$uid,$id).':CLEAN'));?></div></div>
<?php elseif($type==='clutch'):$st=$pdo->prepare('SELECT * FROM wp_ir2_snusky WHERE user_id=? AND id=?');$st->execute([$uid,$id]);$r=$st->fetch();if(!$r)exit('Nenalezeno.');$payload=IR_PUBLIC_URL.'/clutches.php?id='.$id;?><div class="card"><div class="head"><div><h1><?=ir_e((string)$r['nazev'])?></h1><p><?=ir_e((string)$r['stav'])?> · <?=ir_e((string)$r['datum_snusky'])?> · <?=ir_int($r['pocet_celkem'])?> ks</p></div><?=qr_html($payload,260,'qr','QR')?></div></div>
<?php elseif($type==='racks'):$st=$pdo->prepare('SELECT * FROM wp_ir2_racky WHERE user_id=? ORDER BY nazev');$st->execute([$uid]);foreach($st->fetchAll()?:[] as $r):$payload=ir_qr_scan_payload('IR:RACK:'.$r['id']);?><div class="card"><div class="head"><div><h1><?=ir_e((string)$r['nazev'])?></h1><p><?=ir_e((string)$r['umisteni'])?></p></div><?=qr_html($payload,260,'qr','QR')?></div></div><?php endforeach;endif;?>
</div><script src="assets/vendor/qr/qrcode.min.js"></script><script>document.querySelectorAll("[data-qr-render]").forEach(function(el){var q=qrcode(0,"M");q.addData(el.dataset.qrRender);q.make();el.innerHTML=q.createSvgTag({cellSize:4,margin:2,scalable:true});});</script></body></html>
