<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';
$uid=ir_current_user_id();$catalog=ir_activity_catalog_for_user($pdo,$uid);$presetType=trim((string)($_GET['type']??'Krmení'));$preset=trim((string)($_GET['preset']??''));$rackId=ir_int($_GET['rack_id']??0);$cageId=ir_int($_GET['cage_id']??0);$groupId=ir_int($_GET['group_id']??0);$animalId=ir_int($_GET['animal_id']??0);$fastMode=$animalId>0&&((string)($_GET['fast']??'')==='1');$preselect=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 ir_verify_csrf();$ids=array_values(array_filter(array_map('intval',(array)($_POST['animals']??[]))));$type=trim((string)($_POST['type']??'Krmení'));if($type==='Vlastní')$type=trim((string)($_POST['custom_type']??''));$date=(string)($_POST['date']??'');$value=trim((string)($_POST['value']??''));$detail=trim((string)($_POST['detail']??''));$refused=array_flip(array_map('intval',(array)($_POST['refused']??[])));
 if(!$ids)$error='Vyberte alespoň jedno zvíře.';elseif($type==='')$error='Vyberte typ aktivity.';else{try{
  $results=(array)($_POST['result']??[]);$feeding=in_array($type,['Krmení','Odmítnutí potravy','Nekrmeno'],true);$src=in_array((string)($_POST['source']??''),IR_EVENT_SOURCES,true)?(string)$_POST['source']:'quick';
  $items=[];foreach($ids as $aid){if($feeding){$r=(string)($results[$aid]??($type==='Odmítnutí potravy'?'refused':($type==='Nekrmeno'?'not_fed':'eaten')));if(isset($refused[$aid]))$r='refused';if(!isset(IR_FEED_RESULTS[$r]))$r='eaten';$items[]=['animal_id'=>$aid,'result'=>$r,'feed'=>$value,'note'=>$detail];}else $items[]=['animal_id'=>$aid,'type'=>$type,'value'=>$value,'note'=>$detail];}
  $out=ir_event_batch($pdo,$uid,$items,['source'=>$src,'performed_at'=>str_replace('T',' ',$date),'type'=>$feeding?'Krmení':$type,'allow_duplicate'=>!empty($_POST['allow_duplicate'])]);
  $count=count($out['ids']);ir_flash('success','Zapsáno '.$count.' '.($count===1?'záznam':($count<5?'záznamy':'záznamů')).($feeding?' · '.ir_batch_summary_text($out['summary']):'').'.');$returnTo=trim((string)($_POST['return_to']??''));if($returnTo!==''&&preg_match('~^(?:scan|quick|animal|animals|tasks|index)\.php(?:[?#].*)?$~',$returnTo))ir_redirect($returnTo);ir_redirect('activities.php');}catch(IrDuplicateEvent $d){$error=$d->getMessage().' Nic nebylo uloženo — pokud jde o další krmení téhož dne, zaškrtněte „Povolit opakovaný záznam“.';$dupShown=true;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('IR action: '.$e->getMessage());$error=$e instanceof PDOException?'Změnu se nepodařilo uložit. Zkus to znovu.':$e->getMessage();}}
}
$animals=[];try{$st=$pdo->prepare("SELECT z.id,z.jmeno_kod,z.latinsky_nazev,z.druh,z.pohlavi,z.foto,u.nazev ubikace_nazev FROM wp_ir2_zvirata z LEFT JOIN wp_ir2_ubikace u ON u.id=z.ubikace_id AND u.user_id=z.user_id WHERE z.user_id=? AND ".ir_status_active_sql('z')." AND COALESCE(z.pohlavi,'') NOT IN ('Skupina','Pár') ORDER BY COALESCE(z.latinsky_nazev,z.druh),z.jmeno_kod");$st->execute([$uid]);$animals=$st->fetchAll()?:[];}catch(Throwable){}
if($animalId>0){$preselect=[$animalId];}
elseif((int)($_GET['parent_id']??0)>0){$st=$pdo->prepare('SELECT id FROM wp_ir2_zvirata z WHERE user_id=? AND skupina_parent_id=? AND '.ir_status_active_sql('z'));$st->execute([$uid,(int)$_GET['parent_id']]);$preselect=array_map('intval',$st->fetchAll(PDO::FETCH_COLUMN));}
elseif($groupId){try{$st=$pdo->prepare("SELECT zvire_id FROM wp_ir2_skupiny_clenove WHERE user_id=? AND skupina_id=? AND datum_do IS NULL AND stav='Ve skupině'");$st->execute([$uid,$groupId]);$preselect=array_map('intval',array_column($st->fetchAll()?:[],'zvire_id'));}catch(Throwable){}}
elseif($rackId){try{$st=$pdo->prepare("SELECT z.id FROM wp_ir2_zvirata z JOIN wp_ir2_ubikace u ON u.id=z.ubikace_id AND u.user_id=z.user_id WHERE z.user_id=? AND u.rack_id=? AND ".ir_status_active_sql('z'));$st->execute([$uid,$rackId]);$preselect=array_map('intval',array_column($st->fetchAll()?:[],'id'));}catch(Throwable){}}
elseif($cageId){try{$st=$pdo->prepare("SELECT id FROM wp_ir2_zvirata z WHERE user_id=? AND ubikace_id=? AND ".ir_status_active_sql('z'));$st->execute([$uid,$cageId]);$preselect=array_map('intval',array_column($st->fetchAll()?:[],'id'));}catch(Throwable){}}elseif($preset==='needs-feed'){$preselect=array_map('intval',array_column(ir_needs_feed($pdo,$uid,500),'id'));}elseif($preset==='all'){$preselect=array_map('intval',array_column($animals,'id'));}
ir_page_start('Rychlý záznam','care');echo ir_back($fastMode?'scan.php':'index.php',$fastMode?'Další QR / NFC':'Zpět');if(!empty($error))echo '<div class="flash danger">'.ir_e($error).'</div>';
$fastAnimal=null;if($fastMode){foreach($animals as $row)if((int)$row['id']===$animalId){$fastAnimal=$row;break;}}
?>
<?php if($fastMode&&$fastAnimal):$fastPhoto=ir_asset_photo_url((string)($fastAnimal['foto']??''));?>
<form method="post" class="quick-scan-confirm panel glow-panel"><?=ir_csrf_field()?><input type="hidden" name="return_to" value="scan.php?ready=1"><input type="hidden" name="animals[]" value="<?=$animalId?>"><input type="hidden" name="type" value="<?=ir_e($presetType)?>"><input type="hidden" name="date" value="<?=ir_e(ir_datetime_input())?>">
 <div class="quick-scan-animal"><span class="quick-scan-photo"><?php if($fastPhoto):?><img src="<?=ir_e($fastPhoto)?>" alt=""><?php else:?><?=ir_visual_icon('animals')?><?php endif;?></span><span><small>QR / NFC · připraveno k zápisu</small><strong><?=ir_e((string)($fastAnimal['latinsky_nazev']?:$fastAnimal['druh']))?></strong><em><?=ir_e((string)$fastAnimal['jmeno_kod'])?> · <?=ir_e((string)($fastAnimal['ubikace_nazev']??'Bez ubikace'))?></em></span></div>
 <div class="quick-scan-action"><?=ir_visual_icon((string)(($catalog[$presetType]['icon']??ir_activity_icon_key('activity',$presetType))))?><span><small>Akce</small><strong><?=ir_e($presetType)?></strong></span></div>
 <div class="quick-scan-fields"><label>Hodnota / množství<input name="value" placeholder="volitelné · prázdné = výchozí z karty"></label><label>Poznámka<input name="detail" placeholder="volitelné"></label></div>
 <input type="hidden" name="source" value="<?=ir_e(in_array((string)($_GET['source']??''),IR_EVENT_SOURCES,true)?(string)$_GET['source']:'qr')?>">
 <?php if($presetType==='Krmení'):?><div class="b1-feed-results" style="margin:10px 0"><?php foreach(['eaten'=>['Snědlo','feeding','ok'],'refused'=>['Odmítlo','warning-action','warn'],'in_shed'=>['Ve svleku','shedding','info'],'not_fed'=>['Nekrmeno','reminder','muted']] as $rk=>[$rl,$ri,$rt]):?><button class="b1-res is-<?=$rt?>" name="result[<?=$animalId?>]" value="<?=$rk?>"><?=ir_visual_icon($ri)?><span><?=$rl?></span></button><?php endforeach;?></div><p class="muted" style="margin:0 0 8px">Klepnutím na výsledek se záznam rovnou uloží.</p><?php endif;?>
 <div class="quick-scan-buttons"><?php if($presetType!=='Krmení'):?><button class="btn primary quick-scan-save">✓ Zapsat a skenovat další</button><?php endif;?><a class="btn" href="animal.php?id=<?=$animalId?>">Karta zvířete</a></div>
</form>
<?php else:?>
<div class="quick-links-row"><a href="quick.php?type=Krmení&preset=needs-feed"><?=ir_visual_icon('feeding')?><strong>Krmení po termínu</strong></a><a href="quick.php?type=Výměna vody&preset=all"><?=ir_visual_icon('water')?><strong>Voda · vše</strong></a><a href="quick.php?type=Rosení&preset=all"><?=ir_visual_icon('mist')?><strong>Rosení · vše</strong></a><a href="quick.php?type=Čištění&preset=all"><?=ir_visual_icon('cleaning')?><strong>Čištění · vše</strong></a></div><form method="post" class="quick-layout"><?=ir_csrf_field()?>
<section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">RYCHLÁ PÉČE · HROMADNĚ</span><h2>Rychlý záznam</h2></div><button class="btn primary">Potvrdit a zapsat</button></header>
<div class="action-tile-grid"><?php foreach($catalog as $t=>$meta):?><label class="action-tile"><input type="radio" name="type" value="<?=ir_e($t)?>" <?=$t===$presetType?'checked':''?>><span><?=ir_visual_icon((string)$meta['icon'])?><b><?=ir_e($t)?></b></span></label><?php endforeach;?><label class="action-tile"><input type="radio" name="type" value="Vlastní"><span><?=ir_visual_icon('add')?><b>Vlastní</b></span></label></div>
<div class="form-grid cols-2 quick-fields"><label>Datum a čas<input type="datetime-local" name="date" value="<?=ir_e(ir_datetime_input())?>" required></label><label>Vlastní typ<input name="custom_type" placeholder="Použije se jen pro Vlastní"></label><label>Hodnota / krmivo / množství<input name="value" placeholder="volitelné přepsání pro celý výběr"><small class="field-help">U Krmení nech prázdné: každému zvířeti se použije jeho Typ krmení z karty a automaticky se přidá aktuální krok suplementační rotace.</small></label><label>Detail<input name="detail" placeholder="Poznámka, stav, dávka…"></label><label class="b1-check"><input type="checkbox" name="allow_duplicate" value="1" <?=!empty($dupShown)?'':''?>> Povolit opakovaný záznam téhož dne</label><input type="hidden" name="source" value="<?=ir_e(in_array((string)($_GET['source']??''),IR_EVENT_SOURCES,true)?(string)$_GET['source']:'quick')?>"></div></section>
<section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">VÝBĚR</span><h2>Jedinci</h2></div><div class="selection-count" data-selection-count>0 vybráno</div></header><div class="filter-bar"><input type="search" data-animal-filter placeholder="Hledat ID, jméno, druh, ubikaci…"><button type="button" class="btn tiny" data-select-all>Vybrat vše</button><button type="button" class="btn tiny" data-select-none>Zrušit</button></div><div class="select-animal-list" data-animal-list><?php foreach($animals as $a):$photo=ir_asset_photo_url((string)$a['foto']);?><label class="select-animal" data-filter-text="<?=ir_e(strtolower(implode(' ',[(string)$a['jmeno_kod'],(string)$a['latinsky_nazev'],(string)$a['druh'],(string)$a['ubikace_nazev']])) )?>"><input type="checkbox" name="animals[]" value="<?=$a['id']?>" <?=in_array((int)$a['id'],$preselect,true)?'checked':''?>><span class="select-photo"><?php if($photo):?><img src="<?=ir_e($photo)?>" alt=""><?php else:?><?=ir_visual_icon('animals')?><?php endif;?></span><span><strong><?=ir_e((string)$a['latinsky_nazev'])?></strong><small><?=ir_e((string)$a['jmeno_kod'])?> · <?=ir_e((string)($a['ubikace_nazev']??'Bez ubikace'))?></small></span><span class="quick-exception b1-qres" data-feed-only><select name="result[<?=(int)$a['id']?>]" aria-label="Výsledek krmení"><option value="eaten">Snědlo</option><option value="refused">Odmítlo</option><option value="in_shed">Ve svleku</option><option value="not_fed">Nekrmeno</option></select></span></label><?php endforeach;?></div></section>
</form>
<?php endif;?>
<script>addEventListener('DOMContentLoaded',()=>{const f=document.querySelector('form.quick-layout');if(!f)return;const sync=()=>{const t=f.querySelector('input[name=type]:checked')?.value||'';const on=['Krmení','Odmítnutí potravy','Nekrmeno'].includes(t);f.querySelectorAll('[data-feed-only]').forEach(x=>x.hidden=!on);};f.addEventListener('change',sync);sync();});</script>
<?php ir_page_end();
