<?php
declare(strict_types=1);
require __DIR__.'/includes/config.php';require __DIR__.'/includes/live.php';require __DIR__.'/includes/shell.php';require __DIR__.'/includes/reptile_core.php';
$uid=ir_current_user_id();
$species=[];$animals=[];
try{$st=$pdo->prepare('SELECT id,latinsky_nazev,cesky_nazev FROM wp_ir2_druhy WHERE user_id=? AND merged_into_id IS NULL ORDER BY latinsky_nazev');$st->execute([$uid]);$species=$st->fetchAll()?:[];$st=$pdo->prepare("SELECT id,jmeno_kod,latinsky_nazev,kategorie,druh_id FROM wp_ir2_zvirata WHERE user_id=? AND ".ir_status_active_sql('wp_ir2_zvirata')." ORDER BY COALESCE(NULLIF(latinsky_nazev,''),jmeno_kod),jmeno_kod");$st->execute([$uid]);$animals=$st->fetchAll()?:[];}catch(Throwable){}
if($_SERVER['REQUEST_METHOD']==='POST'){
 ir_verify_csrf();$action=(string)($_POST['action']??'');
 try{
  if($action==='save_rotation'){
   $speciesId=ir_int($_POST['druh_id']??0);if(!$speciesId)throw new RuntimeException('Vyber druh.');$check=$pdo->prepare('SELECT id FROM wp_ir2_druhy WHERE user_id=? AND id=?');$check->execute([$uid,$speciesId]);if(!$check->fetchColumn())throw new RuntimeException('Druh nebyl nalezen.');
   $target=(string)($_POST['cil']??'adult');if(!in_array($target,['all','mlade','juvenile','subadult','adult','breeding'],true))$target='adult';$name=trim((string)($_POST['nazev']??''))?:'Hlavní rotace';$active=!empty($_POST['aktivni'])?1:0;
   $names=(array)($_POST['step_name']??[]);$types=(array)($_POST['step_type']??[]);$notes=(array)($_POST['step_note']??[]);$steps=[];foreach($names as $i=>$n){$n=trim((string)$n);if($n==='')continue;$steps[]=['name'=>$n,'type'=>trim((string)($types[$i]??'Vlastní'))?:'Vlastní','note'=>trim((string)($notes[$i]??''))];}if(!$steps)throw new RuntimeException('Rotace musí mít alespoň jeden krok.');
   $pdo->beginTransaction();$pdo->prepare('INSERT INTO wp_ir2_suplement_rotace(user_id,druh_id,cil,nazev,aktivni) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE nazev=VALUES(nazev),aktivni=VALUES(aktivni),upraveno=CURRENT_TIMESTAMP')->execute([$uid,$speciesId,$target,$name,$active]);$q=$pdo->prepare('SELECT id FROM wp_ir2_suplement_rotace WHERE user_id=? AND druh_id=? AND cil=? LIMIT 1');$q->execute([$uid,$speciesId,$target]);$rid=(int)$q->fetchColumn();$pdo->prepare('DELETE FROM wp_ir2_suplement_kroky WHERE user_id=? AND rotace_id=?')->execute([$uid,$rid]);$in=$pdo->prepare('INSERT INTO wp_ir2_suplement_kroky(user_id,rotace_id,poradi,typ,nazev,poznamka) VALUES(?,?,?,?,?,?)');foreach($steps as $i=>$step)$in->execute([$uid,$rid,$i+1,$step['type'],$step['name'],$step['note']!==''?$step['note']:null]);$pdo->prepare('DELETE FROM wp_ir2_suplement_stav WHERE user_id=? AND rotace_id=?')->execute([$uid,$rid]);$pdo->commit();
   $q=$pdo->prepare('SELECT id FROM wp_ir2_zvirata WHERE user_id=? AND druh_id=?');$q->execute([$uid,$speciesId]);foreach($q->fetchAll(PDO::FETCH_COLUMN)?:[] as $aid)ir_resync_feed_task($pdo,$uid,(int)$aid);ir_flash('success','Suplementační rotace byla uložena a další krmení v Plánovači přepočítána.');ir_redirect('supplements.php');
  }
  if($action==='delete_rotation'){
   $rid=ir_int($_POST['rotation_id']??0);$q=$pdo->prepare('SELECT druh_id FROM wp_ir2_suplement_rotace WHERE user_id=? AND id=?');$q->execute([$uid,$rid]);$speciesId=(int)$q->fetchColumn();if(!$speciesId)throw new RuntimeException('Rotace nebyla nalezena.');$pdo->beginTransaction();$pdo->prepare('DELETE FROM wp_ir2_suplement_stav WHERE user_id=? AND rotace_id=?')->execute([$uid,$rid]);$pdo->prepare('DELETE FROM wp_ir2_suplement_kroky WHERE user_id=? AND rotace_id=?')->execute([$uid,$rid]);$pdo->prepare('DELETE FROM wp_ir2_suplement_rotace WHERE user_id=? AND id=?')->execute([$uid,$rid]);$pdo->commit();$q=$pdo->prepare('SELECT id FROM wp_ir2_zvirata WHERE user_id=? AND druh_id=?');$q->execute([$uid,$speciesId]);foreach($q->fetchAll(PDO::FETCH_COLUMN)?:[] as $aid)ir_resync_feed_task($pdo,$uid,(int)$aid);ir_flash('success','Rotace byla odstraněna.');ir_redirect('supplements.php');
  }
  if($action==='save_independent'){
   $animalId=ir_int($_POST['animal_id']??0);$animal=ir_animal($pdo,$uid,$animalId);if(!$animal)throw new RuntimeException('Vyber zvíře.');$name=trim((string)($_POST['supplement_name']??''));if($name==='')throw new RuntimeException('Vyplň suplement.');$days=max(1,min(3650,ir_int($_POST['interval_days']??30)));$priority=max(1,min(200,ir_int($_POST['priority']??100)));$start=(string)($_POST['start_date']??date('Y-m-d'));if(!strtotime($start))throw new RuntimeException('Neplatné datum.');$task='Suplementace: '.$name;$marker='[IR-SUPP-PRIORITY:'.$priority.']';$pdo->prepare("UPDATE wp_ir2_planovac SET stav='Hotovo' WHERE user_id=? AND zvire_id=? AND stav='Aktivní' AND nazev_ukolu=?")->execute([$uid,$animalId,$task]);$pdo->prepare("INSERT INTO wp_ir2_planovac(user_id,zvire_id,nazev_ukolu,kategorie,datum_termin,priorita,stav,opakovani,interval_hodnota,poznamka) VALUES(?,?,?,'Suplementace',?,'Vysoká','Aktivní','interval',?,?)")->execute([$uid,$animalId,$task,$start,$days,$marker.' Nezávislý suplement s prioritou před běžnou rotací.']);ir_resync_feed_task($pdo,$uid,$animalId);ir_flash('success','Nezávislý suplement byl přidán do Plánovače.');ir_redirect('supplements.php');
  }
  if($action==='delete_independent'){$taskId=ir_int($_POST['task_id']??0);$q=$pdo->prepare("SELECT zvire_id FROM wp_ir2_planovac WHERE user_id=? AND id=? AND nazev_ukolu LIKE 'Suplementace:%'");$q->execute([$uid,$taskId]);$animalId=(int)$q->fetchColumn();if(!$animalId)throw new RuntimeException('Interval nebyl nalezen.');$pdo->prepare('DELETE FROM wp_ir2_planovac WHERE user_id=? AND id=?')->execute([$uid,$taskId]);ir_resync_feed_task($pdo,$uid,$animalId);ir_flash('success','Nezávislý interval byl odstraněn.');ir_redirect('supplements.php');}
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('IR action: '.$e->getMessage());$error=$e instanceof PDOException?'Změnu se nepodařilo uložit. Zkus to znovu.':$e->getMessage();}
}
$rotations=[];$independent=[];
try{$st=$pdo->prepare("SELECT r.*,d.latinsky_nazev,d.cesky_nazev FROM wp_ir2_suplement_rotace r JOIN wp_ir2_druhy d ON d.id=r.druh_id AND d.user_id=r.user_id WHERE r.user_id=? ORDER BY r.aktivni DESC,d.latinsky_nazev,r.cil");$st->execute([$uid]);foreach($st->fetchAll()?:[] as $r){$q=$pdo->prepare('SELECT * FROM wp_ir2_suplement_kroky WHERE user_id=? AND rotace_id=? ORDER BY poradi,id');$q->execute([$uid,(int)$r['id']]);$r['steps']=$q->fetchAll()?:[];$rotations[]=$r;}$st=$pdo->prepare("SELECT p.*,z.jmeno_kod,z.latinsky_nazev FROM wp_ir2_planovac p JOIN wp_ir2_zvirata z ON z.id=p.zvire_id AND z.user_id=p.user_id WHERE p.user_id=? AND p.stav='Aktivní' AND p.nazev_ukolu LIKE 'Suplementace:%' ORDER BY p.datum_termin,p.id");$st->execute([$uid]);$independent=$st->fetchAll()?:[];}catch(Throwable){}
$labels=['all'=>'Všechny kategorie','mlade'=>'Mláďata','juvenile'=>'Juvenile','subadult'=>'Subadult','adult'=>'Adult','breeding'=>'Chovná zvířata'];
ir_page_start('Suplementační rotace','settings');echo ir_back('settings.php','Zpět do nastavení');if(!empty($error))echo '<div class="flash danger">'.ir_e($error).'</div>';
?>
<section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">KRMENÍ · SUPLEMENTACE</span><h2>Automatická rotace</h2><p>Rotace se neposouvá podle kalendáře, ale až po skutečně uloženém krmení. Další krok se automaticky propíše do historie i Plánovače.</p></div></header></section>
<div class="two-column-layout supplement-layout">
<section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">AKTIVNÍ PROTOKOLY</span><h2>Druhové rotace</h2></div><span class="muted-note"><?=count($rotations)?> uložených</span></header><div class="supplement-list">
<?php foreach($rotations as $r):?><article class="supplement-card"><header><div><strong><?=ir_e((string)$r['nazev'])?></strong><small><i><?=ir_e((string)$r['latinsky_nazev'])?></i> · <?=ir_e($labels[$r['cil']]??(string)$r['cil'])?></small></div><span class="status-pill <?=$r['aktivni']?'amber':''?>"><?=$r['aktivni']?'Aktivní':'Pauza'?></span></header><div class="rotation-chain"><?php foreach($r['steps'] as $i=>$step):?><span><b><?=$i+1?></b><strong><?=ir_e((string)($step['nazev']?:$step['typ']))?></strong><small><?=ir_e((string)$step['typ'])?></small></span><?php endforeach;?></div><footer><span>Posun po skutečném krmení</span><form method="post" onsubmit="return confirm('Odstranit rotaci?')"><?=ir_csrf_field()?><input type="hidden" name="rotation_id" value="<?=$r['id']?>"><button class="btn tiny danger" name="action" value="delete_rotation">Smazat</button></form></footer></article><?php endforeach;if(!$rotations):?><div class="empty-state">Zatím bez rotace.</div><?php endif;?></div>
</section>
<aside class="stack">
<form class="panel glow-panel form-panel" method="post"><?=ir_csrf_field()?><input type="hidden" name="action" value="save_rotation"><header class="panel-head"><div><span class="panel-kicker">ROTATION BUILDER</span><h2>Nová / přepsat rotaci</h2></div><button class="btn primary">Uložit</button></header><div class="form-grid cols-2"><label>Druh<select name="druh_id" required><option value="">Vyber druh…</option><?php foreach($species as $sp):?><option value="<?=$sp['id']?>"><?=ir_e((string)$sp['latinsky_nazev'])?></option><?php endforeach;?></select></label><label>Vývojová kategorie<select name="cil"><?php foreach($labels as $k=>$v):?><option value="<?=$k?>" <?=$k==='adult'?'selected':''?>><?=$v?></option><?php endforeach;?></select></label><label>Název<input name="nazev" value="Hlavní rotace"></label><label class="check-line"><input type="checkbox" name="aktivni" value="1" checked><span>Aktivní rotace</span></label></div><div class="rotation-builder" data-rotation-builder><?php for($i=0;$i<6;$i++):?><div class="rotation-builder-row"><b><?=$i+1?></b><input name="step_name[]" placeholder="<?=['Dendrocare','Calcium + D3','Bez suplementu','Dendrocare','Calcium bez D3','Bez suplementu'][$i]?>"><select name="step_type[]"><option>Multivitamin</option><option>Calcium+D3</option><option>Calcium</option><option>Bez</option><option>Vitamin A</option><option>Vlastní</option></select><input name="step_note[]" placeholder="Poznámka"></div><?php endfor;?></div></form>
<form class="panel glow-panel form-panel" method="post"><?=ir_csrf_field()?><input type="hidden" name="action" value="save_independent"><header class="panel-head"><div><span class="panel-kicker">PRIORITA</span><h2>Nezávislý suplement</h2></div></header><div class="form-grid cols-2"><label>Zvíře<select name="animal_id" required><option value="">Vyber zvíře…</option><?php foreach($animals as $a):?><option value="<?=$a['id']?>"><?=ir_e((string)$a['latinsky_nazev'])?> · <?=ir_e((string)$a['jmeno_kod'])?></option><?php endforeach;?></select></label><label>Suplement<input name="supplement_name" required placeholder="Vitamin A"></label><label>Každých dní<input type="number" min="1" name="interval_days" value="30"></label><label>Priorita<input type="number" min="1" max="200" name="priority" value="100"></label><label>První termín<input type="date" name="start_date" value="<?=date('Y-m-d')?>"></label></div><button class="btn secondary">Přidat do Plánovače</button></form>
</aside></div>
<?php if($independent):?><section class="panel glow-panel"><header class="panel-head"><div><span class="panel-kicker">NEZÁVISLÉ INTERVALY</span><h2>Aktivní priority</h2></div></header><div class="simple-list"><?php foreach($independent as $t):?><div class="custom-action-row"><span><?=ir_visual_icon('supplement')?></span><div><strong><?=ir_e((string)$t['nazev_ukolu'])?></strong><span><?=ir_e((string)$t['latinsky_nazev'])?> · <?=date('d.m.Y',strtotime((string)$t['datum_termin']))?></span></div><form method="post" onsubmit="return confirm('Odstranit interval?')"><?=ir_csrf_field()?><input type="hidden" name="task_id" value="<?=$t['id']?>"><button class="btn tiny danger" name="action" value="delete_independent">Smazat</button></form></div><?php endforeach;?></div></section><?php endif;?>
<?php ir_page_end();
