<?php
/** Repair imported aliases and connect the existing group records, retaining original rows. */
if(!ir_db_column_exists($pdo,'wp_ir2_druhy','merged_into_id'))$pdo->exec('ALTER TABLE wp_ir2_druhy ADD COLUMN merged_into_id INT UNSIGNED NULL');
if(!ir_db_column_exists($pdo,'wp_ir2_skupiny','main_animal_id'))$pdo->exec('ALTER TABLE wp_ir2_skupiny ADD COLUMN main_animal_id INT UNSIGNED NULL, ADD INDEX main_animal(user_id,main_animal_id)');
$pdo->exec('CREATE TABLE IF NOT EXISTS wp_ir2_repair_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, repair_key VARCHAR(100) NOT NULL, user_id INT NOT NULL, object_table VARCHAR(80) NOT NULL, object_id INT NOT NULL, previous_json LONGTEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY repair_object(repair_key,user_id,object_table,object_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
$backup=static function(string $key,string $table,array $row)use($pdo):void{$pdo->prepare('INSERT IGNORE INTO wp_ir2_repair_history(repair_key,user_id,object_table,object_id,previous_json) VALUES(?,?,?,?,?)')->execute([$key,$row['user_id'],$table,$row['id'],json_encode($row,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)]);};
$pdo->beginTransaction();
try{
 $q=$pdo->query("SELECT * FROM wp_ir2_druhy WHERE LOWER(latinsky_nazev) IN ('dendrobates tinctorius azureus','dendrobates tinctorius f. azureus','dendrobates azureus') ORDER BY id");$byUser=[];foreach($q as $row)$byUser[$row['user_id']][]=$row;
 foreach($byUser as $uid=>$rows){$canonical=$rows[0];foreach($rows as $r)if($r['latinsky_nazev']==='Dendrobates tinctorius f. azureus')$canonical=$r;$keep=(int)$canonical['id'];$backup('046-species','wp_ir2_druhy',$canonical);$pdo->prepare('UPDATE wp_ir2_druhy SET latinsky_nazev=?,merged_into_id=NULL WHERE user_id=? AND id=?')->execute(['Dendrobates tinctorius azureus',$uid,$keep]);
  foreach($rows as $r){if((int)$r['id']===$keep)continue;$backup('046-species','wp_ir2_druhy',$r);foreach(['wp_ir2_pece_pravidla','wp_ir2_repro_faze','wp_ir2_rodokmen_osoby','wp_ir2_skupiny','wp_ir2_snusky','wp_ir2_suplement_rotace','wp_ir2_zvirata'] as $table){$q=$pdo->prepare("SELECT * FROM `$table` WHERE user_id=? AND druh_id=?");$q->execute([$uid,$r['id']]);foreach($q as $row)$backup('046-species',$table,$row);$pdo->prepare("UPDATE `$table` SET druh_id=? WHERE user_id=? AND druh_id=?")->execute([$keep,$uid,$r['id']]);}$pdo->prepare('UPDATE wp_ir2_druhy SET merged_into_id=? WHERE user_id=? AND id=?')->execute([$keep,$uid,$r['id']]);}
  $q=$pdo->prepare("SELECT * FROM wp_ir2_zvirata WHERE user_id=? AND pohlavi='Skupina' AND LOWER(jmeno_kod) LIKE '%azureus%' ORDER BY id");$q->execute([$uid]);$main=$q->fetch();if($main){$q=$pdo->prepare("SELECT * FROM wp_ir2_skupiny WHERE user_id=? AND LOWER(nazev) LIKE '%azureus%' ORDER BY id");$q->execute([$uid]);foreach($q as $g){$backup('046-group',$gtable='wp_ir2_skupiny',$g);$pdo->prepare('UPDATE wp_ir2_skupiny SET main_animal_id=?,druh_id=?,ubikace_id=? WHERE user_id=? AND id=?')->execute([$main['id'],$keep,$main['ubikace_id'],$uid,$g['id']]);}}
 }
 // Existing individual memberships identify their existing main animal card.
 $maps=$pdo->query("SELECT c.user_id,c.skupina_id,MIN(z.skupina_parent_id) parent_id FROM wp_ir2_skupiny_clenove c JOIN wp_ir2_zvirata z ON z.id=c.zvire_id AND z.user_id=c.user_id WHERE c.datum_do IS NULL AND z.skupina_parent_id IS NOT NULL GROUP BY c.user_id,c.skupina_id HAVING COUNT(DISTINCT z.skupina_parent_id)=1")->fetchAll();foreach($maps as $m)$pdo->prepare('UPDATE wp_ir2_skupiny SET main_animal_id=? WHERE user_id=? AND id=? AND main_animal_id IS NULL')->execute([$m['parent_id'],$m['user_id'],$m['skupina_id']]);
 // The supplied import contains five automatically numbered Azureus records.
 // User explicitly requested four; retain the unused fifth in Archive with a repair snapshot.
 $q=$pdo->query("SELECT * FROM wp_ir2_zvirata WHERE id=35 AND user_id=1 AND skupina_parent_id=30 AND jmeno_kod LIKE '%azureus%05' AND status_chovu='Aktivní'");$extra=$q->fetch();
 if($extra){$used=0;foreach(['wp_ir2_pece','wp_ir2_zdravi','wp_ir2_zvire_fotky'] as $table){$q=$pdo->prepare("SELECT COUNT(*) FROM `$table` WHERE user_id=1 AND zvire_id=35");$q->execute();$used+=(int)$q->fetchColumn();}$q=$pdo->query('SELECT COUNT(*) FROM wp_ir2_zvirata WHERE user_id=1 AND (otec_id=35 OR matka_id=35)');$used+=(int)$q->fetchColumn();if(!$used){$backup('046-azureus-four','wp_ir2_zvirata',$extra);$pdo->prepare("UPDATE wp_ir2_zvirata SET status_chovu='Archiv',poznamka=CONCAT(COALESCE(poznamka,''),?) WHERE id=35 AND user_id=1")->execute(["\n[Oprava 046] Nevyužitá pátá importovaná karta; skupina má podle zadání 4 jedince. Záznam zachován pro obnovu."]);}}
 foreach($pdo->query('SELECT * FROM wp_ir2_skupiny WHERE main_animal_id IS NOT NULL')->fetchAll() as $g){$q=$pdo->prepare("SELECT id FROM wp_ir2_zvirata WHERE user_id=? AND skupina_parent_id=? AND status_chovu NOT IN ('Archiv','Prodáno','Uhynulo','Mrtvé','Dead','Sold')");$q->execute([$g['user_id'],$g['main_animal_id']]);$ids=$q->fetchAll(PDO::FETCH_COLUMN);foreach($ids as $aid){$check=$pdo->prepare("SELECT id FROM wp_ir2_skupiny_clenove WHERE user_id=? AND skupina_id=? AND zvire_id=? AND datum_do IS NULL");$check->execute([$g['user_id'],$g['id'],$aid]);if(!$check->fetchColumn())$pdo->prepare("INSERT INTO wp_ir2_skupiny_clenove(user_id,skupina_id,zvire_id,datum_od,stav) VALUES(?,?,?,CURDATE(),'Ve skupině')")->execute([$g['user_id'],$g['id'],$aid]);}$pdo->prepare('UPDATE wp_ir2_skupiny SET pocet=? WHERE user_id=? AND id=?')->execute([count($ids),$g['user_id'],$g['id']]);}
 $pdo->commit();echo "Migrace 046: katalog a vazby skupin sjednoceny; původní data zachována v historii oprav.\n";
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
